// @generated by ferroterm-fhir-codegen from hl7.fhir.r5.core 5.0.0. DO NOT EDIT.
// Change the emitter (tools/ferroterm-fhir-codegen) and regenerate.
//! `CodeSystem/$validate-code`.
//!
//! Validate that a coded value is in the code system. If the operation is
//! not called at the instance level, one of the parameters "url" or
//! "codeSystem" must be provided. The operation returns a result (true /
//! false), an error message, and the recommended display for the code. When
//! invoking this operation, a client \*\*SHALL\*\* provide one (and only
//! one) of the parameters (code+system, coding, or codeableConcept). Other
//! parameters (including version and display) are optional. When validating
//! a code or a coding, then the code, system and version output parameters
//! \*\*SHOULD\*\* be populated when possible. When a validating a
//! CodeableConcept, then the codeableConcept output parameter
//! \*\*SHOULD\*\* be populated when possible.

/// The `in` parameters of `CodeSystem/$validate-code`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CodeSystemValidateCodeRequest {
    /// CodeSystem URL. The server must know the code system (e.g. it is defined
    /// explicitly in the server'scode systems, or it is known implicitly by the
    /// server
    pub url: Option<super::super::primitives::Uri>,
    /// The codeSystem is provided directly as part of the request. Servers may
    /// choose not to accept code systems in this fashion. This parameter is
    /// used when the client wants the server to check against a code system
    /// that is not stored on the server
    pub code_system: Option<super::super::code_system::CodeSystem>,
    /// The code that is to be validated
    pub code: Option<super::super::primitives::Code>,
    /// The version of the code system, if one was provided in the source data
    pub version: Option<super::super::primitives::String>,
    /// The display associated with the code, if provided. If a display is
    /// provided a code must be provided. If no display is provided, the server
    /// cannot validate the display value, but may choose to return a
    /// recommended display name in an extension in the outcome. Whether
    /// displays are case sensitive is code system dependent
    pub display: Option<super::super::primitives::String>,
    /// A coding to validate. The system must match the specified code system
    pub coding: Option<super::super::coding::Coding>,
    /// A full codeableConcept to validate. The server returns true if one of
    /// the coding values is in the code system, and may also validate that the
    /// codings are not in conflict with each other if more than one is present
    pub codeable_concept: Option<super::super::codeable_concept::CodeableConcept>,
    /// The date for which the validation should be checked. Normally, this is
    /// the current conditions (which is the default values) but under some
    /// circumstances, systems need to validate that a correct code was used at
    /// some point in the past. A typical example of this would be where code
    /// selection is constrained to the set of codes that were available when
    /// the patient was treated, not when the record is being edited. Note that
    /// which date is appropriate is a matter for implementation policy.
    pub date: Option<super::super::primitives::DateTime>,
    /// If this parameter has a value of true, the client is stating that the
    /// validation is being performed in a context where a concept designated as
    /// 'abstract' is appropriate/allowed to be used, and the server should
    /// regard abstract codes as valid. If this parameter is false, abstract
    /// codes are not considered to be valid. Note that. 'abstract' is a
    /// property defined by many HL7 code systems that indicates that the
    /// concept is a logical grouping concept that is not intended to be used
    /// asa 'concrete' concept to in an actual patient/care/process record. This
    /// language is borrowed from Object Orienated theory where 'asbtract'
    /// objects are never instantiated. However in the general record and
    /// terminology eco-system, there are many contexts where it is appropraite
    /// to use these codes e.g. as decision making criterion, or when editing
    /// value sets themselves. This parameter allows a client to indicate to the
    /// server that it is working in such a context.
    pub r#abstract: Option<super::super::primitives::Boolean>,
    /// Specifies the language to be used for description when validating the
    /// display property
    pub display_language: Option<super::super::primitives::Code>,
}

/// The `out` parameters of `CodeSystem/$validate-code`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CodeSystemValidateCodeResponse {
    /// True if the concept details supplied are valid
    pub result: super::super::primitives::Boolean,
    /// Error details, if result = false. If this is provided when result =
    /// true, the message carries hints and warnings
    pub message: Option<super::super::primitives::String>,
    /// A valid display for the concept if the system wishes to display this to
    /// a user
    pub display: Option<super::super::primitives::String>,
    /// The code that was validated
    pub code: Option<super::super::primitives::Code>,
    /// The system for the code that was validated
    pub system: Option<super::super::primitives::Uri>,
    /// The version of the system of the code that was validated
    pub version: Option<super::super::primitives::String>,
    /// A codeableConcept containing codings for all the validated codes
    pub codeable_concept: Option<super::super::codeable_concept::CodeableConcept>,
    /// List of itemised issues with paths constrained to simple FHIRPath.
    /// Examples are CodeableConcept, CodeableConcept.coding\[0\],
    /// CodeableConcept.coding\[1\].display, or Coding.display
    pub issues: Option<super::super::operation_outcome::OperationOutcome>,
}

impl CodeSystemValidateCodeRequest {
    /// Reads the parameters from a `Parameters` resource.
    ///
    /// # Errors
    ///
    /// Returns the error for an undeclared, repeated, missing, or wrongly typed parameter.
    pub fn from_parameters(
        parameters: &super::super::parameters::Parameters,
    ) -> Result<Self, super::super::super::operation::ParametersError> {
        Self::from_parameter_list(&parameters.parameter)
    }
    /// Writes the parameters as a `Parameters` resource.
    #[must_use]
    pub fn to_parameters(&self) -> super::super::parameters::Parameters {
        super::super::parameters::Parameters {
            parameter: self.to_parameter_list(),
            ..Default::default()
        }
    }
    /// Reads the fields from a parameter list.
    ///
    /// # Errors
    ///
    /// Returns the error for an undeclared, repeated, missing, or wrongly typed parameter.
    pub fn from_parameter_list(
        list: &[super::super::parameters::ParametersParameter],
    ) -> Result<Self, super::super::super::operation::ParametersError> {
        const OPERATION: &str = "CodeSystem/$validate-code";
        const PREFIX: &str = "";
        let mut field_url: Option<super::super::primitives::Uri> = None;
        let mut field_code_system: Option<super::super::code_system::CodeSystem> = None;
        let mut field_code: Option<super::super::primitives::Code> = None;
        let mut field_version: Option<super::super::primitives::String> = None;
        let mut field_display: Option<super::super::primitives::String> = None;
        let mut field_coding: Option<super::super::coding::Coding> = None;
        let mut field_codeable_concept: Option<super::super::codeable_concept::CodeableConcept> =
            None;
        let mut field_date: Option<super::super::primitives::DateTime> = None;
        let mut field_abstract: Option<super::super::primitives::Boolean> = None;
        let mut field_display_language: Option<super::super::primitives::Code> = None;
        for parameter in list {
            let parameter_name = parameter.name.value.as_deref().ok_or(
                super::super::super::operation::ParametersError::Unnamed {
                    operation: OPERATION,
                },
            )?;
            match parameter_name {
                "url" => {
                    if field_url.is_some() {
                        return Err(super::super::super::operation::ParametersError::Repeated {
                            operation: OPERATION,
                            name: "url",
                        });
                    }
                    field_url = Some(match &parameter.value {
                        Some(super::super::parameters::ParametersParameterValue::Uri(value)) => {
                            value.clone()
                        }
                        Some(_) => {
                            return Err(
                                super::super::super::operation::ParametersError::WrongType {
                                    operation: OPERATION,
                                    name: "url",
                                    expected: "Uri",
                                },
                            );
                        }
                        None => {
                            return Err(
                                super::super::super::operation::ParametersError::MissingValue {
                                    operation: OPERATION,
                                    name: "url",
                                },
                            );
                        }
                    });
                }
                "codeSystem" => {
                    if field_code_system.is_some() {
                        return Err(super::super::super::operation::ParametersError::Repeated {
                            operation: OPERATION,
                            name: "codeSystem",
                        });
                    }
                    field_code_system = Some(match &parameter.resource {
                        Some(super::super::resource::Resource::CodeSystem(value)) => {
                            (**value).clone()
                        }
                        Some(_) => {
                            return Err(
                                super::super::super::operation::ParametersError::WrongType {
                                    operation: OPERATION,
                                    name: "codeSystem",
                                    expected: "CodeSystem",
                                },
                            );
                        }
                        None => {
                            return Err(
                                super::super::super::operation::ParametersError::MissingValue {
                                    operation: OPERATION,
                                    name: "codeSystem",
                                },
                            );
                        }
                    });
                }
                "code" => {
                    if field_code.is_some() {
                        return Err(super::super::super::operation::ParametersError::Repeated {
                            operation: OPERATION,
                            name: "code",
                        });
                    }
                    field_code = Some(match &parameter.value {
                        Some(super::super::parameters::ParametersParameterValue::Code(value)) => {
                            value.clone()
                        }
                        Some(_) => {
                            return Err(
                                super::super::super::operation::ParametersError::WrongType {
                                    operation: OPERATION,
                                    name: "code",
                                    expected: "Code",
                                },
                            );
                        }
                        None => {
                            return Err(
                                super::super::super::operation::ParametersError::MissingValue {
                                    operation: OPERATION,
                                    name: "code",
                                },
                            );
                        }
                    });
                }
                "version" => {
                    if field_version.is_some() {
                        return Err(super::super::super::operation::ParametersError::Repeated {
                            operation: OPERATION,
                            name: "version",
                        });
                    }
                    field_version = Some(match &parameter.value {
                        Some(super::super::parameters::ParametersParameterValue::String(value)) => {
                            value.clone()
                        }
                        Some(_) => {
                            return Err(
                                super::super::super::operation::ParametersError::WrongType {
                                    operation: OPERATION,
                                    name: "version",
                                    expected: "String",
                                },
                            );
                        }
                        None => {
                            return Err(
                                super::super::super::operation::ParametersError::MissingValue {
                                    operation: OPERATION,
                                    name: "version",
                                },
                            );
                        }
                    });
                }
                "display" => {
                    if field_display.is_some() {
                        return Err(super::super::super::operation::ParametersError::Repeated {
                            operation: OPERATION,
                            name: "display",
                        });
                    }
                    field_display = Some(match &parameter.value {
                        Some(super::super::parameters::ParametersParameterValue::String(value)) => {
                            value.clone()
                        }
                        Some(_) => {
                            return Err(
                                super::super::super::operation::ParametersError::WrongType {
                                    operation: OPERATION,
                                    name: "display",
                                    expected: "String",
                                },
                            );
                        }
                        None => {
                            return Err(
                                super::super::super::operation::ParametersError::MissingValue {
                                    operation: OPERATION,
                                    name: "display",
                                },
                            );
                        }
                    });
                }
                "coding" => {
                    if field_coding.is_some() {
                        return Err(super::super::super::operation::ParametersError::Repeated {
                            operation: OPERATION,
                            name: "coding",
                        });
                    }
                    field_coding = Some(match &parameter.value {
                        Some(super::super::parameters::ParametersParameterValue::Coding(value)) => {
                            value.clone()
                        }
                        Some(_) => {
                            return Err(
                                super::super::super::operation::ParametersError::WrongType {
                                    operation: OPERATION,
                                    name: "coding",
                                    expected: "Coding",
                                },
                            );
                        }
                        None => {
                            return Err(
                                super::super::super::operation::ParametersError::MissingValue {
                                    operation: OPERATION,
                                    name: "coding",
                                },
                            );
                        }
                    });
                }
                "codeableConcept" => {
                    if field_codeable_concept.is_some() {
                        return Err(super::super::super::operation::ParametersError::Repeated {
                            operation: OPERATION,
                            name: "codeableConcept",
                        });
                    }
                    field_codeable_concept = Some(match &parameter.value {
                        Some(
                            super::super::parameters::ParametersParameterValue::CodeableConcept(
                                value,
                            ),
                        ) => value.clone(),
                        Some(_) => {
                            return Err(
                                super::super::super::operation::ParametersError::WrongType {
                                    operation: OPERATION,
                                    name: "codeableConcept",
                                    expected: "CodeableConcept",
                                },
                            );
                        }
                        None => {
                            return Err(
                                super::super::super::operation::ParametersError::MissingValue {
                                    operation: OPERATION,
                                    name: "codeableConcept",
                                },
                            );
                        }
                    });
                }
                "date" => {
                    if field_date.is_some() {
                        return Err(super::super::super::operation::ParametersError::Repeated {
                            operation: OPERATION,
                            name: "date",
                        });
                    }
                    field_date = Some(match &parameter.value {
                        Some(super::super::parameters::ParametersParameterValue::DateTime(
                            value,
                        )) => value.clone(),
                        Some(_) => {
                            return Err(
                                super::super::super::operation::ParametersError::WrongType {
                                    operation: OPERATION,
                                    name: "date",
                                    expected: "DateTime",
                                },
                            );
                        }
                        None => {
                            return Err(
                                super::super::super::operation::ParametersError::MissingValue {
                                    operation: OPERATION,
                                    name: "date",
                                },
                            );
                        }
                    });
                }
                "abstract" => {
                    if field_abstract.is_some() {
                        return Err(super::super::super::operation::ParametersError::Repeated {
                            operation: OPERATION,
                            name: "abstract",
                        });
                    }
                    field_abstract = Some(match &parameter.value {
                        Some(super::super::parameters::ParametersParameterValue::Boolean(
                            value,
                        )) => value.clone(),
                        Some(_) => {
                            return Err(
                                super::super::super::operation::ParametersError::WrongType {
                                    operation: OPERATION,
                                    name: "abstract",
                                    expected: "Boolean",
                                },
                            );
                        }
                        None => {
                            return Err(
                                super::super::super::operation::ParametersError::MissingValue {
                                    operation: OPERATION,
                                    name: "abstract",
                                },
                            );
                        }
                    });
                }
                "displayLanguage" => {
                    if field_display_language.is_some() {
                        return Err(super::super::super::operation::ParametersError::Repeated {
                            operation: OPERATION,
                            name: "displayLanguage",
                        });
                    }
                    field_display_language = Some(match &parameter.value {
                        Some(super::super::parameters::ParametersParameterValue::Code(value)) => {
                            value.clone()
                        }
                        Some(_) => {
                            return Err(
                                super::super::super::operation::ParametersError::WrongType {
                                    operation: OPERATION,
                                    name: "displayLanguage",
                                    expected: "Code",
                                },
                            );
                        }
                        None => {
                            return Err(
                                super::super::super::operation::ParametersError::MissingValue {
                                    operation: OPERATION,
                                    name: "displayLanguage",
                                },
                            );
                        }
                    });
                }
                other => {
                    return Err(
                        super::super::super::operation::ParametersError::Undeclared {
                            operation: OPERATION,
                            name: [PREFIX, other].concat(),
                        },
                    );
                }
            }
        }
        Ok(Self {
            url: field_url,
            code_system: field_code_system,
            code: field_code,
            version: field_version,
            display: field_display,
            coding: field_coding,
            codeable_concept: field_codeable_concept,
            date: field_date,
            r#abstract: field_abstract,
            display_language: field_display_language,
        })
    }
    /// Writes the fields as a parameter list.
    #[must_use]
    pub fn to_parameter_list(&self) -> Vec<super::super::parameters::ParametersParameter> {
        let mut out = Vec::new();
        if let Some(value) = &self.url {
            out.push(super::super::parameters::ParametersParameter {
                name: "url".into(),
                value: Some(super::super::parameters::ParametersParameterValue::Uri(
                    value.clone(),
                )),
                ..Default::default()
            });
        }
        if let Some(value) = &self.code_system {
            out.push(super::super::parameters::ParametersParameter {
                name: "codeSystem".into(),
                resource: Some(super::super::resource::Resource::CodeSystem(Box::new(
                    value.clone(),
                ))),
                ..Default::default()
            });
        }
        if let Some(value) = &self.code {
            out.push(super::super::parameters::ParametersParameter {
                name: "code".into(),
                value: Some(super::super::parameters::ParametersParameterValue::Code(
                    value.clone(),
                )),
                ..Default::default()
            });
        }
        if let Some(value) = &self.version {
            out.push(super::super::parameters::ParametersParameter {
                name: "version".into(),
                value: Some(super::super::parameters::ParametersParameterValue::String(
                    value.clone(),
                )),
                ..Default::default()
            });
        }
        if let Some(value) = &self.display {
            out.push(super::super::parameters::ParametersParameter {
                name: "display".into(),
                value: Some(super::super::parameters::ParametersParameterValue::String(
                    value.clone(),
                )),
                ..Default::default()
            });
        }
        if let Some(value) = &self.coding {
            out.push(super::super::parameters::ParametersParameter {
                name: "coding".into(),
                value: Some(super::super::parameters::ParametersParameterValue::Coding(
                    value.clone(),
                )),
                ..Default::default()
            });
        }
        if let Some(value) = &self.codeable_concept {
            out.push(super::super::parameters::ParametersParameter {
                name: "codeableConcept".into(),
                value: Some(
                    super::super::parameters::ParametersParameterValue::CodeableConcept(
                        value.clone(),
                    ),
                ),
                ..Default::default()
            });
        }
        if let Some(value) = &self.date {
            out.push(super::super::parameters::ParametersParameter {
                name: "date".into(),
                value: Some(
                    super::super::parameters::ParametersParameterValue::DateTime(value.clone()),
                ),
                ..Default::default()
            });
        }
        if let Some(value) = &self.r#abstract {
            out.push(super::super::parameters::ParametersParameter {
                name: "abstract".into(),
                value: Some(super::super::parameters::ParametersParameterValue::Boolean(
                    value.clone(),
                )),
                ..Default::default()
            });
        }
        if let Some(value) = &self.display_language {
            out.push(super::super::parameters::ParametersParameter {
                name: "displayLanguage".into(),
                value: Some(super::super::parameters::ParametersParameterValue::Code(
                    value.clone(),
                )),
                ..Default::default()
            });
        }
        out
    }
}

impl CodeSystemValidateCodeResponse {
    /// Reads the parameters from a `Parameters` resource.
    ///
    /// # Errors
    ///
    /// Returns the error for an undeclared, repeated, missing, or wrongly typed parameter.
    pub fn from_parameters(
        parameters: &super::super::parameters::Parameters,
    ) -> Result<Self, super::super::super::operation::ParametersError> {
        Self::from_parameter_list(&parameters.parameter)
    }
    /// Writes the parameters as a `Parameters` resource.
    #[must_use]
    pub fn to_parameters(&self) -> super::super::parameters::Parameters {
        super::super::parameters::Parameters {
            parameter: self.to_parameter_list(),
            ..Default::default()
        }
    }
    /// Reads the fields from a parameter list.
    ///
    /// # Errors
    ///
    /// Returns the error for an undeclared, repeated, missing, or wrongly typed parameter.
    pub fn from_parameter_list(
        list: &[super::super::parameters::ParametersParameter],
    ) -> Result<Self, super::super::super::operation::ParametersError> {
        const OPERATION: &str = "CodeSystem/$validate-code";
        const PREFIX: &str = "";
        let mut field_result: Option<super::super::primitives::Boolean> = None;
        let mut field_message: Option<super::super::primitives::String> = None;
        let mut field_display: Option<super::super::primitives::String> = None;
        let mut field_code: Option<super::super::primitives::Code> = None;
        let mut field_system: Option<super::super::primitives::Uri> = None;
        let mut field_version: Option<super::super::primitives::String> = None;
        let mut field_codeable_concept: Option<super::super::codeable_concept::CodeableConcept> =
            None;
        let mut field_issues: Option<super::super::operation_outcome::OperationOutcome> = None;
        for parameter in list {
            let parameter_name = parameter.name.value.as_deref().ok_or(
                super::super::super::operation::ParametersError::Unnamed {
                    operation: OPERATION,
                },
            )?;
            match parameter_name {
                "result" => {
                    if field_result.is_some() {
                        return Err(super::super::super::operation::ParametersError::Repeated {
                            operation: OPERATION,
                            name: "result",
                        });
                    }
                    field_result = Some(match &parameter.value {
                        Some(super::super::parameters::ParametersParameterValue::Boolean(
                            value,
                        )) => value.clone(),
                        Some(_) => {
                            return Err(
                                super::super::super::operation::ParametersError::WrongType {
                                    operation: OPERATION,
                                    name: "result",
                                    expected: "Boolean",
                                },
                            );
                        }
                        None => {
                            return Err(
                                super::super::super::operation::ParametersError::MissingValue {
                                    operation: OPERATION,
                                    name: "result",
                                },
                            );
                        }
                    });
                }
                "message" => {
                    if field_message.is_some() {
                        return Err(super::super::super::operation::ParametersError::Repeated {
                            operation: OPERATION,
                            name: "message",
                        });
                    }
                    field_message = Some(match &parameter.value {
                        Some(super::super::parameters::ParametersParameterValue::String(value)) => {
                            value.clone()
                        }
                        Some(_) => {
                            return Err(
                                super::super::super::operation::ParametersError::WrongType {
                                    operation: OPERATION,
                                    name: "message",
                                    expected: "String",
                                },
                            );
                        }
                        None => {
                            return Err(
                                super::super::super::operation::ParametersError::MissingValue {
                                    operation: OPERATION,
                                    name: "message",
                                },
                            );
                        }
                    });
                }
                "display" => {
                    if field_display.is_some() {
                        return Err(super::super::super::operation::ParametersError::Repeated {
                            operation: OPERATION,
                            name: "display",
                        });
                    }
                    field_display = Some(match &parameter.value {
                        Some(super::super::parameters::ParametersParameterValue::String(value)) => {
                            value.clone()
                        }
                        Some(_) => {
                            return Err(
                                super::super::super::operation::ParametersError::WrongType {
                                    operation: OPERATION,
                                    name: "display",
                                    expected: "String",
                                },
                            );
                        }
                        None => {
                            return Err(
                                super::super::super::operation::ParametersError::MissingValue {
                                    operation: OPERATION,
                                    name: "display",
                                },
                            );
                        }
                    });
                }
                "code" => {
                    if field_code.is_some() {
                        return Err(super::super::super::operation::ParametersError::Repeated {
                            operation: OPERATION,
                            name: "code",
                        });
                    }
                    field_code = Some(match &parameter.value {
                        Some(super::super::parameters::ParametersParameterValue::Code(value)) => {
                            value.clone()
                        }
                        Some(_) => {
                            return Err(
                                super::super::super::operation::ParametersError::WrongType {
                                    operation: OPERATION,
                                    name: "code",
                                    expected: "Code",
                                },
                            );
                        }
                        None => {
                            return Err(
                                super::super::super::operation::ParametersError::MissingValue {
                                    operation: OPERATION,
                                    name: "code",
                                },
                            );
                        }
                    });
                }
                "system" => {
                    if field_system.is_some() {
                        return Err(super::super::super::operation::ParametersError::Repeated {
                            operation: OPERATION,
                            name: "system",
                        });
                    }
                    field_system = Some(match &parameter.value {
                        Some(super::super::parameters::ParametersParameterValue::Uri(value)) => {
                            value.clone()
                        }
                        Some(_) => {
                            return Err(
                                super::super::super::operation::ParametersError::WrongType {
                                    operation: OPERATION,
                                    name: "system",
                                    expected: "Uri",
                                },
                            );
                        }
                        None => {
                            return Err(
                                super::super::super::operation::ParametersError::MissingValue {
                                    operation: OPERATION,
                                    name: "system",
                                },
                            );
                        }
                    });
                }
                "version" => {
                    if field_version.is_some() {
                        return Err(super::super::super::operation::ParametersError::Repeated {
                            operation: OPERATION,
                            name: "version",
                        });
                    }
                    field_version = Some(match &parameter.value {
                        Some(super::super::parameters::ParametersParameterValue::String(value)) => {
                            value.clone()
                        }
                        Some(_) => {
                            return Err(
                                super::super::super::operation::ParametersError::WrongType {
                                    operation: OPERATION,
                                    name: "version",
                                    expected: "String",
                                },
                            );
                        }
                        None => {
                            return Err(
                                super::super::super::operation::ParametersError::MissingValue {
                                    operation: OPERATION,
                                    name: "version",
                                },
                            );
                        }
                    });
                }
                "codeableConcept" => {
                    if field_codeable_concept.is_some() {
                        return Err(super::super::super::operation::ParametersError::Repeated {
                            operation: OPERATION,
                            name: "codeableConcept",
                        });
                    }
                    field_codeable_concept = Some(match &parameter.value {
                        Some(
                            super::super::parameters::ParametersParameterValue::CodeableConcept(
                                value,
                            ),
                        ) => value.clone(),
                        Some(_) => {
                            return Err(
                                super::super::super::operation::ParametersError::WrongType {
                                    operation: OPERATION,
                                    name: "codeableConcept",
                                    expected: "CodeableConcept",
                                },
                            );
                        }
                        None => {
                            return Err(
                                super::super::super::operation::ParametersError::MissingValue {
                                    operation: OPERATION,
                                    name: "codeableConcept",
                                },
                            );
                        }
                    });
                }
                "issues" => {
                    if field_issues.is_some() {
                        return Err(super::super::super::operation::ParametersError::Repeated {
                            operation: OPERATION,
                            name: "issues",
                        });
                    }
                    field_issues = Some(match &parameter.resource {
                        Some(super::super::resource::Resource::OperationOutcome(value)) => {
                            (**value).clone()
                        }
                        Some(_) => {
                            return Err(
                                super::super::super::operation::ParametersError::WrongType {
                                    operation: OPERATION,
                                    name: "issues",
                                    expected: "OperationOutcome",
                                },
                            );
                        }
                        None => {
                            return Err(
                                super::super::super::operation::ParametersError::MissingValue {
                                    operation: OPERATION,
                                    name: "issues",
                                },
                            );
                        }
                    });
                }
                other => {
                    return Err(
                        super::super::super::operation::ParametersError::Undeclared {
                            operation: OPERATION,
                            name: [PREFIX, other].concat(),
                        },
                    );
                }
            }
        }
        Ok(Self {
            result: field_result.ok_or(
                super::super::super::operation::ParametersError::Missing {
                    operation: OPERATION,
                    name: "result",
                },
            )?,
            message: field_message,
            display: field_display,
            code: field_code,
            system: field_system,
            version: field_version,
            codeable_concept: field_codeable_concept,
            issues: field_issues,
        })
    }
    /// Writes the fields as a parameter list.
    #[must_use]
    pub fn to_parameter_list(&self) -> Vec<super::super::parameters::ParametersParameter> {
        let mut out = Vec::new();
        {
            let value = &self.result;
            out.push(super::super::parameters::ParametersParameter {
                name: "result".into(),
                value: Some(super::super::parameters::ParametersParameterValue::Boolean(
                    value.clone(),
                )),
                ..Default::default()
            });
        }
        if let Some(value) = &self.message {
            out.push(super::super::parameters::ParametersParameter {
                name: "message".into(),
                value: Some(super::super::parameters::ParametersParameterValue::String(
                    value.clone(),
                )),
                ..Default::default()
            });
        }
        if let Some(value) = &self.display {
            out.push(super::super::parameters::ParametersParameter {
                name: "display".into(),
                value: Some(super::super::parameters::ParametersParameterValue::String(
                    value.clone(),
                )),
                ..Default::default()
            });
        }
        if let Some(value) = &self.code {
            out.push(super::super::parameters::ParametersParameter {
                name: "code".into(),
                value: Some(super::super::parameters::ParametersParameterValue::Code(
                    value.clone(),
                )),
                ..Default::default()
            });
        }
        if let Some(value) = &self.system {
            out.push(super::super::parameters::ParametersParameter {
                name: "system".into(),
                value: Some(super::super::parameters::ParametersParameterValue::Uri(
                    value.clone(),
                )),
                ..Default::default()
            });
        }
        if let Some(value) = &self.version {
            out.push(super::super::parameters::ParametersParameter {
                name: "version".into(),
                value: Some(super::super::parameters::ParametersParameterValue::String(
                    value.clone(),
                )),
                ..Default::default()
            });
        }
        if let Some(value) = &self.codeable_concept {
            out.push(super::super::parameters::ParametersParameter {
                name: "codeableConcept".into(),
                value: Some(
                    super::super::parameters::ParametersParameterValue::CodeableConcept(
                        value.clone(),
                    ),
                ),
                ..Default::default()
            });
        }
        if let Some(value) = &self.issues {
            out.push(super::super::parameters::ParametersParameter {
                name: "issues".into(),
                resource: Some(super::super::resource::Resource::OperationOutcome(
                    Box::new(value.clone()),
                )),
                ..Default::default()
            });
        }
        out
    }
}

/// The declared parameter set of `CodeSystem/$validate-code`.
pub const CODE_SYSTEM_VALIDATE_CODE: super::super::super::operation::Operation =
    super::super::super::operation::Operation {
        url: "http://hl7.org/fhir/OperationDefinition/CodeSystem-validate-code",
        resource: "CodeSystem",
        code: "validate-code",
        system: false,
        type_level: true,
        instance: true,
        parameters: &[
            super::super::super::operation::Parameter {
                name: "url",
                usage: super::super::super::operation::ParameterUse::In,
                cardinality: super::super::super::operation::Cardinality {
                    min: 0,
                    max: Some(1),
                },
                type_code: Some("uri"),
                scope: &["type"],
                parts: &[],
            },
            super::super::super::operation::Parameter {
                name: "codeSystem",
                usage: super::super::super::operation::ParameterUse::In,
                cardinality: super::super::super::operation::Cardinality {
                    min: 0,
                    max: Some(1),
                },
                type_code: Some("CodeSystem"),
                scope: &["type"],
                parts: &[],
            },
            super::super::super::operation::Parameter {
                name: "code",
                usage: super::super::super::operation::ParameterUse::In,
                cardinality: super::super::super::operation::Cardinality {
                    min: 0,
                    max: Some(1),
                },
                type_code: Some("code"),
                scope: &[],
                parts: &[],
            },
            super::super::super::operation::Parameter {
                name: "version",
                usage: super::super::super::operation::ParameterUse::In,
                cardinality: super::super::super::operation::Cardinality {
                    min: 0,
                    max: Some(1),
                },
                type_code: Some("string"),
                scope: &["type"],
                parts: &[],
            },
            super::super::super::operation::Parameter {
                name: "display",
                usage: super::super::super::operation::ParameterUse::In,
                cardinality: super::super::super::operation::Cardinality {
                    min: 0,
                    max: Some(1),
                },
                type_code: Some("string"),
                scope: &[],
                parts: &[],
            },
            super::super::super::operation::Parameter {
                name: "coding",
                usage: super::super::super::operation::ParameterUse::In,
                cardinality: super::super::super::operation::Cardinality {
                    min: 0,
                    max: Some(1),
                },
                type_code: Some("Coding"),
                scope: &[],
                parts: &[],
            },
            super::super::super::operation::Parameter {
                name: "codeableConcept",
                usage: super::super::super::operation::ParameterUse::In,
                cardinality: super::super::super::operation::Cardinality {
                    min: 0,
                    max: Some(1),
                },
                type_code: Some("CodeableConcept"),
                scope: &[],
                parts: &[],
            },
            super::super::super::operation::Parameter {
                name: "date",
                usage: super::super::super::operation::ParameterUse::In,
                cardinality: super::super::super::operation::Cardinality {
                    min: 0,
                    max: Some(1),
                },
                type_code: Some("dateTime"),
                scope: &[],
                parts: &[],
            },
            super::super::super::operation::Parameter {
                name: "abstract",
                usage: super::super::super::operation::ParameterUse::In,
                cardinality: super::super::super::operation::Cardinality {
                    min: 0,
                    max: Some(1),
                },
                type_code: Some("boolean"),
                scope: &[],
                parts: &[],
            },
            super::super::super::operation::Parameter {
                name: "displayLanguage",
                usage: super::super::super::operation::ParameterUse::In,
                cardinality: super::super::super::operation::Cardinality {
                    min: 0,
                    max: Some(1),
                },
                type_code: Some("code"),
                scope: &[],
                parts: &[],
            },
            super::super::super::operation::Parameter {
                name: "result",
                usage: super::super::super::operation::ParameterUse::Out,
                cardinality: super::super::super::operation::Cardinality {
                    min: 1,
                    max: Some(1),
                },
                type_code: Some("boolean"),
                scope: &[],
                parts: &[],
            },
            super::super::super::operation::Parameter {
                name: "message",
                usage: super::super::super::operation::ParameterUse::Out,
                cardinality: super::super::super::operation::Cardinality {
                    min: 0,
                    max: Some(1),
                },
                type_code: Some("string"),
                scope: &[],
                parts: &[],
            },
            super::super::super::operation::Parameter {
                name: "display",
                usage: super::super::super::operation::ParameterUse::Out,
                cardinality: super::super::super::operation::Cardinality {
                    min: 0,
                    max: Some(1),
                },
                type_code: Some("string"),
                scope: &[],
                parts: &[],
            },
            super::super::super::operation::Parameter {
                name: "code",
                usage: super::super::super::operation::ParameterUse::Out,
                cardinality: super::super::super::operation::Cardinality {
                    min: 0,
                    max: Some(1),
                },
                type_code: Some("code"),
                scope: &[],
                parts: &[],
            },
            super::super::super::operation::Parameter {
                name: "system",
                usage: super::super::super::operation::ParameterUse::Out,
                cardinality: super::super::super::operation::Cardinality {
                    min: 0,
                    max: Some(1),
                },
                type_code: Some("uri"),
                scope: &[],
                parts: &[],
            },
            super::super::super::operation::Parameter {
                name: "version",
                usage: super::super::super::operation::ParameterUse::Out,
                cardinality: super::super::super::operation::Cardinality {
                    min: 0,
                    max: Some(1),
                },
                type_code: Some("string"),
                scope: &[],
                parts: &[],
            },
            super::super::super::operation::Parameter {
                name: "codeableConcept",
                usage: super::super::super::operation::ParameterUse::Out,
                cardinality: super::super::super::operation::Cardinality {
                    min: 0,
                    max: Some(1),
                },
                type_code: Some("CodeableConcept"),
                scope: &[],
                parts: &[],
            },
            super::super::super::operation::Parameter {
                name: "issues",
                usage: super::super::super::operation::ParameterUse::Out,
                cardinality: super::super::super::operation::Cardinality {
                    min: 0,
                    max: Some(1),
                },
                type_code: Some("OperationOutcome"),
                scope: &[],
                parts: &[],
            },
        ],
    };
