// @generated by ferroterm-fhir-codegen from hl7.fhir.r4b.core 4.3.0. DO NOT EDIT.
// Change the emitter (tools/ferroterm-fhir-codegen) and regenerate.
//! A duration of time during which an organism (or a process) has existed

/// A duration of time during which an organism (or a process) has existed.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Age {
    /// Unique id for inter-element referencing
    ///
    /// Unique id for the element within a resource (for internal references). This
    /// may be any string value that does not contain spaces.
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the element. To make the use of extensions safe and
    /// manageable, there is a strict set of governance applied to the definition
    /// and use of extensions. Though any implementer can define an extension, there
    /// is a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// Numerical value (with implicit precision)
    ///
    /// The value of the measured amount. The value includes an implicit precision
    /// in the presentation of the value.
    pub value: Option<super::primitives::Decimal>,
    /// \< | \<= | \>= | \> - how to understand the value
    ///
    /// How the value should be understood and represented - whether the actual
    /// value is greater or less than the stated value due to measurement issues;
    /// e.g. if the comparator is "\<" , then the real value is \< stated value.
    pub comparator: Option<super::primitives::Code>,
    /// Unit representation
    ///
    /// A human-readable form of the unit.
    pub unit: Option<super::primitives::String>,
    /// System that defines coded unit form
    ///
    /// The identification of the system that provides the coded form of the unit.
    pub system: Option<super::primitives::Uri>,
    /// Coded form of the unit
    ///
    /// A computer processable form of the unit in some unit representation system.
    pub code: Option<super::primitives::Code>,
}
