// @generated by ferroterm-fhir-codegen from hl7.fhir.r4b.core 4.3.0. DO NOT EDIT.
// Change the emitter (tools/ferroterm-fhir-codegen) and regenerate.
//! Declares the existence of and describes a code system or code system supplement

/// Declares the existence of and describes a code system or code system
/// supplement
///
/// The CodeSystem resource is used to declare the existence of and describe a
/// code system or code system supplement and its key properties, and optionally
/// define a part or all of its content.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CodeSystem {
    /// Logical id of this artifact
    ///
    /// The logical id of the resource, as used in the URL for the resource. Once
    /// assigned, this value never changes.
    pub id: Option<std::string::String>,
    /// Metadata about the resource
    ///
    /// The metadata about the resource. This is content that is maintained by the
    /// infrastructure. Changes to the content might not always be associated with
    /// version changes to the resource.
    pub meta: Option<super::meta::Meta>,
    /// A set of rules under which this content was created
    ///
    /// A reference to a set of rules that were followed when the resource was
    /// constructed, and which must be understood when processing the content.
    /// Often, this is a reference to an implementation guide that defines the
    /// special rules along with other profiles etc.
    pub implicit_rules: Option<super::primitives::Uri>,
    /// Language of the resource content
    ///
    /// The base language in which the resource is written.
    pub language: Option<super::primitives::Code>,
    /// Text summary of the resource, for human interpretation
    ///
    /// A human-readable narrative that contains a summary of the resource and can
    /// be used to represent the content of the resource to a human. The narrative
    /// need not encode all the structured data, but is required to contain
    /// sufficient detail to make it "clinically safe" for a human to just read the
    /// narrative. Resource definitions may define what content should be
    /// represented in the narrative to ensure clinical safety.
    pub text: Option<super::narrative::Narrative>,
    /// Contained, inline Resources
    ///
    /// These resources do not have an independent existence apart from the resource
    /// that contains them - they cannot be identified independently, and nor can
    /// they have their own independent transaction scope.
    pub contained: Vec<super::resource::Resource>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the resource. To make the use of extensions safe and
    /// manageable, there is a strict set of governance applied to the definition
    /// and use of extensions. Though any implementer can define an extension, there
    /// is a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// Extensions that cannot be ignored
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the resource and that modifies the understanding of the
    /// element that contains it and/or the understanding of the containing
    /// element's descendants. Usually modifier elements provide negation or
    /// qualification. To make the use of extensions safe and manageable, there is a
    /// strict set of governance applied to the definition and use of extensions.
    /// Though any implementer is allowed to define an extension, there is a set of
    /// requirements that SHALL be met as part of the definition of the extension.
    /// Applications processing a resource are required to check for modifier
    /// extensions. Modifier extensions SHALL NOT change the meaning of any elements
    /// on Resource or DomainResource (including cannot change the meaning of
    /// modifierExtension itself).
    pub modifier_extension: Vec<super::extension::Extension>,
    /// Canonical identifier for this code system, represented as a URI (globally
    /// unique) (Coding.system)
    ///
    /// An absolute URI that is used to identify this code system when it is
    /// referenced in a specification, model, design or an instance; also called its
    /// canonical identifier. This SHOULD be globally unique and SHOULD be a literal
    /// address at which at which an authoritative instance of this code system is
    /// (or will be) published. This URL can be the target of a canonical reference.
    /// It SHALL remain the same when the code system is stored on different
    /// servers. This is used in \[Coding\](datatypes.html\#Coding).system.
    pub url: Option<super::primitives::Uri>,
    /// Additional identifier for the code system (business identifier)
    ///
    /// A formal identifier that is used to identify this code system when it is
    /// represented in other formats, or referenced in a specification, model,
    /// design or an instance.
    pub identifier: Vec<super::identifier::Identifier>,
    /// Business version of the code system (Coding.version)
    ///
    /// The identifier that is used to identify this version of the code system when
    /// it is referenced in a specification, model, design or instance. This is an
    /// arbitrary value managed by the code system author and is not expected to be
    /// globally unique. For example, it might be a timestamp (e.g. yyyymmdd) if a
    /// managed version is not available. There is also no expectation that versions
    /// can be placed in a lexicographical sequence. This is used in
    /// \[Coding\](datatypes.html\#Coding).version.
    pub version: Option<super::primitives::String>,
    /// Name for this code system (computer friendly)
    ///
    /// A natural language name identifying the code system. This name should be
    /// usable as an identifier for the module by machine processing applications
    /// such as code generation.
    pub name: Option<super::primitives::String>,
    /// Name for this code system (human friendly)
    ///
    /// A short, descriptive, user-friendly title for the code system.
    pub title: Option<super::primitives::String>,
    /// draft | active | retired | unknown
    ///
    /// The date (and optionally time) when the code system resource was created or
    /// revised.
    pub status: super::primitives::Code,
    /// For testing purposes, not real usage
    ///
    /// A Boolean value to indicate that this code system is authored for testing
    /// purposes (or education/evaluation/marketing) and is not intended to be used
    /// for genuine usage.
    pub experimental: Option<super::primitives::Boolean>,
    /// Date last changed
    ///
    /// The date (and optionally time) when the code system was published. The date
    /// must change when the business version changes and it must change if the
    /// status code changes. In addition, it should change when the substantive
    /// content of the code system changes.
    pub date: Option<super::primitives::DateTime>,
    /// Name of the publisher (organization or individual)
    ///
    /// The name of the organization or individual that published the code system.
    pub publisher: Option<super::primitives::String>,
    /// Contact details for the publisher
    ///
    /// Contact details to assist a user in finding and communicating with the
    /// publisher.
    pub contact: Vec<super::contact_detail::ContactDetail>,
    /// Natural language description of the code system
    ///
    /// A free text natural language description of the code system from a
    /// consumer's perspective.
    pub description: Option<super::primitives::Markdown>,
    /// The context that the content is intended to support
    ///
    /// The content was developed with a focus and intent of supporting the contexts
    /// that are listed. These contexts may be general categories (gender, age, ...)
    /// or may be references to specific programs (insurance plans, studies, ...)
    /// and may be used to assist with indexing and searching for appropriate code
    /// system instances.
    pub use_context: Vec<super::usage_context::UsageContext>,
    /// Intended jurisdiction for code system (if applicable)
    ///
    /// A legal or geographic region in which the code system is intended to be
    /// used.
    pub jurisdiction: Vec<super::codeable_concept::CodeableConcept>,
    /// Why this code system is defined
    ///
    /// Explanation of why this code system is needed and why it has been designed
    /// as it has.
    pub purpose: Option<super::primitives::Markdown>,
    /// Use and/or publishing restrictions
    ///
    /// A copyright statement relating to the code system and/or its contents.
    /// Copyright statements are generally legal restrictions on the use and
    /// publishing of the code system.
    pub copyright: Option<super::primitives::Markdown>,
    /// If code comparison is case sensitive
    ///
    /// If code comparison is case sensitive when codes within this system are
    /// compared to each other.
    pub case_sensitive: Option<super::primitives::Boolean>,
    /// Canonical reference to the value set with entire code system
    ///
    /// Canonical reference to the value set that contains the entire code system.
    pub value_set: Option<super::primitives::Canonical>,
    /// grouped-by | is-a | part-of | classified-with
    ///
    /// The meaning of the hierarchy of concepts as represented in this resource.
    pub hierarchy_meaning: Option<super::primitives::Code>,
    /// If code system defines a compositional grammar
    ///
    /// The code system defines a compositional (post-coordination) grammar.
    pub compositional: Option<super::primitives::Boolean>,
    /// If definitions are not stable
    ///
    /// This flag is used to signify that the code system does not commit to concept
    /// permanence across versions. If true, a version must be specified when
    /// referencing this code system.
    pub version_needed: Option<super::primitives::Boolean>,
    /// not-present | example | fragment | complete | supplement
    ///
    /// The extent of the content of the code system (the concepts and codes it
    /// defines) are represented in this resource instance.
    pub content: super::primitives::Code,
    /// Canonical URL of Code System this adds designations and properties to
    ///
    /// The canonical URL of the code system that this code system supplement is
    /// adding designations and properties to.
    pub supplements: Option<super::primitives::Canonical>,
    /// Total concepts in the code system
    ///
    /// The total number of concepts defined by the code system. Where the code
    /// system has a compositional grammar, the basis of this count is defined by
    /// the system steward.
    pub count: Option<super::primitives::UnsignedInt>,
    /// Filter that can be used in a value set
    ///
    /// A filter that can be used in a value set compose statement when selecting
    /// concepts using a filter.
    pub filter: Vec<CodeSystemFilter>,
    /// Additional information supplied about each concept
    ///
    /// A property defines an additional slot through which additional information
    /// can be provided about a concept.
    pub property: Vec<CodeSystemProperty>,
    /// Concepts in the code system
    ///
    /// Concepts that are in the code system. The concept definitions are inherently
    /// hierarchical, but the definitions must be consulted to determine what the
    /// meanings of the hierarchical relationships are.
    pub concept: Vec<CodeSystemConcept>,
}

/// Concepts in the code system
///
/// Concepts that are in the code system. The concept definitions are inherently
/// hierarchical, but the definitions must be consulted to determine what the
/// meanings of the hierarchical relationships are.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CodeSystemConcept {
    /// Unique id for inter-element referencing
    ///
    /// Unique id for the element within a resource (for internal references). This
    /// may be any string value that does not contain spaces.
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the element. To make the use of extensions safe and
    /// manageable, there is a strict set of governance applied to the definition
    /// and use of extensions. Though any implementer can define an extension, there
    /// is a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// Extensions that cannot be ignored even if unrecognized
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the element and that modifies the understanding of the
    /// element in which it is contained and/or the understanding of the containing
    /// element's descendants. Usually modifier elements provide negation or
    /// qualification. To make the use of extensions safe and manageable, there is a
    /// strict set of governance applied to the definition and use of extensions.
    /// Though any implementer can define an extension, there is a set of
    /// requirements that SHALL be met as part of the definition of the extension.
    /// Applications processing a resource are required to check for modifier
    /// extensions. Modifier extensions SHALL NOT change the meaning of any elements
    /// on Resource or DomainResource (including cannot change the meaning of
    /// modifierExtension itself).
    pub modifier_extension: Vec<super::extension::Extension>,
    /// Code that identifies concept
    ///
    /// A code - a text symbol - that uniquely identifies the concept within the
    /// code system.
    pub code: super::primitives::Code,
    /// Text to display to the user
    ///
    /// A human readable string that is the recommended default way to present this
    /// concept to a user.
    pub display: Option<super::primitives::String>,
    /// Formal definition
    ///
    /// The formal definition of the concept. The code system resource does not make
    /// formal definitions required, because of the prevalence of legacy systems.
    /// However, they are highly recommended, as without them there is no formal
    /// meaning associated with the concept.
    pub definition: Option<super::primitives::String>,
    /// Additional representations for the concept
    ///
    /// Additional representations for the concept - other languages, aliases,
    /// specialized purposes, used for particular purposes, etc.
    pub designation: Vec<CodeSystemConceptDesignation>,
    /// Property value for the concept
    ///
    /// A property value for this concept.
    pub property: Vec<CodeSystemConceptProperty>,
    /// Child Concepts (is-a/contains/categorizes)
    ///
    /// Defines children of a concept to produce a hierarchy of concepts. The nature
    /// of the relationships is variable (is-a/contains/categorizes) - see
    /// hierarchyMeaning.
    pub concept: Vec<CodeSystemConcept>,
}

/// Additional representations for the concept
///
/// Additional representations for the concept - other languages, aliases,
/// specialized purposes, used for particular purposes, etc.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CodeSystemConceptDesignation {
    /// Unique id for inter-element referencing
    ///
    /// Unique id for the element within a resource (for internal references). This
    /// may be any string value that does not contain spaces.
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the element. To make the use of extensions safe and
    /// manageable, there is a strict set of governance applied to the definition
    /// and use of extensions. Though any implementer can define an extension, there
    /// is a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// Extensions that cannot be ignored even if unrecognized
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the element and that modifies the understanding of the
    /// element in which it is contained and/or the understanding of the containing
    /// element's descendants. Usually modifier elements provide negation or
    /// qualification. To make the use of extensions safe and manageable, there is a
    /// strict set of governance applied to the definition and use of extensions.
    /// Though any implementer can define an extension, there is a set of
    /// requirements that SHALL be met as part of the definition of the extension.
    /// Applications processing a resource are required to check for modifier
    /// extensions. Modifier extensions SHALL NOT change the meaning of any elements
    /// on Resource or DomainResource (including cannot change the meaning of
    /// modifierExtension itself).
    pub modifier_extension: Vec<super::extension::Extension>,
    /// Human language of the designation
    ///
    /// The language this designation is defined for.
    pub language: Option<super::primitives::Code>,
    /// Details how this designation would be used
    ///
    /// A code that details how this designation would be used.
    pub r#use: Option<super::coding::Coding>,
    /// The text value for this designation.
    pub value: super::primitives::String,
}

/// Property value for the concept
///
/// A property value for this concept.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CodeSystemConceptProperty {
    /// Unique id for inter-element referencing
    ///
    /// Unique id for the element within a resource (for internal references). This
    /// may be any string value that does not contain spaces.
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the element. To make the use of extensions safe and
    /// manageable, there is a strict set of governance applied to the definition
    /// and use of extensions. Though any implementer can define an extension, there
    /// is a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// Extensions that cannot be ignored even if unrecognized
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the element and that modifies the understanding of the
    /// element in which it is contained and/or the understanding of the containing
    /// element's descendants. Usually modifier elements provide negation or
    /// qualification. To make the use of extensions safe and manageable, there is a
    /// strict set of governance applied to the definition and use of extensions.
    /// Though any implementer can define an extension, there is a set of
    /// requirements that SHALL be met as part of the definition of the extension.
    /// Applications processing a resource are required to check for modifier
    /// extensions. Modifier extensions SHALL NOT change the meaning of any elements
    /// on Resource or DomainResource (including cannot change the meaning of
    /// modifierExtension itself).
    pub modifier_extension: Vec<super::extension::Extension>,
    /// Reference to CodeSystem.property.code
    ///
    /// A code that is a reference to CodeSystem.property.code.
    pub code: super::primitives::Code,
    /// Value of the property for this concept
    ///
    /// The value of this property.
    pub value: CodeSystemConceptPropertyValue,
}

/// The \`value\[x\]\` choice of \`CodeSystemConceptProperty\`.
///
/// The value of this property.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CodeSystemConceptPropertyValue {
    /// The `code` form.
    Code(super::primitives::Code),
    /// The `Coding` form.
    Coding(super::coding::Coding),
    /// The `string` form.
    String(super::primitives::String),
    /// The `integer` form.
    Integer(super::primitives::Integer),
    /// The `boolean` form.
    Boolean(super::primitives::Boolean),
    /// The `dateTime` form.
    DateTime(super::primitives::DateTime),
    /// The `decimal` form.
    Decimal(super::primitives::Decimal),
}

/// Filter that can be used in a value set
///
/// A filter that can be used in a value set compose statement when selecting
/// concepts using a filter.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CodeSystemFilter {
    /// Unique id for inter-element referencing
    ///
    /// Unique id for the element within a resource (for internal references). This
    /// may be any string value that does not contain spaces.
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the element. To make the use of extensions safe and
    /// manageable, there is a strict set of governance applied to the definition
    /// and use of extensions. Though any implementer can define an extension, there
    /// is a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// Extensions that cannot be ignored even if unrecognized
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the element and that modifies the understanding of the
    /// element in which it is contained and/or the understanding of the containing
    /// element's descendants. Usually modifier elements provide negation or
    /// qualification. To make the use of extensions safe and manageable, there is a
    /// strict set of governance applied to the definition and use of extensions.
    /// Though any implementer can define an extension, there is a set of
    /// requirements that SHALL be met as part of the definition of the extension.
    /// Applications processing a resource are required to check for modifier
    /// extensions. Modifier extensions SHALL NOT change the meaning of any elements
    /// on Resource or DomainResource (including cannot change the meaning of
    /// modifierExtension itself).
    pub modifier_extension: Vec<super::extension::Extension>,
    /// Code that identifies the filter
    ///
    /// The code that identifies this filter when it is used as a filter in
    /// \[ValueSet\](valueset.html\#).compose.include.filter.
    pub code: super::primitives::Code,
    /// How or why the filter is used
    ///
    /// A description of how or why the filter is used.
    pub description: Option<super::primitives::String>,
    /// = | is-a | descendent-of | is-not-a | regex | in | not-in | generalizes |
    /// exists
    ///
    /// A list of operators that can be used with the filter.
    pub operator: Vec<super::primitives::Code>,
    /// What to use for the value
    ///
    /// A description of what the value for the filter should be.
    pub value: super::primitives::String,
}

/// Additional information supplied about each concept
///
/// A property defines an additional slot through which additional information
/// can be provided about a concept.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CodeSystemProperty {
    /// Unique id for inter-element referencing
    ///
    /// Unique id for the element within a resource (for internal references). This
    /// may be any string value that does not contain spaces.
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the element. To make the use of extensions safe and
    /// manageable, there is a strict set of governance applied to the definition
    /// and use of extensions. Though any implementer can define an extension, there
    /// is a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// Extensions that cannot be ignored even if unrecognized
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the element and that modifies the understanding of the
    /// element in which it is contained and/or the understanding of the containing
    /// element's descendants. Usually modifier elements provide negation or
    /// qualification. To make the use of extensions safe and manageable, there is a
    /// strict set of governance applied to the definition and use of extensions.
    /// Though any implementer can define an extension, there is a set of
    /// requirements that SHALL be met as part of the definition of the extension.
    /// Applications processing a resource are required to check for modifier
    /// extensions. Modifier extensions SHALL NOT change the meaning of any elements
    /// on Resource or DomainResource (including cannot change the meaning of
    /// modifierExtension itself).
    pub modifier_extension: Vec<super::extension::Extension>,
    /// Identifies the property on the concepts, and when referred to in operations
    ///
    /// A code that is used to identify the property. The code is used internally
    /// (in CodeSystem.concept.property.code) and also externally, such as in
    /// property filters.
    pub code: super::primitives::Code,
    /// Formal identifier for the property
    ///
    /// Reference to the formal meaning of the property. One possible source of
    /// meaning is the \[Concept Properties\](codesystem-concept-properties.html)
    /// code system.
    pub uri: Option<super::primitives::Uri>,
    /// Why the property is defined, and/or what it conveys
    ///
    /// A description of the property- why it is defined, and how its value might be
    /// used.
    pub description: Option<super::primitives::String>,
    /// code | Coding | string | integer | boolean | dateTime | decimal
    ///
    /// The type of the property value. Properties of type "code" contain a code
    /// defined by the code system (e.g. a reference to another defined concept).
    pub r#type: super::primitives::Code,
}
