// @generated by ferroterm-fhir-codegen from hl7.fhir.r4b.core 4.3.0. DO NOT EDIT.
// Change the emitter (tools/ferroterm-fhir-codegen) and regenerate.
//! Definition of a parameter to a module

/// Definition of a parameter to a module
///
/// The parameters to the module. This collection specifies both the input and
/// output parameters. Input parameters are provided by the caller as part of
/// the $evaluate operation. Output parameters are included in the
/// GuidanceResponse.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParameterDefinition {
    /// Unique id for inter-element referencing
    ///
    /// Unique id for the element within a resource (for internal references). This
    /// may be any string value that does not contain spaces.
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the element. To make the use of extensions safe and
    /// manageable, there is a strict set of governance applied to the definition
    /// and use of extensions. Though any implementer can define an extension, there
    /// is a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// Name used to access the parameter value
    ///
    /// The name of the parameter used to allow access to the value of the parameter
    /// in evaluation contexts.
    pub name: Option<super::primitives::Code>,
    /// in | out
    ///
    /// Whether the parameter is input or output for the module.
    pub r#use: super::primitives::Code,
    /// Minimum cardinality
    ///
    /// The minimum number of times this parameter SHALL appear in the request or
    /// response.
    pub min: Option<super::primitives::Integer>,
    /// Maximum cardinality (a number of \*)
    ///
    /// The maximum number of times this element is permitted to appear in the
    /// request or response.
    pub max: Option<super::primitives::String>,
    /// A brief description of the parameter
    ///
    /// A brief discussion of what the parameter is for and how it is used by the
    /// module.
    pub documentation: Option<super::primitives::String>,
    /// What type of value
    ///
    /// The type of the parameter.
    pub r#type: super::primitives::Code,
    /// What profile the value is expected to be
    ///
    /// If specified, this indicates a profile that the input data must conform to,
    /// or that the output data will conform to.
    pub profile: Option<super::primitives::Canonical>,
}
