// @generated by ferroterm-fhir-codegen from hl7.fhir.r5.core 5.0.0. DO NOT EDIT.
// Change the emitter (tools/ferroterm-fhir-codegen) and regenerate.
//! Content in a format defined elsewhere

/// Content in a format defined elsewhere
///
/// For referring to data content defined in other formats.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Attachment {
    /// Unique id for inter-element referencing
    ///
    /// Unique id for the element within a resource (for internal references). This
    /// may be any string value that does not contain spaces.
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the element. To make the use of extensions safe and
    /// managable, there is a strict set of governance applied to the definition and
    /// use of extensions. Though any implementer can define an extension, there is
    /// a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// Mime type of the content, with charset etc.
    ///
    /// Identifies the type of the data in the attachment and allows a method to be
    /// chosen to interpret or render the data. Includes mime type parameters such
    /// as charset where appropriate.
    pub content_type: Option<super::primitives::Code>,
    /// Human language of the content (BCP-47)
    ///
    /// The human language of the content. The value can be any valid value
    /// according to BCP 47.
    pub language: Option<super::primitives::Code>,
    /// Data inline, base64ed
    ///
    /// The actual data of the attachment - a sequence of bytes, base64 encoded.
    pub data: Option<super::primitives::Base64Binary>,
    /// Uri where the data can be found
    ///
    /// A location where the data can be accessed.
    pub url: Option<super::primitives::Url>,
    /// Number of bytes of content (if url provided)
    ///
    /// The number of bytes of data that make up this attachment (before base64
    /// encoding, if that is done).
    pub size: Option<super::primitives::Integer64>,
    /// Hash of the data (sha-1, base64ed)
    ///
    /// The calculated hash of the data using SHA-1. Represented using base64.
    pub hash: Option<super::primitives::Base64Binary>,
    /// Label to display in place of the data
    ///
    /// A label or set of text to display in place of the data.
    pub title: Option<super::primitives::String>,
    /// Date attachment was first created
    ///
    /// The date that the attachment was first created.
    pub creation: Option<super::primitives::DateTime>,
    /// Height of the image in pixels (photo/video).
    pub height: Option<super::primitives::PositiveInt>,
    /// Width of the image in pixels (photo/video).
    pub width: Option<super::primitives::PositiveInt>,
    /// Number of frames if \> 1 (photo)
    ///
    /// The number of frames in a photo. This is used with a multi-page fax, or an
    /// imaging acquisition context that takes multiple slices in a single image, or
    /// an animated gif. If there is more than one frame, this SHALL have a value in
    /// order to alert interface software that a multi-frame capable rendering
    /// widget is required.
    pub frames: Option<super::primitives::PositiveInt>,
    /// Length in seconds (audio / video)
    ///
    /// The duration of the recording in seconds - for audio and video.
    pub duration: Option<super::primitives::Decimal>,
    /// Number of printed pages
    ///
    /// The number of pages when printed.
    pub pages: Option<super::primitives::PositiveInt>,
}
