// @generated by ferroterm-fhir-codegen from hl7.fhir.r5.core 5.0.0. DO NOT EDIT.
// Change the emitter (tools/ferroterm-fhir-codegen) and regenerate.
//! Availability data for an {item}

/// Availability data for an {item}.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Availability {
    /// Unique id for inter-element referencing
    ///
    /// Unique id for the element within a resource (for internal references). This
    /// may be any string value that does not contain spaces.
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the element. To make the use of extensions safe and
    /// managable, there is a strict set of governance applied to the definition and
    /// use of extensions. Though any implementer can define an extension, there is
    /// a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// Times the {item} is available.
    pub available_time: Vec<AvailabilityAvailableTime>,
    /// Not available during this time due to provided reason.
    pub not_available_time: Vec<AvailabilityNotAvailableTime>,
}

/// Times the {item} is available.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AvailabilityAvailableTime {
    /// Unique id for inter-element referencing
    ///
    /// Unique id for the element within a resource (for internal references). This
    /// may be any string value that does not contain spaces.
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the element. To make the use of extensions safe and
    /// managable, there is a strict set of governance applied to the definition and
    /// use of extensions. Though any implementer can define an extension, there is
    /// a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// mon | tue | wed | thu | fri | sat | sun.
    pub days_of_week: Vec<super::primitives::Code>,
    /// Always available? i.e. 24 hour service.
    pub all_day: Option<super::primitives::Boolean>,
    /// Opening time of day (ignored if allDay = true).
    pub available_start_time: Option<super::primitives::Time>,
    /// Closing time of day (ignored if allDay = true).
    pub available_end_time: Option<super::primitives::Time>,
}

/// Not available during this time due to provided reason.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AvailabilityNotAvailableTime {
    /// Unique id for inter-element referencing
    ///
    /// Unique id for the element within a resource (for internal references). This
    /// may be any string value that does not contain spaces.
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the element. To make the use of extensions safe and
    /// managable, there is a strict set of governance applied to the definition and
    /// use of extensions. Though any implementer can define an extension, there is
    /// a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// Reason presented to the user explaining why time not available.
    pub description: Option<super::primitives::String>,
    /// Service not available during this period.
    pub during: Option<super::period::Period>,
}
