// @generated by ferroterm-fhir-codegen from hl7.fhir.r5.core 5.0.0. DO NOT EDIT.
// Change the emitter (tools/ferroterm-fhir-codegen) and regenerate.
//! An expression that can be used to generate a value

/// An expression that can be used to generate a value
///
/// A expression that is evaluated in a specified context and returns a value.
/// The context of use of the expression must specify the context in which the
/// expression is evaluated, and how the result of the expression is used.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Expression {
    /// Unique id for inter-element referencing
    ///
    /// Unique id for the element within a resource (for internal references). This
    /// may be any string value that does not contain spaces.
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the element. To make the use of extensions safe and
    /// managable, there is a strict set of governance applied to the definition and
    /// use of extensions. Though any implementer can define an extension, there is
    /// a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// Natural language description of the condition
    ///
    /// A brief, natural language description of the condition that effectively
    /// communicates the intended semantics.
    pub description: Option<super::primitives::String>,
    /// Short name assigned to expression for reuse
    ///
    /// A short name assigned to the expression to allow for multiple reuse of the
    /// expression in the context where it is defined.
    pub name: Option<super::primitives::Code>,
    /// text/cql | text/fhirpath | application/x-fhir-query | etc.
    ///
    /// The media type of the language for the expression.
    pub language: Option<super::primitives::Code>,
    /// Expression in specified language
    ///
    /// An expression in the specified language that returns a value.
    pub expression: Option<super::primitives::String>,
    /// Where the expression is found
    ///
    /// A URI that defines where the expression is found.
    pub reference: Option<super::primitives::Uri>,
}
