// @generated by ferroterm-fhir-codegen from hl7.fhir.r5.core 5.0.0. DO NOT EDIT.
// Change the emitter (tools/ferroterm-fhir-codegen) and regenerate.
//! Information about the success/failure of an action

/// Information about the success/failure of an action
///
/// A collection of error, warning, or information messages that result from a
/// system action.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct OperationOutcome {
    /// Logical id of this artifact
    ///
    /// The logical id of the resource, as used in the URL for the resource. Once
    /// assigned, this value never changes.
    pub id: Option<std::string::String>,
    /// Metadata about the resource
    ///
    /// The metadata about the resource. This is content that is maintained by the
    /// infrastructure. Changes to the content might not always be associated with
    /// version changes to the resource.
    pub meta: Option<super::meta::Meta>,
    /// A set of rules under which this content was created
    ///
    /// A reference to a set of rules that were followed when the resource was
    /// constructed, and which must be understood when processing the content.
    /// Often, this is a reference to an implementation guide that defines the
    /// special rules along with other profiles etc.
    pub implicit_rules: Option<super::primitives::Uri>,
    /// Language of the resource content
    ///
    /// The base language in which the resource is written.
    pub language: Option<super::primitives::Code>,
    /// Text summary of the resource, for human interpretation
    ///
    /// A human-readable narrative that contains a summary of the resource and can
    /// be used to represent the content of the resource to a human. The narrative
    /// need not encode all the structured data, but is required to contain
    /// sufficient detail to make it "clinically safe" for a human to just read the
    /// narrative. Resource definitions may define what content should be
    /// represented in the narrative to ensure clinical safety.
    pub text: Option<super::narrative::Narrative>,
    /// Contained, inline Resources
    ///
    /// These resources do not have an independent existence apart from the resource
    /// that contains them - they cannot be identified independently, nor can they
    /// have their own independent transaction scope. This is allowed to be a
    /// Parameters resource if and only if it is referenced by a resource that
    /// provides context/meaning.
    pub contained: Vec<super::resource::Resource>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the resource. To make the use of extensions safe and
    /// managable, there is a strict set of governance applied to the definition and
    /// use of extensions. Though any implementer can define an extension, there is
    /// a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// Extensions that cannot be ignored
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the resource and that modifies the understanding of the
    /// element that contains it and/or the understanding of the containing
    /// element's descendants. Usually modifier elements provide negation or
    /// qualification. To make the use of extensions safe and managable, there is a
    /// strict set of governance applied to the definition and use of extensions.
    /// Though any implementer is allowed to define an extension, there is a set of
    /// requirements that SHALL be met as part of the definition of the extension.
    /// Applications processing a resource are required to check for modifier
    /// extensions. Modifier extensions SHALL NOT change the meaning of any elements
    /// on Resource or DomainResource (including cannot change the meaning of
    /// modifierExtension itself).
    pub modifier_extension: Vec<super::extension::Extension>,
    /// A single issue associated with the action
    ///
    /// An error, warning, or information message that results from a system action.
    pub issue: Vec<OperationOutcomeIssue>,
}

impl super::super::codec::Json for OperationOutcome {
    fn to_json(&self) -> Result<super::super::codec::Object, super::super::codec::EncodeError> {
        let mut object = super::super::codec::Object::new();
        object.insert(
            std::string::String::from("resourceType"),
            serde_json::Value::String(std::string::String::from("OperationOutcome")),
        );
        if let Some(v) = &self.id {
            object.insert(
                std::string::String::from("id"),
                serde_json::Value::String(v.clone()),
            );
        }
        if let Some(item) = &self.meta {
            object.insert(
                std::string::String::from("meta"),
                serde_json::Value::Object(super::super::codec::Json::to_json(item)?),
            );
        }
        if let Some(item) = &self.implicit_rules {
            if let Some(v) = super::super::codec::Primitive::value_json(item)? {
                object.insert(std::string::String::from("implicitRules"), v);
            }
            if let Some(e) = super::super::codec::Primitive::element_json(item)? {
                object.insert(std::string::String::from("_implicitRules"), e);
            }
        }
        if let Some(item) = &self.language {
            if let Some(v) = super::super::codec::Primitive::value_json(item)? {
                object.insert(std::string::String::from("language"), v);
            }
            if let Some(e) = super::super::codec::Primitive::element_json(item)? {
                object.insert(std::string::String::from("_language"), e);
            }
        }
        if let Some(item) = &self.text {
            object.insert(
                std::string::String::from("text"),
                serde_json::Value::Object(super::super::codec::Json::to_json(item)?),
            );
        }
        if !self.contained.is_empty() {
            let mut items = Vec::with_capacity(self.contained.len());
            for item in &self.contained {
                items.push(serde_json::Value::Object(
                    super::super::codec::Json::to_json(item)?,
                ));
            }
            object.insert(
                std::string::String::from("contained"),
                serde_json::Value::Array(items),
            );
        }
        if !self.extension.is_empty() {
            let mut items = Vec::with_capacity(self.extension.len());
            for item in &self.extension {
                items.push(serde_json::Value::Object(
                    super::super::codec::Json::to_json(item)?,
                ));
            }
            object.insert(
                std::string::String::from("extension"),
                serde_json::Value::Array(items),
            );
        }
        if !self.modifier_extension.is_empty() {
            let mut items = Vec::with_capacity(self.modifier_extension.len());
            for item in &self.modifier_extension {
                items.push(serde_json::Value::Object(
                    super::super::codec::Json::to_json(item)?,
                ));
            }
            object.insert(
                std::string::String::from("modifierExtension"),
                serde_json::Value::Array(items),
            );
        }
        if !self.issue.is_empty() {
            let mut items = Vec::with_capacity(self.issue.len());
            for item in &self.issue {
                items.push(serde_json::Value::Object(
                    super::super::codec::Json::to_json(item)?,
                ));
            }
            object.insert(
                std::string::String::from("issue"),
                serde_json::Value::Array(items),
            );
        }
        Ok(object)
    }

    fn from_json(
        object: &super::super::codec::Object,
        path: &mut super::super::codec::Path,
    ) -> Result<Self, super::super::codec::DecodeError> {
        let mut raw_id: Option<&serde_json::Value> = None;
        let mut raw_meta: Option<&serde_json::Value> = None;
        let mut raw_implicit_rules: Option<&serde_json::Value> = None;
        let mut raw_implicit_rules_element: Option<&serde_json::Value> = None;
        let mut raw_language: Option<&serde_json::Value> = None;
        let mut raw_language_element: Option<&serde_json::Value> = None;
        let mut raw_text: Option<&serde_json::Value> = None;
        let mut raw_contained: Option<&serde_json::Value> = None;
        let mut raw_extension: Option<&serde_json::Value> = None;
        let mut raw_modifier_extension: Option<&serde_json::Value> = None;
        let mut raw_issue: Option<&serde_json::Value> = None;
        for (key, value) in object {
            match key.as_str() {
                "resourceType" => {
                    if value.as_str() != Some("OperationOutcome") {
                        return Err(path.error(super::super::codec::DecodeErrorKind::ResourceType));
                    }
                }
                "id" => raw_id = Some(value),
                "meta" => raw_meta = Some(value),
                "implicitRules" => raw_implicit_rules = Some(value),
                "_implicitRules" => raw_implicit_rules_element = Some(value),
                "language" => raw_language = Some(value),
                "_language" => raw_language_element = Some(value),
                "text" => raw_text = Some(value),
                "contained" => raw_contained = Some(value),
                "extension" => raw_extension = Some(value),
                "modifierExtension" => raw_modifier_extension = Some(value),
                "issue" => raw_issue = Some(value),
                other => {
                    return path.with(other, |path| {
                        Err(path.error(super::super::codec::DecodeErrorKind::UnknownProperty))
                    });
                }
            }
        }
        let field_id = raw_id
            .map(|value| {
                path.with("id", |path| {
                    let value = super::super::codec::expect_single(value, path)?;
                    super::super::codec::expect_string(value, path)
                })
            })
            .transpose()?;
        let field_meta = raw_meta
            .map(|value| {
                path.with("meta", |path| {
                    super::super::codec::Json::from_json(
                        super::super::codec::expect_object(
                            super::super::codec::expect_single(value, path)?,
                            path,
                        )?,
                        path,
                    )
                })
            })
            .transpose()?;
        let field_implicit_rules = match (raw_implicit_rules, raw_implicit_rules_element) {
            (None, None) => None,
            (value, element) => Some(path.with("implicitRules", |path| {
                super::super::codec::Primitive::from_json_parts(value, element, path)
            })?),
        };
        let field_language = match (raw_language, raw_language_element) {
            (None, None) => None,
            (value, element) => Some(path.with("language", |path| {
                super::super::codec::Primitive::from_json_parts(value, element, path)
            })?),
        };
        let field_text = raw_text
            .map(|value| {
                path.with("text", |path| {
                    super::super::codec::Json::from_json(
                        super::super::codec::expect_object(
                            super::super::codec::expect_single(value, path)?,
                            path,
                        )?,
                        path,
                    )
                })
            })
            .transpose()?;
        let mut field_contained = Vec::new();
        if let Some(raw) = raw_contained {
            for (index, value) in super::super::codec::expect_array(raw, path)?
                .iter()
                .enumerate()
            {
                field_contained.push(path.with_index("contained", index, |path| {
                    super::super::codec::Json::from_json(
                        super::super::codec::expect_object(value, path)?,
                        path,
                    )
                })?);
            }
        }
        let mut field_extension = Vec::new();
        if let Some(raw) = raw_extension {
            for (index, value) in super::super::codec::expect_array(raw, path)?
                .iter()
                .enumerate()
            {
                field_extension.push(path.with_index("extension", index, |path| {
                    super::super::codec::Json::from_json(
                        super::super::codec::expect_object(value, path)?,
                        path,
                    )
                })?);
            }
        }
        let mut field_modifier_extension = Vec::new();
        if let Some(raw) = raw_modifier_extension {
            for (index, value) in super::super::codec::expect_array(raw, path)?
                .iter()
                .enumerate()
            {
                field_modifier_extension.push(path.with_index(
                    "modifierExtension",
                    index,
                    |path| {
                        super::super::codec::Json::from_json(
                            super::super::codec::expect_object(value, path)?,
                            path,
                        )
                    },
                )?);
            }
        }
        let mut field_issue = Vec::new();
        if let Some(raw) = raw_issue {
            for (index, value) in super::super::codec::expect_array(raw, path)?
                .iter()
                .enumerate()
            {
                field_issue.push(path.with_index("issue", index, |path| {
                    super::super::codec::Json::from_json(
                        super::super::codec::expect_object(value, path)?,
                        path,
                    )
                })?);
            }
        }
        Ok(Self {
            id: field_id,
            meta: field_meta,
            implicit_rules: field_implicit_rules,
            language: field_language,
            text: field_text,
            contained: field_contained,
            extension: field_extension,
            modifier_extension: field_modifier_extension,
            issue: field_issue,
        })
    }
}

impl serde::Serialize for OperationOutcome {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        super::super::codec::Json::to_json(self)
            .map_err(serde::ser::Error::custom)?
            .serialize(serializer)
    }
}

impl<'de> serde::Deserialize<'de> for OperationOutcome {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = serde_json::Value::deserialize(deserializer)?;
        let mut path = super::super::codec::Path::root("OperationOutcome");
        let object =
            super::super::codec::expect_object(&value, &path).map_err(serde::de::Error::custom)?;
        super::super::codec::Json::from_json(object, &mut path).map_err(serde::de::Error::custom)
    }
}

/// A single issue associated with the action
///
/// An error, warning, or information message that results from a system action.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct OperationOutcomeIssue {
    /// Unique id for inter-element referencing
    ///
    /// Unique id for the element within a resource (for internal references). This
    /// may be any string value that does not contain spaces.
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the element. To make the use of extensions safe and
    /// managable, there is a strict set of governance applied to the definition and
    /// use of extensions. Though any implementer can define an extension, there is
    /// a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// Extensions that cannot be ignored even if unrecognized
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the element and that modifies the understanding of the
    /// element in which it is contained and/or the understanding of the containing
    /// element's descendants. Usually modifier elements provide negation or
    /// qualification. To make the use of extensions safe and managable, there is a
    /// strict set of governance applied to the definition and use of extensions.
    /// Though any implementer can define an extension, there is a set of
    /// requirements that SHALL be met as part of the definition of the extension.
    /// Applications processing a resource are required to check for modifier
    /// extensions. Modifier extensions SHALL NOT change the meaning of any elements
    /// on Resource or DomainResource (including cannot change the meaning of
    /// modifierExtension itself).
    pub modifier_extension: Vec<super::extension::Extension>,
    /// fatal | error | warning | information | success
    ///
    /// Indicates whether the issue indicates a variation from successful
    /// processing.
    pub severity: super::primitives::Code,
    /// Error or warning code
    ///
    /// Describes the type of the issue. The system that creates an OperationOutcome
    /// SHALL choose the most applicable code from the IssueType value set, and may
    /// additional provide its own code for the error in the details element.
    pub code: super::primitives::Code,
    /// Additional details about the error
    ///
    /// Additional details about the error. This may be a text description of the
    /// error or a system code that identifies the error.
    pub details: Option<super::codeable_concept::CodeableConcept>,
    /// Additional diagnostic information about the issue.
    pub diagnostics: Option<super::primitives::String>,
    /// Deprecated: Path of element(s) related to issue
    ///
    /// This element is deprecated because it is XML specific. It is replaced by
    /// issue.expression, which is format independent, and simpler to parse. For
    /// resource issues, this will be a simple XPath limited to element names,
    /// repetition indicators and the default child accessor that identifies one of
    /// the elements in the resource that caused this issue to be raised. For HTTP
    /// errors, will be "http." + the parameter name.
    pub location: Vec<super::primitives::String>,
    /// FHIRPath of element(s) related to issue
    ///
    /// A \[simple subset of FHIRPath\](fhirpath.html\#simple) limited to element
    /// names, repetition indicators and the default child accessor that identifies
    /// one of the elements in the resource that caused this issue to be raised.
    pub expression: Vec<super::primitives::String>,
}

impl super::super::codec::Json for OperationOutcomeIssue {
    fn to_json(&self) -> Result<super::super::codec::Object, super::super::codec::EncodeError> {
        let mut object = super::super::codec::Object::new();
        if let Some(v) = &self.id {
            object.insert(
                std::string::String::from("id"),
                serde_json::Value::String(v.clone()),
            );
        }
        if !self.extension.is_empty() {
            let mut items = Vec::with_capacity(self.extension.len());
            for item in &self.extension {
                items.push(serde_json::Value::Object(
                    super::super::codec::Json::to_json(item)?,
                ));
            }
            object.insert(
                std::string::String::from("extension"),
                serde_json::Value::Array(items),
            );
        }
        if !self.modifier_extension.is_empty() {
            let mut items = Vec::with_capacity(self.modifier_extension.len());
            for item in &self.modifier_extension {
                items.push(serde_json::Value::Object(
                    super::super::codec::Json::to_json(item)?,
                ));
            }
            object.insert(
                std::string::String::from("modifierExtension"),
                serde_json::Value::Array(items),
            );
        }
        if let Some(v) = super::super::codec::Primitive::value_json(&self.severity)? {
            object.insert(std::string::String::from("severity"), v);
        }
        if let Some(e) = super::super::codec::Primitive::element_json(&self.severity)? {
            object.insert(std::string::String::from("_severity"), e);
        }
        if let Some(v) = super::super::codec::Primitive::value_json(&self.code)? {
            object.insert(std::string::String::from("code"), v);
        }
        if let Some(e) = super::super::codec::Primitive::element_json(&self.code)? {
            object.insert(std::string::String::from("_code"), e);
        }
        if let Some(item) = &self.details {
            object.insert(
                std::string::String::from("details"),
                serde_json::Value::Object(super::super::codec::Json::to_json(item)?),
            );
        }
        if let Some(item) = &self.diagnostics {
            if let Some(v) = super::super::codec::Primitive::value_json(item)? {
                object.insert(std::string::String::from("diagnostics"), v);
            }
            if let Some(e) = super::super::codec::Primitive::element_json(item)? {
                object.insert(std::string::String::from("_diagnostics"), e);
            }
        }
        if !self.location.is_empty() {
            let (values, elements) = super::super::codec::primitive_arrays(&self.location)?;
            object.insert(std::string::String::from("location"), values);
            if let Some(elements) = elements {
                object.insert(std::string::String::from("_location"), elements);
            }
        }
        if !self.expression.is_empty() {
            let (values, elements) = super::super::codec::primitive_arrays(&self.expression)?;
            object.insert(std::string::String::from("expression"), values);
            if let Some(elements) = elements {
                object.insert(std::string::String::from("_expression"), elements);
            }
        }
        Ok(object)
    }

    fn from_json(
        object: &super::super::codec::Object,
        path: &mut super::super::codec::Path,
    ) -> Result<Self, super::super::codec::DecodeError> {
        let mut raw_id: Option<&serde_json::Value> = None;
        let mut raw_extension: Option<&serde_json::Value> = None;
        let mut raw_modifier_extension: Option<&serde_json::Value> = None;
        let mut raw_severity: Option<&serde_json::Value> = None;
        let mut raw_severity_element: Option<&serde_json::Value> = None;
        let mut raw_code: Option<&serde_json::Value> = None;
        let mut raw_code_element: Option<&serde_json::Value> = None;
        let mut raw_details: Option<&serde_json::Value> = None;
        let mut raw_diagnostics: Option<&serde_json::Value> = None;
        let mut raw_diagnostics_element: Option<&serde_json::Value> = None;
        let mut raw_location: Option<&serde_json::Value> = None;
        let mut raw_location_element: Option<&serde_json::Value> = None;
        let mut raw_expression: Option<&serde_json::Value> = None;
        let mut raw_expression_element: Option<&serde_json::Value> = None;
        for (key, value) in object {
            match key.as_str() {
                "id" => raw_id = Some(value),
                "extension" => raw_extension = Some(value),
                "modifierExtension" => raw_modifier_extension = Some(value),
                "severity" => raw_severity = Some(value),
                "_severity" => raw_severity_element = Some(value),
                "code" => raw_code = Some(value),
                "_code" => raw_code_element = Some(value),
                "details" => raw_details = Some(value),
                "diagnostics" => raw_diagnostics = Some(value),
                "_diagnostics" => raw_diagnostics_element = Some(value),
                "location" => raw_location = Some(value),
                "_location" => raw_location_element = Some(value),
                "expression" => raw_expression = Some(value),
                "_expression" => raw_expression_element = Some(value),
                other => {
                    return path.with(other, |path| {
                        Err(path.error(super::super::codec::DecodeErrorKind::UnknownProperty))
                    });
                }
            }
        }
        let field_id = raw_id
            .map(|value| {
                path.with("id", |path| {
                    let value = super::super::codec::expect_single(value, path)?;
                    super::super::codec::expect_string(value, path)
                })
            })
            .transpose()?;
        let mut field_extension = Vec::new();
        if let Some(raw) = raw_extension {
            for (index, value) in super::super::codec::expect_array(raw, path)?
                .iter()
                .enumerate()
            {
                field_extension.push(path.with_index("extension", index, |path| {
                    super::super::codec::Json::from_json(
                        super::super::codec::expect_object(value, path)?,
                        path,
                    )
                })?);
            }
        }
        let mut field_modifier_extension = Vec::new();
        if let Some(raw) = raw_modifier_extension {
            for (index, value) in super::super::codec::expect_array(raw, path)?
                .iter()
                .enumerate()
            {
                field_modifier_extension.push(path.with_index(
                    "modifierExtension",
                    index,
                    |path| {
                        super::super::codec::Json::from_json(
                            super::super::codec::expect_object(value, path)?,
                            path,
                        )
                    },
                )?);
            }
        }
        let field_severity = path.with("severity", |path| {
            super::super::codec::Primitive::from_json_parts(
                raw_severity,
                raw_severity_element,
                path,
            )
        })?;
        let field_code = path.with("code", |path| {
            super::super::codec::Primitive::from_json_parts(raw_code, raw_code_element, path)
        })?;
        let field_details = raw_details
            .map(|value| {
                path.with("details", |path| {
                    super::super::codec::Json::from_json(
                        super::super::codec::expect_object(
                            super::super::codec::expect_single(value, path)?,
                            path,
                        )?,
                        path,
                    )
                })
            })
            .transpose()?;
        let field_diagnostics = match (raw_diagnostics, raw_diagnostics_element) {
            (None, None) => None,
            (value, element) => Some(path.with("diagnostics", |path| {
                super::super::codec::Primitive::from_json_parts(value, element, path)
            })?),
        };
        let mut field_location = Vec::new();
        for (index, (value, element)) in
            super::super::codec::pair_arrays(raw_location, raw_location_element, path)?
                .into_iter()
                .enumerate()
        {
            field_location.push(path.with_index("location", index, |path| {
                super::super::codec::Primitive::from_json_parts(value, element, path)
            })?);
        }
        let mut field_expression = Vec::new();
        for (index, (value, element)) in
            super::super::codec::pair_arrays(raw_expression, raw_expression_element, path)?
                .into_iter()
                .enumerate()
        {
            field_expression.push(path.with_index("expression", index, |path| {
                super::super::codec::Primitive::from_json_parts(value, element, path)
            })?);
        }
        Ok(Self {
            id: field_id,
            extension: field_extension,
            modifier_extension: field_modifier_extension,
            severity: field_severity,
            code: field_code,
            details: field_details,
            diagnostics: field_diagnostics,
            location: field_location,
            expression: field_expression,
        })
    }
}

impl serde::Serialize for OperationOutcomeIssue {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        super::super::codec::Json::to_json(self)
            .map_err(serde::ser::Error::custom)?
            .serialize(serializer)
    }
}

impl<'de> serde::Deserialize<'de> for OperationOutcomeIssue {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = serde_json::Value::deserialize(deserializer)?;
        let mut path = super::super::codec::Path::root("OperationOutcomeIssue");
        let object =
            super::super::codec::expect_object(&value, &path).map_err(serde::de::Error::custom)?;
        super::super::codec::Json::from_json(object, &mut path).map_err(serde::de::Error::custom)
    }
}
