// @generated by notio-fhir-codegen from hl7.fhir.r4b.core 4.3.0. DO NOT EDIT.
// Change the emitter (tools/notio-fhir-codegen) and regenerate.
//! The FHIR primitive types (<https://hl7.org/fhir/R4B/datatypes.html#primitive>).

/// Primitive Type base64Binary
///
/// A stream of bytes
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Base64Binary {
    /// xml:id (or equivalent in JSON)
    ///
    /// unique id for the element within a resource (for internal references)
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the resource. To make the use of extensions safe and
    /// manageable, there is a strict set of governance applied to the definition
    /// and use of extensions. Though any implementer can define an extension, there
    /// is a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// Primitive value for base64Binary
    ///
    /// The actual value
    pub value: Option<std::string::String>,
}

/// Primitive Type boolean
///
/// Value of "true" or "false"
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Boolean {
    /// xml:id (or equivalent in JSON)
    ///
    /// unique id for the element within a resource (for internal references)
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the resource. To make the use of extensions safe and
    /// manageable, there is a strict set of governance applied to the definition
    /// and use of extensions. Though any implementer can define an extension, there
    /// is a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// Primitive value for boolean
    ///
    /// The actual value
    pub value: Option<bool>,
}

/// Primitive Type canonical
///
/// A URI that is a reference to a canonical URL on a FHIR resource
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Canonical {
    /// xml:id (or equivalent in JSON)
    ///
    /// unique id for the element within a resource (for internal references)
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the resource. To make the use of extensions safe and
    /// manageable, there is a strict set of governance applied to the definition
    /// and use of extensions. Though any implementer can define an extension, there
    /// is a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// Primitive value for canonical
    pub value: Option<std::string::String>,
}

/// Primitive Type code
///
/// A string which has at least one character and no leading or trailing
/// whitespace and where there is no whitespace other than single spaces in the
/// contents
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Code {
    /// xml:id (or equivalent in JSON)
    ///
    /// unique id for the element within a resource (for internal references)
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the resource. To make the use of extensions safe and
    /// manageable, there is a strict set of governance applied to the definition
    /// and use of extensions. Though any implementer can define an extension, there
    /// is a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// Primitive value for code
    pub value: Option<std::string::String>,
}

/// Primitive Type date
///
/// A date or partial date (e.g. just year or year + month). There is no time
/// zone. The format is a union of the schema types gYear, gYearMonth and date.
/// Dates SHALL be valid dates.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Date {
    /// xml:id (or equivalent in JSON)
    ///
    /// unique id for the element within a resource (for internal references)
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the resource. To make the use of extensions safe and
    /// manageable, there is a strict set of governance applied to the definition
    /// and use of extensions. Though any implementer can define an extension, there
    /// is a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// Primitive value for date
    ///
    /// The actual value
    pub value: Option<std::string::String>,
}

/// Primitive Type dateTime
///
/// A date, date-time or partial date (e.g. just year or year + month). If hours
/// and minutes are specified, a time zone SHALL be populated. The format is a
/// union of the schema types gYear, gYearMonth, date and dateTime. Seconds must
/// be provided due to schema type constraints but may be zero-filled and may be
/// ignored. Dates SHALL be valid dates.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DateTime {
    /// xml:id (or equivalent in JSON)
    ///
    /// unique id for the element within a resource (for internal references)
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the resource. To make the use of extensions safe and
    /// manageable, there is a strict set of governance applied to the definition
    /// and use of extensions. Though any implementer can define an extension, there
    /// is a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// Primitive value for dateTime
    ///
    /// The actual value
    pub value: Option<std::string::String>,
}

/// Primitive Type decimal
///
/// A rational number with implicit precision
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Decimal {
    /// xml:id (or equivalent in JSON)
    ///
    /// unique id for the element within a resource (for internal references)
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the resource. To make the use of extensions safe and
    /// manageable, there is a strict set of governance applied to the definition
    /// and use of extensions. Though any implementer can define an extension, there
    /// is a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// Primitive value for decimal
    ///
    /// The actual value
    pub value: Option<std::string::String>,
}

/// Primitive Type id
///
/// Any combination of letters, numerals, "-" and ".", with a length limit of 64
/// characters. (This might be an integer, an unprefixed OID, UUID or any other
/// identifier pattern that meets these constraints.) Ids are case-insensitive.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Id {
    /// xml:id (or equivalent in JSON)
    ///
    /// unique id for the element within a resource (for internal references)
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the resource. To make the use of extensions safe and
    /// manageable, there is a strict set of governance applied to the definition
    /// and use of extensions. Though any implementer can define an extension, there
    /// is a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// Primitive value for id
    pub value: Option<std::string::String>,
}

/// Primitive Type instant
///
/// An instant in time - known at least to the second
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Instant {
    /// xml:id (or equivalent in JSON)
    ///
    /// unique id for the element within a resource (for internal references)
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the resource. To make the use of extensions safe and
    /// manageable, there is a strict set of governance applied to the definition
    /// and use of extensions. Though any implementer can define an extension, there
    /// is a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// Primitive value for instant
    ///
    /// The actual value
    pub value: Option<std::string::String>,
}

/// Primitive Type integer
///
/// A whole number
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Integer {
    /// xml:id (or equivalent in JSON)
    ///
    /// unique id for the element within a resource (for internal references)
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the resource. To make the use of extensions safe and
    /// manageable, there is a strict set of governance applied to the definition
    /// and use of extensions. Though any implementer can define an extension, there
    /// is a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// Primitive value for integer
    ///
    /// The actual value
    pub value: Option<i32>,
}

/// Primitive Type markdown
///
/// A string that may contain Github Flavored Markdown syntax for optional
/// processing by a mark down presentation engine
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Markdown {
    /// xml:id (or equivalent in JSON)
    ///
    /// unique id for the element within a resource (for internal references)
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the resource. To make the use of extensions safe and
    /// manageable, there is a strict set of governance applied to the definition
    /// and use of extensions. Though any implementer can define an extension, there
    /// is a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// Primitive value for markdown
    pub value: Option<std::string::String>,
}

/// Primitive Type oid
///
/// An OID represented as a URI
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Oid {
    /// xml:id (or equivalent in JSON)
    ///
    /// unique id for the element within a resource (for internal references)
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the resource. To make the use of extensions safe and
    /// manageable, there is a strict set of governance applied to the definition
    /// and use of extensions. Though any implementer can define an extension, there
    /// is a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// Primitive value for oid
    pub value: Option<std::string::String>,
}

/// Primitive Type positiveInt
///
/// An integer with a value that is positive (e.g. \>0)
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PositiveInt {
    /// xml:id (or equivalent in JSON)
    ///
    /// unique id for the element within a resource (for internal references)
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the resource. To make the use of extensions safe and
    /// manageable, there is a strict set of governance applied to the definition
    /// and use of extensions. Though any implementer can define an extension, there
    /// is a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// Primitive value for positiveInt
    pub value: Option<u32>,
}

/// Primitive Type string
///
/// A sequence of Unicode characters
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct String {
    /// xml:id (or equivalent in JSON)
    ///
    /// unique id for the element within a resource (for internal references)
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the resource. To make the use of extensions safe and
    /// manageable, there is a strict set of governance applied to the definition
    /// and use of extensions. Though any implementer can define an extension, there
    /// is a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// Primitive value for string
    ///
    /// The actual value
    pub value: Option<std::string::String>,
}

/// Primitive Type time
///
/// A time during the day, with no date specified
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Time {
    /// xml:id (or equivalent in JSON)
    ///
    /// unique id for the element within a resource (for internal references)
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the resource. To make the use of extensions safe and
    /// manageable, there is a strict set of governance applied to the definition
    /// and use of extensions. Though any implementer can define an extension, there
    /// is a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// Primitive value for time
    ///
    /// The actual value
    pub value: Option<std::string::String>,
}

/// Primitive Type unsignedInt
///
/// An integer with a value that is not negative (e.g. \>= 0)
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UnsignedInt {
    /// xml:id (or equivalent in JSON)
    ///
    /// unique id for the element within a resource (for internal references)
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the resource. To make the use of extensions safe and
    /// manageable, there is a strict set of governance applied to the definition
    /// and use of extensions. Though any implementer can define an extension, there
    /// is a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// Primitive value for unsignedInt
    pub value: Option<u32>,
}

/// Primitive Type uri
///
/// String of characters used to identify a name or a resource
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Uri {
    /// xml:id (or equivalent in JSON)
    ///
    /// unique id for the element within a resource (for internal references)
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the resource. To make the use of extensions safe and
    /// manageable, there is a strict set of governance applied to the definition
    /// and use of extensions. Though any implementer can define an extension, there
    /// is a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// Primitive value for uri
    ///
    /// The actual value
    pub value: Option<std::string::String>,
}

/// Primitive Type url
///
/// A URI that is a literal reference
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Url {
    /// xml:id (or equivalent in JSON)
    ///
    /// unique id for the element within a resource (for internal references)
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the resource. To make the use of extensions safe and
    /// manageable, there is a strict set of governance applied to the definition
    /// and use of extensions. Though any implementer can define an extension, there
    /// is a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// Primitive value for url
    pub value: Option<std::string::String>,
}

/// Primitive Type uuid
///
/// A UUID, represented as a URI
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Uuid {
    /// xml:id (or equivalent in JSON)
    ///
    /// unique id for the element within a resource (for internal references)
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the resource. To make the use of extensions safe and
    /// manageable, there is a strict set of governance applied to the definition
    /// and use of extensions. Though any implementer can define an extension, there
    /// is a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// Primitive value for uuid
    pub value: Option<std::string::String>,
}

/// Primitive Type xhtml
///
/// XHTML
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Xhtml {
    /// xml:id (or equivalent in JSON)
    ///
    /// unique id for the element within a resource (for internal references)
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the resource. To make the use of extensions safe and
    /// manageable, there is a strict set of governance applied to the definition
    /// and use of extensions. Though any implementer can define an extension, there
    /// is a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Option<super::extension::Extension>,
    /// Actual xhtml
    pub value: std::string::String,
}
