# SPDX-License-Identifier: Apache-2.0
[package]
name = "ferroterm-rf2"
description = "SNOMED CT RF2 loader and typed component model"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
csv.workspace = true
jiff.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
