use std::fs;
use std::path::Path;

use ferroterm_fhir_codegen::emit::{EmitError, EmitOptions, VersionInput, emit};
use ferroterm_fhir_codegen::version_inputs;

use crate::{r4b_dir, vendor_dir};

fn r4b_only(crate_dir: &Path, check: bool) -> EmitOptions {
    EmitOptions {
        versions: vec![VersionInput {
            module: String::from("r4b"),
            package_dir: r4b_dir(),
        }],
        crate_dir: crate_dir.to_path_buf(),
        check,
    }
}

fn all_versions(crate_dir: &Path, check: bool) -> EmitOptions {
    EmitOptions {
        versions: version_inputs(&vendor_dir()),
        crate_dir: crate_dir.to_path_buf(),
        check,
    }
}

fn tree(root: &Path) -> Vec<(String, String)> {
    let mut files = Vec::new();
    for entry in fs::read_dir(root).expect("dir listable") {
        let path = entry.expect("entry readable").path();
        if path.is_dir() {
            files.extend(tree(&path));
        } else {
            files.push((
                path.to_string_lossy().into_owned(),
                fs::read_to_string(&path).expect("file readable"),
            ));
        }
    }
    files.sort();
    files
}

#[test]
fn emitting_twice_is_byte_identical_and_check_passes() {
    let first = tempfile::tempdir().expect("tempdir");
    let second = tempfile::tempdir().expect("tempdir");
    let report = emit(&r4b_only(first.path(), false)).expect("first emit");
    emit(&r4b_only(second.path(), false)).expect("second emit");
    assert_eq!(report.types.get("r4b"), Some(&133));
    assert_eq!(report.files.len(), 58);
    let a: Vec<String> = tree(&first.path().join("src"))
        .into_iter()
        .map(|(_, c)| c)
        .collect();
    let b: Vec<String> = tree(&second.path().join("src"))
        .into_iter()
        .map(|(_, c)| c)
        .collect();
    assert_eq!(a, b);
    emit(&r4b_only(first.path(), true)).expect("check passes on a fresh tree");
}

#[test]
fn every_generated_file_carries_the_banner() {
    let dir = tempfile::tempdir().expect("tempdir");
    emit(&all_versions(dir.path(), false)).expect("emit");
    for (path, content) in tree(&dir.path().join("src")) {
        assert!(
            content.starts_with("// @generated by ferroterm-fhir-codegen from hl7.fhir."),
            "{path} starts with the banner"
        );
        assert!(content.contains("DO NOT EDIT"), "{path} says DO NOT EDIT");
    }
    let lib = fs::read_to_string(dir.path().join("src/lib.rs")).expect("lib.rs");
    assert!(lib.contains("pub mod r4;\npub mod r4b;\npub mod r5;\npub mod r6;\n"));
    assert!(lib.starts_with(
        "// @generated by ferroterm-fhir-codegen from hl7.fhir.r4.core 4.0.1, hl7.fhir.r4b.core 4.3.0, hl7.fhir.r5.core 5.0.0, hl7.fhir.r6.core 6.0.0-ballot5. DO NOT EDIT.\n"
    ));
}

#[test]
fn check_reports_edited_missing_and_stale_files() {
    let dir = tempfile::tempdir().expect("tempdir");
    emit(&r4b_only(dir.path(), false)).expect("emit");
    let src = dir.path().join("src");
    fs::write(src.join("r4b/coding.rs"), "// edited\n").expect("edit");
    fs::remove_file(src.join("r4b/meta.rs")).expect("remove");
    fs::write(src.join("r4b/stale.rs"), "// stale\n").expect("stale");
    match emit(&r4b_only(dir.path(), true)) {
        Err(EmitError::Drift { paths }) => {
            assert_eq!(
                paths,
                vec![
                    "r4b/coding.rs",
                    "r4b/meta.rs (missing)",
                    "r4b/stale.rs (stale)"
                ]
            );
        }
        other => panic!("expected Drift, got {other:?}"),
    }
}

#[test]
fn no_versions_is_refused() {
    let dir = tempfile::tempdir().expect("tempdir");
    let options = EmitOptions {
        versions: Vec::new(),
        crate_dir: dir.path().to_path_buf(),
        check: false,
    };
    assert!(matches!(emit(&options), Err(EmitError::NoVersions)));
}

#[test]
fn the_committed_crate_is_in_sync() {
    let crate_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../crates/ferroterm-fhir");
    emit(&all_versions(&crate_dir, true))
        .expect("the committed ferroterm-fhir crate matches the emitter");
}

#[test]
fn defaults_and_value_constructors_follow_the_definitions() {
    let dir = tempfile::tempdir().expect("tempdir");
    emit(&r4b_only(dir.path(), false)).expect("emit");
    let read =
        |file: &str| fs::read_to_string(dir.path().join("src/r4b").join(file)).expect("file");
    let capabilities = read("terminology_capabilities.rs");
    assert!(
        capabilities.contains(
            "#[derive(Debug, Clone, Default, PartialEq, Eq)]\npub struct TerminologyCapabilities {"
        ),
        "every required element of TerminologyCapabilities is a primitive, so it derives Default"
    );
    let code_system = read("code_system.rs");
    assert!(
        code_system.contains(
            "#[derive(Debug, Clone, PartialEq, Eq)]\npub struct CodeSystemConceptProperty {"
        ),
        "CodeSystem.concept.property.value[x] is a required choice, so no Default"
    );
    assert!(
        code_system
            .contains("#[derive(Debug, Clone, Default, PartialEq, Eq)]\npub struct CodeSystem {")
    );
    let primitives = read("primitives.rs");
    for (name, scalar) in [
        ("Code", "std::string::String"),
        ("Boolean", "bool"),
        ("Integer", "i32"),
        ("PositiveInt", "u32"),
        ("UnsignedInt", "u32"),
        ("Xhtml", "std::string::String"),
    ] {
        assert!(
            primitives.contains(&format!("impl From<{scalar}> for {name} {{")),
            "{name} from {scalar}"
        );
    }
    assert!(primitives.contains("impl From<&str> for Code {"));
    // Operation structs follow the same rule: a request of optional parameters
    // derives Default; a part struct with a required open-type value does not.
    let lookup = read("operations/code_system_lookup.rs");
    assert!(lookup.contains(
        "#[derive(Debug, Clone, Default, PartialEq, Eq)]\npub struct CodeSystemLookupRequest {"
    ));
    assert!(lookup.contains(
        "#[derive(Debug, Clone, PartialEq, Eq)]\npub struct CodeSystemLookupResponsePropertySubproperty {"
    ));
    assert!(!primitives.contains("impl From<&str> for Boolean {"));
}
