# SPDX-License-Identifier: MIT
[package]
name = "notio-text"
description = "The fst and roaring description search index"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
thiserror.workspace = true

[lints]
workspace = true
