# SPDX-License-Identifier: BUSL-1.1
[package]
name = "ferroterm-text"
description = "The fst and roaring description search index"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
ferroterm-graph.workspace = true
fst.workspace = true
roaring.workspace = true
thiserror.workspace = true
unicode-normalization.workspace = true

[dev-dependencies]
ferroterm-rf2.workspace = true
proptest.workspace = true

[lints]
workspace = true
