//! Rendering type definitions to source text.
//!
//! One file per module; every file opens with the `@generated` banner. Types
//! reference each other by `super::<module>::<Name>` paths, so no module
//! re-exports anything.

use std::fmt::{self, Write};

use crate::lower::{
    Cardinality, Docs, Field, PRIMITIVES_MODULE, RESOURCE_MODULE, Scalar, Target, TypeDef,
    TypeKind, UNKNOWN_RESOURCE, Variant, VersionModule,
};
use crate::naming::module_name;

/// The banner every generated file starts with.
#[must_use]
pub fn banner(model: &VersionModule) -> String {
    format!(
        "// @generated by notio-fhir-codegen from {} {}. DO NOT EDIT.\n// Change the emitter (tools/notio-fhir-codegen) and regenerate.\n",
        model.package_name, model.package_version
    )
}

/// The banner of a file that belongs to every version, naming every package.
#[must_use]
pub fn crate_banner(models: &[VersionModule]) -> String {
    let packages: Vec<String> = models
        .iter()
        .map(|model| format!("{} {}", model.package_name, model.package_version))
        .collect();
    format!(
        "// @generated by notio-fhir-codegen from {}. DO NOT EDIT.\n// Change the emitter (tools/notio-fhir-codegen) and regenerate.\n",
        packages.join(", ")
    )
}

/// The `src/lib.rs` of the generated crate, declaring every version module.
///
/// # Errors
///
/// Returns [`fmt::Error`] only if writing to the string fails, which `String` never does.
pub fn render_lib(models: &[VersionModule]) -> Result<String, fmt::Error> {
    let mut out = crate_banner(models);
    out.push_str(
        "//! Per-version FHIR types and terminology operation contracts.\n//!\n//! Generated by `notio-fhir-codegen` from the vendored HL7 FHIR packages, one\n//! module per FHIR version. Every file is `@generated`; change the emitter\n//! and regenerate, never the output.\n",
    );
    out.push_str("#![allow(\n    clippy::doc_markdown,\n    clippy::large_enum_variant,\n    clippy::module_name_repetitions,\n    clippy::struct_field_names,\n    reason = \"generated from the FHIR specification: the documentation is the specification's own text, choice enums hold every allowed type, and modules mirror FHIR type names\"\n)]\n\n");
    writeln!(out, "pub mod operation;")?;
    for model in models {
        writeln!(out, "pub mod {};", model.name)?;
    }
    Ok(out)
}

/// The `mod.rs` of the version module.
///
/// # Errors
///
/// Returns [`fmt::Error`] only if writing to the string fails, which `String` never does.
pub fn render_version_mod(model: &VersionModule) -> Result<String, fmt::Error> {
    let mut out = banner(model);
    writeln!(
        out,
        "//! FHIR {} types: the terminology root set and the complete closure of the\n//! datatypes and primitives it references, from `{}` {}.\n",
        model.name.to_uppercase(),
        model.package_name,
        model.package_version
    )?;
    for module in model.modules().keys() {
        writeln!(out, "pub mod {module};")?;
    }
    writeln!(out, "pub mod operations;")?;
    Ok(out)
}

/// One module file.
///
/// # Errors
///
/// Returns [`fmt::Error`] only if writing to the string fails, which `String` never does.
pub fn render_module(
    model: &VersionModule,
    module: &str,
    types: &[&TypeDef],
) -> Result<String, fmt::Error> {
    let mut out = banner(model);
    let heading = match module {
        PRIMITIVES_MODULE => format!(
            "The FHIR primitive types (<https://hl7.org/fhir/{}/datatypes.html#primitive>).",
            model.name.to_uppercase()
        ),
        RESOURCE_MODULE => {
            String::from("The abstract `Resource` type as an enum over the root set.")
        }
        _ => types
            .iter()
            .find(|ty| module_name(&ty.name) == module)
            .and_then(|ty| ty.docs.short.clone())
            .map_or_else(
                || format!("The `{module}` type and its parts."),
                |short| escape_doc(&short),
            ),
    };
    writeln!(out, "//! {heading}\n")?;
    for ty in types {
        render_type(model, &mut out, module, ty)?;
        out.push('\n');
    }
    Ok(out)
}

fn render_type(model: &VersionModule, out: &mut String, module: &str, ty: &TypeDef) -> fmt::Result {
    render_docs(out, &ty.docs, "")?;
    match &ty.kind {
        TypeKind::Struct { fields } => {
            out.push_str("#[derive(Debug, Clone, PartialEq, Eq)]\n");
            writeln!(out, "pub struct {} {{", ty.name)?;
            for field in fields {
                render_field(model, out, module, field)?;
            }
            out.push_str("}\n");
        }
        TypeKind::Choice { variants, .. } => {
            out.push_str("#[derive(Debug, Clone, PartialEq, Eq)]\n");
            writeln!(out, "pub enum {} {{", ty.name)?;
            for variant in variants {
                render_variant(model, out, module, variant)?;
            }
            out.push_str("}\n");
        }
        TypeKind::ResourceEnum { resources } => {
            out.push_str("#[derive(Debug, Clone, PartialEq, Eq)]\n");
            writeln!(out, "pub enum {} {{", ty.name)?;
            for resource in resources {
                writeln!(out, "    /// A `{resource}` resource.")?;
                writeln!(
                    out,
                    "    {resource}(Box<super::{}::{resource}>),",
                    module_name(resource)
                )?;
            }
            out.push_str("    /// A resource of a type outside the root set.\n");
            writeln!(out, "    Unknown({UNKNOWN_RESOURCE}),")?;
            out.push_str("}\n");
        }
        TypeKind::UnknownResource => {
            out.push_str("#[derive(Debug, Clone, PartialEq, Eq)]\n");
            writeln!(out, "pub struct {} {{", ty.name)?;
            out.push_str("    /// The `resourceType` of the carried resource.\n");
            out.push_str("    pub resource_type: std::string::String,\n");
            out.push_str("    /// The complete JSON object, `resourceType` included.\n");
            out.push_str("    pub body: serde_json::Value,\n");
            out.push_str("}\n");
        }
    }
    Ok(())
}

fn render_field(
    model: &VersionModule,
    out: &mut String,
    module: &str,
    field: &Field,
) -> fmt::Result {
    render_docs(out, &field.docs, "    ")?;
    let inner = render_target(model, module, &field.ty.target, field.ty.boxed);
    let ty = match field.ty.card {
        Cardinality::One => inner,
        Cardinality::Optional => format!("Option<{inner}>"),
        Cardinality::Many => format!("Vec<{inner}>"),
    };
    writeln!(out, "    pub {}: {ty},", field.name)
}

fn render_variant(
    model: &VersionModule,
    out: &mut String,
    module: &str,
    variant: &Variant,
) -> fmt::Result {
    writeln!(out, "    /// The `{}` form.", variant.code)?;
    let inner = render_target(model, module, &variant.target, variant.boxed);
    writeln!(out, "    {}({inner}),", variant.name)
}

fn render_target(model: &VersionModule, module: &str, target: &Target, boxed: bool) -> String {
    let path = match target {
        Target::Inline(Scalar::Bool) => String::from("bool"),
        Target::Inline(Scalar::I32) => String::from("i32"),
        Target::Inline(Scalar::U32) => String::from("u32"),
        Target::Inline(Scalar::I64) => String::from("i64"),
        Target::Inline(Scalar::Str) => String::from("std::string::String"),
        Target::Named(name) => {
            let target_module = model
                .types
                .get(name)
                .map_or_else(|| module_name(name), |ty| ty.module.clone());
            if target_module == module {
                name.clone()
            } else {
                format!("super::{target_module}::{name}")
            }
        }
    };
    if boxed { format!("Box<{path}>") } else { path }
}

fn render_docs(out: &mut String, docs: &Docs, indent: &str) -> fmt::Result {
    let short = docs.short.as_deref().map(escape_doc);
    let definition = docs.definition.as_deref().map(escape_doc);
    match (short, definition) {
        (Some(short), Some(definition)) if same_sentence(&short, &definition) => {
            for line in wrap(&definition) {
                writeln!(out, "{indent}/// {line}")?;
            }
        }
        (Some(short), Some(definition)) => {
            for line in wrap(&short) {
                writeln!(out, "{indent}/// {line}")?;
            }
            writeln!(out, "{indent}///")?;
            for line in wrap(&definition) {
                writeln!(out, "{indent}/// {line}")?;
            }
        }
        (Some(text), None) | (None, Some(text)) => {
            for line in wrap(&text) {
                writeln!(out, "{indent}/// {line}")?;
            }
        }
        (None, None) => {
            writeln!(out, "{indent}/// (undocumented in the package)")?;
        }
    }
    Ok(())
}

/// Whether the short description and the definition say the same thing, so the
/// documentation shows the sentence once.
fn same_sentence(short: &str, definition: &str) -> bool {
    let trim = |s: &str| s.trim_end_matches(['.', '!']).trim().to_lowercase();
    trim(short) == trim(definition)
}

/// Escapes specification text for rustdoc.
///
/// Brackets would read as intra-doc links, angle brackets and asterisks as
/// markup, and a bare URL fails the `bare_urls` lint, so every URL is wrapped
/// in angle brackets wherever it sits in the text.
#[must_use]
pub fn escape_doc(text: &str) -> String {
    let chars: Vec<char> = text
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
        .chars()
        .collect();
    let mut out = String::with_capacity(chars.len() + 16);
    let mut index = 0;
    while index < chars.len() {
        if starts_url(&chars, index) {
            let start = index;
            while index < chars.len()
                && !chars.get(index).is_some_and(|c| {
                    c.is_whitespace()
                        || matches!(c, ')' | ']' | '`' | '\\' | '<' | '>' | '"' | '\'')
                })
            {
                index += 1;
            }
            let mut end = index;
            while end > start
                && chars
                    .get(end - 1)
                    .is_some_and(|c| matches!(c, '.' | ',' | ';' | ':'))
            {
                end -= 1;
            }
            out.push('<');
            out.extend(chars.get(start..end).into_iter().flatten());
            out.push('>');
            out.extend(chars.get(end..index).into_iter().flatten());
        } else if let Some(ch) = chars.get(index) {
            match ch {
                '[' | ']' | '<' | '>' | '*' | '_' | '`' | '\\' | '#' => {
                    out.push('\\');
                    out.push(*ch);
                }
                _ => out.push(*ch),
            }
            index += 1;
        }
    }
    out
}

fn starts_url(chars: &[char], index: usize) -> bool {
    const HTTP: [char; 7] = ['h', 't', 't', 'p', ':', '/', '/'];
    const HTTPS: [char; 8] = ['h', 't', 't', 'p', 's', ':', '/', '/'];
    chars.get(index..index + HTTP.len()) == Some(&HTTP[..])
        || chars.get(index..index + HTTPS.len()) == Some(&HTTPS[..])
}

fn wrap(text: &str) -> Vec<String> {
    let mut lines = Vec::new();
    let mut current = String::new();
    for word in text.split(' ') {
        if !current.is_empty() && current.chars().count() + 1 + word.chars().count() > 76 {
            lines.push(std::mem::take(&mut current));
        }
        if !current.is_empty() {
            current.push(' ');
        }
        current.push_str(word);
    }
    if !current.is_empty() {
        lines.push(current);
    }
    lines
}

#[cfg(test)]
mod tests {
    use super::escape_doc;

    #[test]
    fn identical_short_and_definition_render_once() {
        let mut out = String::new();
        super::render_docs(
            &mut out,
            &crate::lower::Docs {
                short: Some("ISO 4217 Currency Code".to_owned()),
                definition: Some("ISO 4217 Currency Code.".to_owned()),
            },
            "",
        )
        .expect("renders");
        assert_eq!(out, "/// ISO 4217 Currency Code.\n");
    }

    #[test]
    fn brackets_and_urls_are_escaped() {
        assert_eq!(escape_doc("The value[x] of it"), "The value\\[x\\] of it");
        assert_eq!(
            escape_doc("See http://hl7.org/fhir. Now"),
            "See <http://hl7.org/fhir>. Now"
        );
        assert_eq!(escape_doc("a <b> c"), "a \\<b\\> c");
        assert_eq!(
            escape_doc("[link](http://x.org/a#b) done"),
            "\\[link\\](<http://x.org/a#b>) done"
        );
        assert_eq!(
            escape_doc("```http://x.org```), that"),
            "\\`\\`\\`<http://x.org>\\`\\`\\`), that"
        );
    }
}
