// @generated by fhir-codegen from hl7.fhir.r4.core 4.0.1. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
//! Optional Extensions Element

/// Optional Extensions Element
///
/// Optional Extension Element - found in all resources.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Extension {
    /// Unique id for inter-element referencing
    ///
    /// Unique id for the element within a resource (for internal references). This
    /// may be any string value that does not contain spaces.
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the element. To make the use of extensions safe and
    /// manageable, there is a strict set of governance applied to the definition
    /// and use of extensions. Though any implementer can define an extension, there
    /// is a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<Extension>,
    /// identifies the meaning of the extension
    ///
    /// Source of the definition for the extension code - a logical name or a URL.
    pub url: std::string::String,
    /// Value of extension
    ///
    /// Value of extension - must be one of a constrained set of the data types (see
    /// \[Extensibility\](extensibility.html) for a list).
    pub value: Option<ExtensionValue>,
}

impl super::super::codec::Json for Extension {
    fn to_json(&self) -> Result<super::super::codec::Object, super::super::codec::EncodeError> {
        let mut object = super::super::codec::Object::new();
        if let Some(v) = &self.id {
            object.insert(
                std::string::String::from("id"),
                serde_json::Value::String(v.clone()),
            );
        }
        if !self.extension.is_empty() {
            let mut items = Vec::with_capacity(self.extension.len());
            for item in &self.extension {
                items.push(serde_json::Value::Object(
                    super::super::codec::Json::to_json(item)?,
                ));
            }
            object.insert(
                std::string::String::from("extension"),
                serde_json::Value::Array(items),
            );
        }
        object.insert(
            std::string::String::from("url"),
            serde_json::Value::String(self.url.clone()),
        );
        if let Some(item) = &self.value {
            let (suffix, value, element) = item.to_json_parts()?;
            if let Some(value) = value {
                object.insert(format!("value{suffix}"), value);
            }
            if let Some(element) = element {
                object.insert(format!("_value{suffix}"), element);
            }
        }
        Ok(object)
    }

    fn from_json(
        object: &super::super::codec::Object,
        path: &mut super::super::codec::Path,
    ) -> Result<Self, super::super::codec::DecodeError> {
        let mut raw_id: Option<&serde_json::Value> = None;
        let mut raw_extension: Option<&serde_json::Value> = None;
        let mut raw_url: Option<&serde_json::Value> = None;
        let mut raw_value = super::super::codec::ChoiceSlot::default();
        for (key, value) in object {
            match key.as_str() {
                "id" => raw_id = Some(value),
                "extension" => raw_extension = Some(value),
                "url" => raw_url = Some(value),
                "valueBase64Binary" => {
                    raw_value.value("Base64Binary", value, path)?;
                }
                "_valueBase64Binary" => {
                    raw_value.element("Base64Binary", value, path)?;
                }
                "valueBoolean" => {
                    raw_value.value("Boolean", value, path)?;
                }
                "_valueBoolean" => {
                    raw_value.element("Boolean", value, path)?;
                }
                "valueCanonical" => {
                    raw_value.value("Canonical", value, path)?;
                }
                "_valueCanonical" => {
                    raw_value.element("Canonical", value, path)?;
                }
                "valueCode" => {
                    raw_value.value("Code", value, path)?;
                }
                "_valueCode" => {
                    raw_value.element("Code", value, path)?;
                }
                "valueDate" => {
                    raw_value.value("Date", value, path)?;
                }
                "_valueDate" => {
                    raw_value.element("Date", value, path)?;
                }
                "valueDateTime" => {
                    raw_value.value("DateTime", value, path)?;
                }
                "_valueDateTime" => {
                    raw_value.element("DateTime", value, path)?;
                }
                "valueDecimal" => {
                    raw_value.value("Decimal", value, path)?;
                }
                "_valueDecimal" => {
                    raw_value.element("Decimal", value, path)?;
                }
                "valueId" => {
                    raw_value.value("Id", value, path)?;
                }
                "_valueId" => {
                    raw_value.element("Id", value, path)?;
                }
                "valueInstant" => {
                    raw_value.value("Instant", value, path)?;
                }
                "_valueInstant" => {
                    raw_value.element("Instant", value, path)?;
                }
                "valueInteger" => {
                    raw_value.value("Integer", value, path)?;
                }
                "_valueInteger" => {
                    raw_value.element("Integer", value, path)?;
                }
                "valueMarkdown" => {
                    raw_value.value("Markdown", value, path)?;
                }
                "_valueMarkdown" => {
                    raw_value.element("Markdown", value, path)?;
                }
                "valueOid" => {
                    raw_value.value("Oid", value, path)?;
                }
                "_valueOid" => {
                    raw_value.element("Oid", value, path)?;
                }
                "valuePositiveInt" => {
                    raw_value.value("PositiveInt", value, path)?;
                }
                "_valuePositiveInt" => {
                    raw_value.element("PositiveInt", value, path)?;
                }
                "valueString" => {
                    raw_value.value("String", value, path)?;
                }
                "_valueString" => {
                    raw_value.element("String", value, path)?;
                }
                "valueTime" => {
                    raw_value.value("Time", value, path)?;
                }
                "_valueTime" => {
                    raw_value.element("Time", value, path)?;
                }
                "valueUnsignedInt" => {
                    raw_value.value("UnsignedInt", value, path)?;
                }
                "_valueUnsignedInt" => {
                    raw_value.element("UnsignedInt", value, path)?;
                }
                "valueUri" => {
                    raw_value.value("Uri", value, path)?;
                }
                "_valueUri" => {
                    raw_value.element("Uri", value, path)?;
                }
                "valueUrl" => {
                    raw_value.value("Url", value, path)?;
                }
                "_valueUrl" => {
                    raw_value.element("Url", value, path)?;
                }
                "valueUuid" => {
                    raw_value.value("Uuid", value, path)?;
                }
                "_valueUuid" => {
                    raw_value.element("Uuid", value, path)?;
                }
                "valueAddress" => {
                    raw_value.value("Address", value, path)?;
                }
                "_valueAddress" => {
                    raw_value.element("Address", value, path)?;
                }
                "valueAge" => {
                    raw_value.value("Age", value, path)?;
                }
                "_valueAge" => {
                    raw_value.element("Age", value, path)?;
                }
                "valueAnnotation" => {
                    raw_value.value("Annotation", value, path)?;
                }
                "_valueAnnotation" => {
                    raw_value.element("Annotation", value, path)?;
                }
                "valueAttachment" => {
                    raw_value.value("Attachment", value, path)?;
                }
                "_valueAttachment" => {
                    raw_value.element("Attachment", value, path)?;
                }
                "valueCodeableConcept" => {
                    raw_value.value("CodeableConcept", value, path)?;
                }
                "_valueCodeableConcept" => {
                    raw_value.element("CodeableConcept", value, path)?;
                }
                "valueCoding" => {
                    raw_value.value("Coding", value, path)?;
                }
                "_valueCoding" => {
                    raw_value.element("Coding", value, path)?;
                }
                "valueContactPoint" => {
                    raw_value.value("ContactPoint", value, path)?;
                }
                "_valueContactPoint" => {
                    raw_value.element("ContactPoint", value, path)?;
                }
                "valueCount" => {
                    raw_value.value("Count", value, path)?;
                }
                "_valueCount" => {
                    raw_value.element("Count", value, path)?;
                }
                "valueDistance" => {
                    raw_value.value("Distance", value, path)?;
                }
                "_valueDistance" => {
                    raw_value.element("Distance", value, path)?;
                }
                "valueDuration" => {
                    raw_value.value("Duration", value, path)?;
                }
                "_valueDuration" => {
                    raw_value.element("Duration", value, path)?;
                }
                "valueHumanName" => {
                    raw_value.value("HumanName", value, path)?;
                }
                "_valueHumanName" => {
                    raw_value.element("HumanName", value, path)?;
                }
                "valueIdentifier" => {
                    raw_value.value("Identifier", value, path)?;
                }
                "_valueIdentifier" => {
                    raw_value.element("Identifier", value, path)?;
                }
                "valueMoney" => {
                    raw_value.value("Money", value, path)?;
                }
                "_valueMoney" => {
                    raw_value.element("Money", value, path)?;
                }
                "valuePeriod" => {
                    raw_value.value("Period", value, path)?;
                }
                "_valuePeriod" => {
                    raw_value.element("Period", value, path)?;
                }
                "valueQuantity" => {
                    raw_value.value("Quantity", value, path)?;
                }
                "_valueQuantity" => {
                    raw_value.element("Quantity", value, path)?;
                }
                "valueRange" => {
                    raw_value.value("Range", value, path)?;
                }
                "_valueRange" => {
                    raw_value.element("Range", value, path)?;
                }
                "valueRatio" => {
                    raw_value.value("Ratio", value, path)?;
                }
                "_valueRatio" => {
                    raw_value.element("Ratio", value, path)?;
                }
                "valueReference" => {
                    raw_value.value("Reference", value, path)?;
                }
                "_valueReference" => {
                    raw_value.element("Reference", value, path)?;
                }
                "valueSampledData" => {
                    raw_value.value("SampledData", value, path)?;
                }
                "_valueSampledData" => {
                    raw_value.element("SampledData", value, path)?;
                }
                "valueSignature" => {
                    raw_value.value("Signature", value, path)?;
                }
                "_valueSignature" => {
                    raw_value.element("Signature", value, path)?;
                }
                "valueTiming" => {
                    raw_value.value("Timing", value, path)?;
                }
                "_valueTiming" => {
                    raw_value.element("Timing", value, path)?;
                }
                "valueContactDetail" => {
                    raw_value.value("ContactDetail", value, path)?;
                }
                "_valueContactDetail" => {
                    raw_value.element("ContactDetail", value, path)?;
                }
                "valueContributor" => {
                    raw_value.value("Contributor", value, path)?;
                }
                "_valueContributor" => {
                    raw_value.element("Contributor", value, path)?;
                }
                "valueDataRequirement" => {
                    raw_value.value("DataRequirement", value, path)?;
                }
                "_valueDataRequirement" => {
                    raw_value.element("DataRequirement", value, path)?;
                }
                "valueExpression" => {
                    raw_value.value("Expression", value, path)?;
                }
                "_valueExpression" => {
                    raw_value.element("Expression", value, path)?;
                }
                "valueParameterDefinition" => {
                    raw_value.value("ParameterDefinition", value, path)?;
                }
                "_valueParameterDefinition" => {
                    raw_value.element("ParameterDefinition", value, path)?;
                }
                "valueRelatedArtifact" => {
                    raw_value.value("RelatedArtifact", value, path)?;
                }
                "_valueRelatedArtifact" => {
                    raw_value.element("RelatedArtifact", value, path)?;
                }
                "valueTriggerDefinition" => {
                    raw_value.value("TriggerDefinition", value, path)?;
                }
                "_valueTriggerDefinition" => {
                    raw_value.element("TriggerDefinition", value, path)?;
                }
                "valueUsageContext" => {
                    raw_value.value("UsageContext", value, path)?;
                }
                "_valueUsageContext" => {
                    raw_value.element("UsageContext", value, path)?;
                }
                "valueDosage" => {
                    raw_value.value("Dosage", value, path)?;
                }
                "_valueDosage" => {
                    raw_value.element("Dosage", value, path)?;
                }
                "valueMeta" => {
                    raw_value.value("Meta", value, path)?;
                }
                "_valueMeta" => {
                    raw_value.element("Meta", value, path)?;
                }
                other => {
                    return path.with(other, |path| {
                        Err(path.error(super::super::codec::DecodeErrorKind::UnknownProperty))
                    });
                }
            }
        }
        let field_id = raw_id
            .map(|value| {
                path.with("id", |path| {
                    let value = super::super::codec::expect_single(value, path)?;
                    super::super::codec::expect_string(value, path)
                })
            })
            .transpose()?;
        let mut field_extension = Vec::new();
        if let Some(raw) = raw_extension {
            for (index, value) in super::super::codec::expect_array(raw, path)?
                .iter()
                .enumerate()
            {
                field_extension.push(path.with_index("extension", index, |path| {
                    super::super::codec::Json::from_json(
                        super::super::codec::expect_object(value, path)?,
                        path,
                    )
                })?);
            }
        }
        let field_url = path.with("url", |path| {
            let value = raw_url
                .ok_or_else(|| path.error(super::super::codec::DecodeErrorKind::MissingProperty))?;
            let value = super::super::codec::expect_single(value, path)?;
            super::super::codec::expect_string(value, path)
        })?;
        let field_value = match raw_value.suffix {
            None => None,
            Some(suffix) => Some(path.with("value", |path| {
                ExtensionValue::from_json_parts(suffix, raw_value.value, raw_value.element, path)
            })?),
        };
        Ok(Self {
            id: field_id,
            extension: field_extension,
            url: field_url,
            value: field_value,
        })
    }
}

impl serde::Serialize for Extension {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        let mut map = serde::Serializer::serialize_map(serializer, None)?;
        match &self.value {
            Some(ExtensionValue::Base64Binary(inner)) => {
                super::super::codec::element_entry(&mut map, "_valueBase64Binary", inner)?;
            }
            Some(ExtensionValue::Boolean(inner)) => {
                super::super::codec::element_entry(&mut map, "_valueBoolean", inner)?;
            }
            Some(ExtensionValue::Canonical(inner)) => {
                super::super::codec::element_entry(&mut map, "_valueCanonical", inner)?;
            }
            Some(ExtensionValue::Code(inner)) => {
                super::super::codec::element_entry(&mut map, "_valueCode", inner)?;
            }
            Some(ExtensionValue::Date(inner)) => {
                super::super::codec::element_entry(&mut map, "_valueDate", inner)?;
            }
            Some(ExtensionValue::DateTime(inner)) => {
                super::super::codec::element_entry(&mut map, "_valueDateTime", inner)?;
            }
            Some(ExtensionValue::Decimal(inner)) => {
                super::super::codec::element_entry(&mut map, "_valueDecimal", inner)?;
            }
            Some(ExtensionValue::Id(inner)) => {
                super::super::codec::element_entry(&mut map, "_valueId", inner)?;
            }
            Some(ExtensionValue::Instant(inner)) => {
                super::super::codec::element_entry(&mut map, "_valueInstant", inner)?;
            }
            Some(ExtensionValue::Integer(inner)) => {
                super::super::codec::element_entry(&mut map, "_valueInteger", inner)?;
            }
            Some(ExtensionValue::Markdown(inner)) => {
                super::super::codec::element_entry(&mut map, "_valueMarkdown", inner)?;
            }
            Some(ExtensionValue::Oid(inner)) => {
                super::super::codec::element_entry(&mut map, "_valueOid", inner)?;
            }
            Some(ExtensionValue::PositiveInt(inner)) => {
                super::super::codec::element_entry(&mut map, "_valuePositiveInt", inner)?;
            }
            Some(ExtensionValue::String(inner)) => {
                super::super::codec::element_entry(&mut map, "_valueString", inner)?;
            }
            Some(ExtensionValue::Time(inner)) => {
                super::super::codec::element_entry(&mut map, "_valueTime", inner)?;
            }
            Some(ExtensionValue::UnsignedInt(inner)) => {
                super::super::codec::element_entry(&mut map, "_valueUnsignedInt", inner)?;
            }
            Some(ExtensionValue::Uri(inner)) => {
                super::super::codec::element_entry(&mut map, "_valueUri", inner)?;
            }
            Some(ExtensionValue::Url(inner)) => {
                super::super::codec::element_entry(&mut map, "_valueUrl", inner)?;
            }
            Some(ExtensionValue::Uuid(inner)) => {
                super::super::codec::element_entry(&mut map, "_valueUuid", inner)?;
            }
            _ => {}
        }
        if !self.extension.is_empty() {
            serde::ser::SerializeMap::serialize_entry(&mut map, "extension", &self.extension)?;
        }
        if let Some(v) = &self.id {
            serde::ser::SerializeMap::serialize_entry(&mut map, "id", v)?;
        }
        serde::ser::SerializeMap::serialize_entry(&mut map, "url", &self.url)?;
        match &self.value {
            Some(ExtensionValue::Address(inner)) => {
                serde::ser::SerializeMap::serialize_entry(
                    &mut map,
                    "valueAddress",
                    inner.as_ref(),
                )?;
            }
            Some(ExtensionValue::Age(inner)) => {
                serde::ser::SerializeMap::serialize_entry(&mut map, "valueAge", inner.as_ref())?;
            }
            Some(ExtensionValue::Annotation(inner)) => {
                serde::ser::SerializeMap::serialize_entry(
                    &mut map,
                    "valueAnnotation",
                    inner.as_ref(),
                )?;
            }
            Some(ExtensionValue::Attachment(inner)) => {
                serde::ser::SerializeMap::serialize_entry(
                    &mut map,
                    "valueAttachment",
                    inner.as_ref(),
                )?;
            }
            Some(ExtensionValue::Base64Binary(inner)) => {
                super::super::codec::value_entry(&mut map, "valueBase64Binary", inner)?;
            }
            Some(ExtensionValue::Boolean(inner)) => {
                super::super::codec::value_entry(&mut map, "valueBoolean", inner)?;
            }
            Some(ExtensionValue::Canonical(inner)) => {
                super::super::codec::value_entry(&mut map, "valueCanonical", inner)?;
            }
            Some(ExtensionValue::Code(inner)) => {
                super::super::codec::value_entry(&mut map, "valueCode", inner)?;
            }
            Some(ExtensionValue::CodeableConcept(inner)) => {
                serde::ser::SerializeMap::serialize_entry(
                    &mut map,
                    "valueCodeableConcept",
                    inner.as_ref(),
                )?;
            }
            Some(ExtensionValue::Coding(inner)) => {
                serde::ser::SerializeMap::serialize_entry(&mut map, "valueCoding", inner.as_ref())?;
            }
            Some(ExtensionValue::ContactDetail(inner)) => {
                serde::ser::SerializeMap::serialize_entry(
                    &mut map,
                    "valueContactDetail",
                    inner.as_ref(),
                )?;
            }
            Some(ExtensionValue::ContactPoint(inner)) => {
                serde::ser::SerializeMap::serialize_entry(
                    &mut map,
                    "valueContactPoint",
                    inner.as_ref(),
                )?;
            }
            Some(ExtensionValue::Contributor(inner)) => {
                serde::ser::SerializeMap::serialize_entry(
                    &mut map,
                    "valueContributor",
                    inner.as_ref(),
                )?;
            }
            Some(ExtensionValue::Count(inner)) => {
                serde::ser::SerializeMap::serialize_entry(&mut map, "valueCount", inner.as_ref())?;
            }
            Some(ExtensionValue::DataRequirement(inner)) => {
                serde::ser::SerializeMap::serialize_entry(
                    &mut map,
                    "valueDataRequirement",
                    inner.as_ref(),
                )?;
            }
            Some(ExtensionValue::Date(inner)) => {
                super::super::codec::value_entry(&mut map, "valueDate", inner)?;
            }
            Some(ExtensionValue::DateTime(inner)) => {
                super::super::codec::value_entry(&mut map, "valueDateTime", inner)?;
            }
            Some(ExtensionValue::Decimal(inner)) => {
                super::super::codec::value_entry(&mut map, "valueDecimal", inner)?;
            }
            Some(ExtensionValue::Distance(inner)) => {
                serde::ser::SerializeMap::serialize_entry(
                    &mut map,
                    "valueDistance",
                    inner.as_ref(),
                )?;
            }
            Some(ExtensionValue::Dosage(inner)) => {
                serde::ser::SerializeMap::serialize_entry(&mut map, "valueDosage", inner.as_ref())?;
            }
            Some(ExtensionValue::Duration(inner)) => {
                serde::ser::SerializeMap::serialize_entry(
                    &mut map,
                    "valueDuration",
                    inner.as_ref(),
                )?;
            }
            Some(ExtensionValue::Expression(inner)) => {
                serde::ser::SerializeMap::serialize_entry(
                    &mut map,
                    "valueExpression",
                    inner.as_ref(),
                )?;
            }
            Some(ExtensionValue::HumanName(inner)) => {
                serde::ser::SerializeMap::serialize_entry(
                    &mut map,
                    "valueHumanName",
                    inner.as_ref(),
                )?;
            }
            Some(ExtensionValue::Id(inner)) => {
                super::super::codec::value_entry(&mut map, "valueId", inner)?;
            }
            Some(ExtensionValue::Identifier(inner)) => {
                serde::ser::SerializeMap::serialize_entry(
                    &mut map,
                    "valueIdentifier",
                    inner.as_ref(),
                )?;
            }
            Some(ExtensionValue::Instant(inner)) => {
                super::super::codec::value_entry(&mut map, "valueInstant", inner)?;
            }
            Some(ExtensionValue::Integer(inner)) => {
                super::super::codec::value_entry(&mut map, "valueInteger", inner)?;
            }
            Some(ExtensionValue::Markdown(inner)) => {
                super::super::codec::value_entry(&mut map, "valueMarkdown", inner)?;
            }
            Some(ExtensionValue::Meta(inner)) => {
                serde::ser::SerializeMap::serialize_entry(&mut map, "valueMeta", inner.as_ref())?;
            }
            Some(ExtensionValue::Money(inner)) => {
                serde::ser::SerializeMap::serialize_entry(&mut map, "valueMoney", inner.as_ref())?;
            }
            Some(ExtensionValue::Oid(inner)) => {
                super::super::codec::value_entry(&mut map, "valueOid", inner)?;
            }
            Some(ExtensionValue::ParameterDefinition(inner)) => {
                serde::ser::SerializeMap::serialize_entry(
                    &mut map,
                    "valueParameterDefinition",
                    inner.as_ref(),
                )?;
            }
            Some(ExtensionValue::Period(inner)) => {
                serde::ser::SerializeMap::serialize_entry(&mut map, "valuePeriod", inner.as_ref())?;
            }
            Some(ExtensionValue::PositiveInt(inner)) => {
                super::super::codec::value_entry(&mut map, "valuePositiveInt", inner)?;
            }
            Some(ExtensionValue::Quantity(inner)) => {
                serde::ser::SerializeMap::serialize_entry(
                    &mut map,
                    "valueQuantity",
                    inner.as_ref(),
                )?;
            }
            Some(ExtensionValue::Range(inner)) => {
                serde::ser::SerializeMap::serialize_entry(&mut map, "valueRange", inner.as_ref())?;
            }
            Some(ExtensionValue::Ratio(inner)) => {
                serde::ser::SerializeMap::serialize_entry(&mut map, "valueRatio", inner.as_ref())?;
            }
            Some(ExtensionValue::Reference(inner)) => {
                serde::ser::SerializeMap::serialize_entry(
                    &mut map,
                    "valueReference",
                    inner.as_ref(),
                )?;
            }
            Some(ExtensionValue::RelatedArtifact(inner)) => {
                serde::ser::SerializeMap::serialize_entry(
                    &mut map,
                    "valueRelatedArtifact",
                    inner.as_ref(),
                )?;
            }
            Some(ExtensionValue::SampledData(inner)) => {
                serde::ser::SerializeMap::serialize_entry(
                    &mut map,
                    "valueSampledData",
                    inner.as_ref(),
                )?;
            }
            Some(ExtensionValue::Signature(inner)) => {
                serde::ser::SerializeMap::serialize_entry(
                    &mut map,
                    "valueSignature",
                    inner.as_ref(),
                )?;
            }
            Some(ExtensionValue::String(inner)) => {
                super::super::codec::value_entry(&mut map, "valueString", inner)?;
            }
            Some(ExtensionValue::Time(inner)) => {
                super::super::codec::value_entry(&mut map, "valueTime", inner)?;
            }
            Some(ExtensionValue::Timing(inner)) => {
                serde::ser::SerializeMap::serialize_entry(&mut map, "valueTiming", inner.as_ref())?;
            }
            Some(ExtensionValue::TriggerDefinition(inner)) => {
                serde::ser::SerializeMap::serialize_entry(
                    &mut map,
                    "valueTriggerDefinition",
                    inner.as_ref(),
                )?;
            }
            Some(ExtensionValue::UnsignedInt(inner)) => {
                super::super::codec::value_entry(&mut map, "valueUnsignedInt", inner)?;
            }
            Some(ExtensionValue::Uri(inner)) => {
                super::super::codec::value_entry(&mut map, "valueUri", inner)?;
            }
            Some(ExtensionValue::Url(inner)) => {
                super::super::codec::value_entry(&mut map, "valueUrl", inner)?;
            }
            Some(ExtensionValue::UsageContext(inner)) => {
                serde::ser::SerializeMap::serialize_entry(
                    &mut map,
                    "valueUsageContext",
                    inner.as_ref(),
                )?;
            }
            Some(ExtensionValue::Uuid(inner)) => {
                super::super::codec::value_entry(&mut map, "valueUuid", inner)?;
            }
            None => {}
        }
        serde::ser::SerializeMap::end(map)
    }
}

impl<'de> serde::Deserialize<'de> for Extension {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = serde_json::Value::deserialize(deserializer)?;
        let mut path = super::super::codec::Path::root("Extension");
        let object =
            super::super::codec::expect_object(&value, &path).map_err(serde::de::Error::custom)?;
        super::super::codec::Json::from_json(object, &mut path).map_err(serde::de::Error::custom)
    }
}

/// The \`value\[x\]\` choice of \`Extension\`.
///
/// Value of extension - must be one of a constrained set of the data types (see
/// \[Extensibility\](extensibility.html) for a list).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ExtensionValue {
    /// The `base64Binary` form.
    Base64Binary(super::primitives::Base64Binary),
    /// The `boolean` form.
    Boolean(super::primitives::Boolean),
    /// The `canonical` form.
    Canonical(super::primitives::Canonical),
    /// The `code` form.
    Code(super::primitives::Code),
    /// The `date` form.
    Date(super::primitives::Date),
    /// The `dateTime` form.
    DateTime(super::primitives::DateTime),
    /// The `decimal` form.
    Decimal(super::primitives::Decimal),
    /// The `id` form.
    Id(super::primitives::Id),
    /// The `instant` form.
    Instant(super::primitives::Instant),
    /// The `integer` form.
    Integer(super::primitives::Integer),
    /// The `markdown` form.
    Markdown(super::primitives::Markdown),
    /// The `oid` form.
    Oid(super::primitives::Oid),
    /// The `positiveInt` form.
    PositiveInt(super::primitives::PositiveInt),
    /// The `string` form.
    String(super::primitives::String),
    /// The `time` form.
    Time(super::primitives::Time),
    /// The `unsignedInt` form.
    UnsignedInt(super::primitives::UnsignedInt),
    /// The `uri` form.
    Uri(super::primitives::Uri),
    /// The `url` form.
    Url(super::primitives::Url),
    /// The `uuid` form.
    Uuid(super::primitives::Uuid),
    /// The `Address` form.
    Address(Box<super::address::Address>),
    /// The `Age` form.
    Age(Box<super::age::Age>),
    /// The `Annotation` form.
    Annotation(Box<super::annotation::Annotation>),
    /// The `Attachment` form.
    Attachment(Box<super::attachment::Attachment>),
    /// The `CodeableConcept` form.
    CodeableConcept(Box<super::codeable_concept::CodeableConcept>),
    /// The `Coding` form.
    Coding(Box<super::coding::Coding>),
    /// The `ContactPoint` form.
    ContactPoint(Box<super::contact_point::ContactPoint>),
    /// The `Count` form.
    Count(Box<super::count::Count>),
    /// The `Distance` form.
    Distance(Box<super::distance::Distance>),
    /// The `Duration` form.
    Duration(Box<super::duration::Duration>),
    /// The `HumanName` form.
    HumanName(Box<super::human_name::HumanName>),
    /// The `Identifier` form.
    Identifier(Box<super::identifier::Identifier>),
    /// The `Money` form.
    Money(Box<super::money::Money>),
    /// The `Period` form.
    Period(Box<super::period::Period>),
    /// The `Quantity` form.
    Quantity(Box<super::quantity::Quantity>),
    /// The `Range` form.
    Range(Box<super::range::Range>),
    /// The `Ratio` form.
    Ratio(Box<super::ratio::Ratio>),
    /// The `Reference` form.
    Reference(Box<super::reference::Reference>),
    /// The `SampledData` form.
    SampledData(Box<super::sampled_data::SampledData>),
    /// The `Signature` form.
    Signature(Box<super::signature::Signature>),
    /// The `Timing` form.
    Timing(Box<super::timing::Timing>),
    /// The `ContactDetail` form.
    ContactDetail(Box<super::contact_detail::ContactDetail>),
    /// The `Contributor` form.
    Contributor(Box<super::contributor::Contributor>),
    /// The `DataRequirement` form.
    DataRequirement(Box<super::data_requirement::DataRequirement>),
    /// The `Expression` form.
    Expression(Box<super::expression::Expression>),
    /// The `ParameterDefinition` form.
    ParameterDefinition(Box<super::parameter_definition::ParameterDefinition>),
    /// The `RelatedArtifact` form.
    RelatedArtifact(Box<super::related_artifact::RelatedArtifact>),
    /// The `TriggerDefinition` form.
    TriggerDefinition(Box<super::trigger_definition::TriggerDefinition>),
    /// The `UsageContext` form.
    UsageContext(Box<super::usage_context::UsageContext>),
    /// The `Dosage` form.
    Dosage(Box<super::dosage::Dosage>),
    /// The `Meta` form.
    Meta(Box<super::meta::Meta>),
}

impl ExtensionValue {
    /// The key suffix, the value part, and the `_name` part of this form.
    ///
    /// # Errors
    ///
    /// Returns [`super::super::codec::EncodeError`] when a held value has no JSON form.
    pub fn to_json_parts(
        &self,
    ) -> Result<
        (
            &'static str,
            Option<serde_json::Value>,
            Option<serde_json::Value>,
        ),
        super::super::codec::EncodeError,
    > {
        match self {
            Self::Base64Binary(inner) => Ok((
                "Base64Binary",
                super::super::codec::Primitive::value_json(inner)?,
                super::super::codec::Primitive::element_json(inner)?,
            )),
            Self::Boolean(inner) => Ok((
                "Boolean",
                super::super::codec::Primitive::value_json(inner)?,
                super::super::codec::Primitive::element_json(inner)?,
            )),
            Self::Canonical(inner) => Ok((
                "Canonical",
                super::super::codec::Primitive::value_json(inner)?,
                super::super::codec::Primitive::element_json(inner)?,
            )),
            Self::Code(inner) => Ok((
                "Code",
                super::super::codec::Primitive::value_json(inner)?,
                super::super::codec::Primitive::element_json(inner)?,
            )),
            Self::Date(inner) => Ok((
                "Date",
                super::super::codec::Primitive::value_json(inner)?,
                super::super::codec::Primitive::element_json(inner)?,
            )),
            Self::DateTime(inner) => Ok((
                "DateTime",
                super::super::codec::Primitive::value_json(inner)?,
                super::super::codec::Primitive::element_json(inner)?,
            )),
            Self::Decimal(inner) => Ok((
                "Decimal",
                super::super::codec::Primitive::value_json(inner)?,
                super::super::codec::Primitive::element_json(inner)?,
            )),
            Self::Id(inner) => Ok((
                "Id",
                super::super::codec::Primitive::value_json(inner)?,
                super::super::codec::Primitive::element_json(inner)?,
            )),
            Self::Instant(inner) => Ok((
                "Instant",
                super::super::codec::Primitive::value_json(inner)?,
                super::super::codec::Primitive::element_json(inner)?,
            )),
            Self::Integer(inner) => Ok((
                "Integer",
                super::super::codec::Primitive::value_json(inner)?,
                super::super::codec::Primitive::element_json(inner)?,
            )),
            Self::Markdown(inner) => Ok((
                "Markdown",
                super::super::codec::Primitive::value_json(inner)?,
                super::super::codec::Primitive::element_json(inner)?,
            )),
            Self::Oid(inner) => Ok((
                "Oid",
                super::super::codec::Primitive::value_json(inner)?,
                super::super::codec::Primitive::element_json(inner)?,
            )),
            Self::PositiveInt(inner) => Ok((
                "PositiveInt",
                super::super::codec::Primitive::value_json(inner)?,
                super::super::codec::Primitive::element_json(inner)?,
            )),
            Self::String(inner) => Ok((
                "String",
                super::super::codec::Primitive::value_json(inner)?,
                super::super::codec::Primitive::element_json(inner)?,
            )),
            Self::Time(inner) => Ok((
                "Time",
                super::super::codec::Primitive::value_json(inner)?,
                super::super::codec::Primitive::element_json(inner)?,
            )),
            Self::UnsignedInt(inner) => Ok((
                "UnsignedInt",
                super::super::codec::Primitive::value_json(inner)?,
                super::super::codec::Primitive::element_json(inner)?,
            )),
            Self::Uri(inner) => Ok((
                "Uri",
                super::super::codec::Primitive::value_json(inner)?,
                super::super::codec::Primitive::element_json(inner)?,
            )),
            Self::Url(inner) => Ok((
                "Url",
                super::super::codec::Primitive::value_json(inner)?,
                super::super::codec::Primitive::element_json(inner)?,
            )),
            Self::Uuid(inner) => Ok((
                "Uuid",
                super::super::codec::Primitive::value_json(inner)?,
                super::super::codec::Primitive::element_json(inner)?,
            )),
            Self::Address(inner) => Ok((
                "Address",
                Some(serde_json::Value::Object(
                    super::super::codec::Json::to_json(inner.as_ref())?,
                )),
                None,
            )),
            Self::Age(inner) => Ok((
                "Age",
                Some(serde_json::Value::Object(
                    super::super::codec::Json::to_json(inner.as_ref())?,
                )),
                None,
            )),
            Self::Annotation(inner) => Ok((
                "Annotation",
                Some(serde_json::Value::Object(
                    super::super::codec::Json::to_json(inner.as_ref())?,
                )),
                None,
            )),
            Self::Attachment(inner) => Ok((
                "Attachment",
                Some(serde_json::Value::Object(
                    super::super::codec::Json::to_json(inner.as_ref())?,
                )),
                None,
            )),
            Self::CodeableConcept(inner) => Ok((
                "CodeableConcept",
                Some(serde_json::Value::Object(
                    super::super::codec::Json::to_json(inner.as_ref())?,
                )),
                None,
            )),
            Self::Coding(inner) => Ok((
                "Coding",
                Some(serde_json::Value::Object(
                    super::super::codec::Json::to_json(inner.as_ref())?,
                )),
                None,
            )),
            Self::ContactPoint(inner) => Ok((
                "ContactPoint",
                Some(serde_json::Value::Object(
                    super::super::codec::Json::to_json(inner.as_ref())?,
                )),
                None,
            )),
            Self::Count(inner) => Ok((
                "Count",
                Some(serde_json::Value::Object(
                    super::super::codec::Json::to_json(inner.as_ref())?,
                )),
                None,
            )),
            Self::Distance(inner) => Ok((
                "Distance",
                Some(serde_json::Value::Object(
                    super::super::codec::Json::to_json(inner.as_ref())?,
                )),
                None,
            )),
            Self::Duration(inner) => Ok((
                "Duration",
                Some(serde_json::Value::Object(
                    super::super::codec::Json::to_json(inner.as_ref())?,
                )),
                None,
            )),
            Self::HumanName(inner) => Ok((
                "HumanName",
                Some(serde_json::Value::Object(
                    super::super::codec::Json::to_json(inner.as_ref())?,
                )),
                None,
            )),
            Self::Identifier(inner) => Ok((
                "Identifier",
                Some(serde_json::Value::Object(
                    super::super::codec::Json::to_json(inner.as_ref())?,
                )),
                None,
            )),
            Self::Money(inner) => Ok((
                "Money",
                Some(serde_json::Value::Object(
                    super::super::codec::Json::to_json(inner.as_ref())?,
                )),
                None,
            )),
            Self::Period(inner) => Ok((
                "Period",
                Some(serde_json::Value::Object(
                    super::super::codec::Json::to_json(inner.as_ref())?,
                )),
                None,
            )),
            Self::Quantity(inner) => Ok((
                "Quantity",
                Some(serde_json::Value::Object(
                    super::super::codec::Json::to_json(inner.as_ref())?,
                )),
                None,
            )),
            Self::Range(inner) => Ok((
                "Range",
                Some(serde_json::Value::Object(
                    super::super::codec::Json::to_json(inner.as_ref())?,
                )),
                None,
            )),
            Self::Ratio(inner) => Ok((
                "Ratio",
                Some(serde_json::Value::Object(
                    super::super::codec::Json::to_json(inner.as_ref())?,
                )),
                None,
            )),
            Self::Reference(inner) => Ok((
                "Reference",
                Some(serde_json::Value::Object(
                    super::super::codec::Json::to_json(inner.as_ref())?,
                )),
                None,
            )),
            Self::SampledData(inner) => Ok((
                "SampledData",
                Some(serde_json::Value::Object(
                    super::super::codec::Json::to_json(inner.as_ref())?,
                )),
                None,
            )),
            Self::Signature(inner) => Ok((
                "Signature",
                Some(serde_json::Value::Object(
                    super::super::codec::Json::to_json(inner.as_ref())?,
                )),
                None,
            )),
            Self::Timing(inner) => Ok((
                "Timing",
                Some(serde_json::Value::Object(
                    super::super::codec::Json::to_json(inner.as_ref())?,
                )),
                None,
            )),
            Self::ContactDetail(inner) => Ok((
                "ContactDetail",
                Some(serde_json::Value::Object(
                    super::super::codec::Json::to_json(inner.as_ref())?,
                )),
                None,
            )),
            Self::Contributor(inner) => Ok((
                "Contributor",
                Some(serde_json::Value::Object(
                    super::super::codec::Json::to_json(inner.as_ref())?,
                )),
                None,
            )),
            Self::DataRequirement(inner) => Ok((
                "DataRequirement",
                Some(serde_json::Value::Object(
                    super::super::codec::Json::to_json(inner.as_ref())?,
                )),
                None,
            )),
            Self::Expression(inner) => Ok((
                "Expression",
                Some(serde_json::Value::Object(
                    super::super::codec::Json::to_json(inner.as_ref())?,
                )),
                None,
            )),
            Self::ParameterDefinition(inner) => Ok((
                "ParameterDefinition",
                Some(serde_json::Value::Object(
                    super::super::codec::Json::to_json(inner.as_ref())?,
                )),
                None,
            )),
            Self::RelatedArtifact(inner) => Ok((
                "RelatedArtifact",
                Some(serde_json::Value::Object(
                    super::super::codec::Json::to_json(inner.as_ref())?,
                )),
                None,
            )),
            Self::TriggerDefinition(inner) => Ok((
                "TriggerDefinition",
                Some(serde_json::Value::Object(
                    super::super::codec::Json::to_json(inner.as_ref())?,
                )),
                None,
            )),
            Self::UsageContext(inner) => Ok((
                "UsageContext",
                Some(serde_json::Value::Object(
                    super::super::codec::Json::to_json(inner.as_ref())?,
                )),
                None,
            )),
            Self::Dosage(inner) => Ok((
                "Dosage",
                Some(serde_json::Value::Object(
                    super::super::codec::Json::to_json(inner.as_ref())?,
                )),
                None,
            )),
            Self::Meta(inner) => Ok((
                "Meta",
                Some(serde_json::Value::Object(
                    super::super::codec::Json::to_json(inner.as_ref())?,
                )),
                None,
            )),
        }
    }

    /// Decodes the form named by `suffix` from its value and `_name` parts.
    ///
    /// # Errors
    ///
    /// Returns [`super::super::codec::DecodeError`] for an unknown suffix or a malformed part.
    pub fn from_json_parts(
        suffix: &str,
        value: Option<&serde_json::Value>,
        element: Option<&serde_json::Value>,
        path: &mut super::super::codec::Path,
    ) -> Result<Self, super::super::codec::DecodeError> {
        match suffix {
            "Base64Binary" => Ok(Self::Base64Binary(
                super::super::codec::Primitive::from_json_parts(value, element, path)?,
            )),
            "Boolean" => Ok(Self::Boolean(
                super::super::codec::Primitive::from_json_parts(value, element, path)?,
            )),
            "Canonical" => Ok(Self::Canonical(
                super::super::codec::Primitive::from_json_parts(value, element, path)?,
            )),
            "Code" => Ok(Self::Code(super::super::codec::Primitive::from_json_parts(
                value, element, path,
            )?)),
            "Date" => Ok(Self::Date(super::super::codec::Primitive::from_json_parts(
                value, element, path,
            )?)),
            "DateTime" => Ok(Self::DateTime(
                super::super::codec::Primitive::from_json_parts(value, element, path)?,
            )),
            "Decimal" => Ok(Self::Decimal(
                super::super::codec::Primitive::from_json_parts(value, element, path)?,
            )),
            "Id" => Ok(Self::Id(super::super::codec::Primitive::from_json_parts(
                value, element, path,
            )?)),
            "Instant" => Ok(Self::Instant(
                super::super::codec::Primitive::from_json_parts(value, element, path)?,
            )),
            "Integer" => Ok(Self::Integer(
                super::super::codec::Primitive::from_json_parts(value, element, path)?,
            )),
            "Markdown" => Ok(Self::Markdown(
                super::super::codec::Primitive::from_json_parts(value, element, path)?,
            )),
            "Oid" => Ok(Self::Oid(super::super::codec::Primitive::from_json_parts(
                value, element, path,
            )?)),
            "PositiveInt" => Ok(Self::PositiveInt(
                super::super::codec::Primitive::from_json_parts(value, element, path)?,
            )),
            "String" => Ok(Self::String(
                super::super::codec::Primitive::from_json_parts(value, element, path)?,
            )),
            "Time" => Ok(Self::Time(super::super::codec::Primitive::from_json_parts(
                value, element, path,
            )?)),
            "UnsignedInt" => Ok(Self::UnsignedInt(
                super::super::codec::Primitive::from_json_parts(value, element, path)?,
            )),
            "Uri" => Ok(Self::Uri(super::super::codec::Primitive::from_json_parts(
                value, element, path,
            )?)),
            "Url" => Ok(Self::Url(super::super::codec::Primitive::from_json_parts(
                value, element, path,
            )?)),
            "Uuid" => Ok(Self::Uuid(super::super::codec::Primitive::from_json_parts(
                value, element, path,
            )?)),
            "Address" => {
                if element.is_some() {
                    return Err(path.error(super::super::codec::DecodeErrorKind::WrongType {
                        expected: "no underscore form for a complex type",
                    }));
                }
                let value = value.ok_or_else(|| {
                    path.error(super::super::codec::DecodeErrorKind::MissingProperty)
                })?;
                let inner = super::super::codec::Json::from_json(
                    super::super::codec::expect_object(
                        super::super::codec::expect_single(value, path)?,
                        path,
                    )?,
                    path,
                )?;
                Ok(Self::Address(Box::new(inner)))
            }
            "Age" => {
                if element.is_some() {
                    return Err(path.error(super::super::codec::DecodeErrorKind::WrongType {
                        expected: "no underscore form for a complex type",
                    }));
                }
                let value = value.ok_or_else(|| {
                    path.error(super::super::codec::DecodeErrorKind::MissingProperty)
                })?;
                let inner = super::super::codec::Json::from_json(
                    super::super::codec::expect_object(
                        super::super::codec::expect_single(value, path)?,
                        path,
                    )?,
                    path,
                )?;
                Ok(Self::Age(Box::new(inner)))
            }
            "Annotation" => {
                if element.is_some() {
                    return Err(path.error(super::super::codec::DecodeErrorKind::WrongType {
                        expected: "no underscore form for a complex type",
                    }));
                }
                let value = value.ok_or_else(|| {
                    path.error(super::super::codec::DecodeErrorKind::MissingProperty)
                })?;
                let inner = super::super::codec::Json::from_json(
                    super::super::codec::expect_object(
                        super::super::codec::expect_single(value, path)?,
                        path,
                    )?,
                    path,
                )?;
                Ok(Self::Annotation(Box::new(inner)))
            }
            "Attachment" => {
                if element.is_some() {
                    return Err(path.error(super::super::codec::DecodeErrorKind::WrongType {
                        expected: "no underscore form for a complex type",
                    }));
                }
                let value = value.ok_or_else(|| {
                    path.error(super::super::codec::DecodeErrorKind::MissingProperty)
                })?;
                let inner = super::super::codec::Json::from_json(
                    super::super::codec::expect_object(
                        super::super::codec::expect_single(value, path)?,
                        path,
                    )?,
                    path,
                )?;
                Ok(Self::Attachment(Box::new(inner)))
            }
            "CodeableConcept" => {
                if element.is_some() {
                    return Err(path.error(super::super::codec::DecodeErrorKind::WrongType {
                        expected: "no underscore form for a complex type",
                    }));
                }
                let value = value.ok_or_else(|| {
                    path.error(super::super::codec::DecodeErrorKind::MissingProperty)
                })?;
                let inner = super::super::codec::Json::from_json(
                    super::super::codec::expect_object(
                        super::super::codec::expect_single(value, path)?,
                        path,
                    )?,
                    path,
                )?;
                Ok(Self::CodeableConcept(Box::new(inner)))
            }
            "Coding" => {
                if element.is_some() {
                    return Err(path.error(super::super::codec::DecodeErrorKind::WrongType {
                        expected: "no underscore form for a complex type",
                    }));
                }
                let value = value.ok_or_else(|| {
                    path.error(super::super::codec::DecodeErrorKind::MissingProperty)
                })?;
                let inner = super::super::codec::Json::from_json(
                    super::super::codec::expect_object(
                        super::super::codec::expect_single(value, path)?,
                        path,
                    )?,
                    path,
                )?;
                Ok(Self::Coding(Box::new(inner)))
            }
            "ContactPoint" => {
                if element.is_some() {
                    return Err(path.error(super::super::codec::DecodeErrorKind::WrongType {
                        expected: "no underscore form for a complex type",
                    }));
                }
                let value = value.ok_or_else(|| {
                    path.error(super::super::codec::DecodeErrorKind::MissingProperty)
                })?;
                let inner = super::super::codec::Json::from_json(
                    super::super::codec::expect_object(
                        super::super::codec::expect_single(value, path)?,
                        path,
                    )?,
                    path,
                )?;
                Ok(Self::ContactPoint(Box::new(inner)))
            }
            "Count" => {
                if element.is_some() {
                    return Err(path.error(super::super::codec::DecodeErrorKind::WrongType {
                        expected: "no underscore form for a complex type",
                    }));
                }
                let value = value.ok_or_else(|| {
                    path.error(super::super::codec::DecodeErrorKind::MissingProperty)
                })?;
                let inner = super::super::codec::Json::from_json(
                    super::super::codec::expect_object(
                        super::super::codec::expect_single(value, path)?,
                        path,
                    )?,
                    path,
                )?;
                Ok(Self::Count(Box::new(inner)))
            }
            "Distance" => {
                if element.is_some() {
                    return Err(path.error(super::super::codec::DecodeErrorKind::WrongType {
                        expected: "no underscore form for a complex type",
                    }));
                }
                let value = value.ok_or_else(|| {
                    path.error(super::super::codec::DecodeErrorKind::MissingProperty)
                })?;
                let inner = super::super::codec::Json::from_json(
                    super::super::codec::expect_object(
                        super::super::codec::expect_single(value, path)?,
                        path,
                    )?,
                    path,
                )?;
                Ok(Self::Distance(Box::new(inner)))
            }
            "Duration" => {
                if element.is_some() {
                    return Err(path.error(super::super::codec::DecodeErrorKind::WrongType {
                        expected: "no underscore form for a complex type",
                    }));
                }
                let value = value.ok_or_else(|| {
                    path.error(super::super::codec::DecodeErrorKind::MissingProperty)
                })?;
                let inner = super::super::codec::Json::from_json(
                    super::super::codec::expect_object(
                        super::super::codec::expect_single(value, path)?,
                        path,
                    )?,
                    path,
                )?;
                Ok(Self::Duration(Box::new(inner)))
            }
            "HumanName" => {
                if element.is_some() {
                    return Err(path.error(super::super::codec::DecodeErrorKind::WrongType {
                        expected: "no underscore form for a complex type",
                    }));
                }
                let value = value.ok_or_else(|| {
                    path.error(super::super::codec::DecodeErrorKind::MissingProperty)
                })?;
                let inner = super::super::codec::Json::from_json(
                    super::super::codec::expect_object(
                        super::super::codec::expect_single(value, path)?,
                        path,
                    )?,
                    path,
                )?;
                Ok(Self::HumanName(Box::new(inner)))
            }
            "Identifier" => {
                if element.is_some() {
                    return Err(path.error(super::super::codec::DecodeErrorKind::WrongType {
                        expected: "no underscore form for a complex type",
                    }));
                }
                let value = value.ok_or_else(|| {
                    path.error(super::super::codec::DecodeErrorKind::MissingProperty)
                })?;
                let inner = super::super::codec::Json::from_json(
                    super::super::codec::expect_object(
                        super::super::codec::expect_single(value, path)?,
                        path,
                    )?,
                    path,
                )?;
                Ok(Self::Identifier(Box::new(inner)))
            }
            "Money" => {
                if element.is_some() {
                    return Err(path.error(super::super::codec::DecodeErrorKind::WrongType {
                        expected: "no underscore form for a complex type",
                    }));
                }
                let value = value.ok_or_else(|| {
                    path.error(super::super::codec::DecodeErrorKind::MissingProperty)
                })?;
                let inner = super::super::codec::Json::from_json(
                    super::super::codec::expect_object(
                        super::super::codec::expect_single(value, path)?,
                        path,
                    )?,
                    path,
                )?;
                Ok(Self::Money(Box::new(inner)))
            }
            "Period" => {
                if element.is_some() {
                    return Err(path.error(super::super::codec::DecodeErrorKind::WrongType {
                        expected: "no underscore form for a complex type",
                    }));
                }
                let value = value.ok_or_else(|| {
                    path.error(super::super::codec::DecodeErrorKind::MissingProperty)
                })?;
                let inner = super::super::codec::Json::from_json(
                    super::super::codec::expect_object(
                        super::super::codec::expect_single(value, path)?,
                        path,
                    )?,
                    path,
                )?;
                Ok(Self::Period(Box::new(inner)))
            }
            "Quantity" => {
                if element.is_some() {
                    return Err(path.error(super::super::codec::DecodeErrorKind::WrongType {
                        expected: "no underscore form for a complex type",
                    }));
                }
                let value = value.ok_or_else(|| {
                    path.error(super::super::codec::DecodeErrorKind::MissingProperty)
                })?;
                let inner = super::super::codec::Json::from_json(
                    super::super::codec::expect_object(
                        super::super::codec::expect_single(value, path)?,
                        path,
                    )?,
                    path,
                )?;
                Ok(Self::Quantity(Box::new(inner)))
            }
            "Range" => {
                if element.is_some() {
                    return Err(path.error(super::super::codec::DecodeErrorKind::WrongType {
                        expected: "no underscore form for a complex type",
                    }));
                }
                let value = value.ok_or_else(|| {
                    path.error(super::super::codec::DecodeErrorKind::MissingProperty)
                })?;
                let inner = super::super::codec::Json::from_json(
                    super::super::codec::expect_object(
                        super::super::codec::expect_single(value, path)?,
                        path,
                    )?,
                    path,
                )?;
                Ok(Self::Range(Box::new(inner)))
            }
            "Ratio" => {
                if element.is_some() {
                    return Err(path.error(super::super::codec::DecodeErrorKind::WrongType {
                        expected: "no underscore form for a complex type",
                    }));
                }
                let value = value.ok_or_else(|| {
                    path.error(super::super::codec::DecodeErrorKind::MissingProperty)
                })?;
                let inner = super::super::codec::Json::from_json(
                    super::super::codec::expect_object(
                        super::super::codec::expect_single(value, path)?,
                        path,
                    )?,
                    path,
                )?;
                Ok(Self::Ratio(Box::new(inner)))
            }
            "Reference" => {
                if element.is_some() {
                    return Err(path.error(super::super::codec::DecodeErrorKind::WrongType {
                        expected: "no underscore form for a complex type",
                    }));
                }
                let value = value.ok_or_else(|| {
                    path.error(super::super::codec::DecodeErrorKind::MissingProperty)
                })?;
                let inner = super::super::codec::Json::from_json(
                    super::super::codec::expect_object(
                        super::super::codec::expect_single(value, path)?,
                        path,
                    )?,
                    path,
                )?;
                Ok(Self::Reference(Box::new(inner)))
            }
            "SampledData" => {
                if element.is_some() {
                    return Err(path.error(super::super::codec::DecodeErrorKind::WrongType {
                        expected: "no underscore form for a complex type",
                    }));
                }
                let value = value.ok_or_else(|| {
                    path.error(super::super::codec::DecodeErrorKind::MissingProperty)
                })?;
                let inner = super::super::codec::Json::from_json(
                    super::super::codec::expect_object(
                        super::super::codec::expect_single(value, path)?,
                        path,
                    )?,
                    path,
                )?;
                Ok(Self::SampledData(Box::new(inner)))
            }
            "Signature" => {
                if element.is_some() {
                    return Err(path.error(super::super::codec::DecodeErrorKind::WrongType {
                        expected: "no underscore form for a complex type",
                    }));
                }
                let value = value.ok_or_else(|| {
                    path.error(super::super::codec::DecodeErrorKind::MissingProperty)
                })?;
                let inner = super::super::codec::Json::from_json(
                    super::super::codec::expect_object(
                        super::super::codec::expect_single(value, path)?,
                        path,
                    )?,
                    path,
                )?;
                Ok(Self::Signature(Box::new(inner)))
            }
            "Timing" => {
                if element.is_some() {
                    return Err(path.error(super::super::codec::DecodeErrorKind::WrongType {
                        expected: "no underscore form for a complex type",
                    }));
                }
                let value = value.ok_or_else(|| {
                    path.error(super::super::codec::DecodeErrorKind::MissingProperty)
                })?;
                let inner = super::super::codec::Json::from_json(
                    super::super::codec::expect_object(
                        super::super::codec::expect_single(value, path)?,
                        path,
                    )?,
                    path,
                )?;
                Ok(Self::Timing(Box::new(inner)))
            }
            "ContactDetail" => {
                if element.is_some() {
                    return Err(path.error(super::super::codec::DecodeErrorKind::WrongType {
                        expected: "no underscore form for a complex type",
                    }));
                }
                let value = value.ok_or_else(|| {
                    path.error(super::super::codec::DecodeErrorKind::MissingProperty)
                })?;
                let inner = super::super::codec::Json::from_json(
                    super::super::codec::expect_object(
                        super::super::codec::expect_single(value, path)?,
                        path,
                    )?,
                    path,
                )?;
                Ok(Self::ContactDetail(Box::new(inner)))
            }
            "Contributor" => {
                if element.is_some() {
                    return Err(path.error(super::super::codec::DecodeErrorKind::WrongType {
                        expected: "no underscore form for a complex type",
                    }));
                }
                let value = value.ok_or_else(|| {
                    path.error(super::super::codec::DecodeErrorKind::MissingProperty)
                })?;
                let inner = super::super::codec::Json::from_json(
                    super::super::codec::expect_object(
                        super::super::codec::expect_single(value, path)?,
                        path,
                    )?,
                    path,
                )?;
                Ok(Self::Contributor(Box::new(inner)))
            }
            "DataRequirement" => {
                if element.is_some() {
                    return Err(path.error(super::super::codec::DecodeErrorKind::WrongType {
                        expected: "no underscore form for a complex type",
                    }));
                }
                let value = value.ok_or_else(|| {
                    path.error(super::super::codec::DecodeErrorKind::MissingProperty)
                })?;
                let inner = super::super::codec::Json::from_json(
                    super::super::codec::expect_object(
                        super::super::codec::expect_single(value, path)?,
                        path,
                    )?,
                    path,
                )?;
                Ok(Self::DataRequirement(Box::new(inner)))
            }
            "Expression" => {
                if element.is_some() {
                    return Err(path.error(super::super::codec::DecodeErrorKind::WrongType {
                        expected: "no underscore form for a complex type",
                    }));
                }
                let value = value.ok_or_else(|| {
                    path.error(super::super::codec::DecodeErrorKind::MissingProperty)
                })?;
                let inner = super::super::codec::Json::from_json(
                    super::super::codec::expect_object(
                        super::super::codec::expect_single(value, path)?,
                        path,
                    )?,
                    path,
                )?;
                Ok(Self::Expression(Box::new(inner)))
            }
            "ParameterDefinition" => {
                if element.is_some() {
                    return Err(path.error(super::super::codec::DecodeErrorKind::WrongType {
                        expected: "no underscore form for a complex type",
                    }));
                }
                let value = value.ok_or_else(|| {
                    path.error(super::super::codec::DecodeErrorKind::MissingProperty)
                })?;
                let inner = super::super::codec::Json::from_json(
                    super::super::codec::expect_object(
                        super::super::codec::expect_single(value, path)?,
                        path,
                    )?,
                    path,
                )?;
                Ok(Self::ParameterDefinition(Box::new(inner)))
            }
            "RelatedArtifact" => {
                if element.is_some() {
                    return Err(path.error(super::super::codec::DecodeErrorKind::WrongType {
                        expected: "no underscore form for a complex type",
                    }));
                }
                let value = value.ok_or_else(|| {
                    path.error(super::super::codec::DecodeErrorKind::MissingProperty)
                })?;
                let inner = super::super::codec::Json::from_json(
                    super::super::codec::expect_object(
                        super::super::codec::expect_single(value, path)?,
                        path,
                    )?,
                    path,
                )?;
                Ok(Self::RelatedArtifact(Box::new(inner)))
            }
            "TriggerDefinition" => {
                if element.is_some() {
                    return Err(path.error(super::super::codec::DecodeErrorKind::WrongType {
                        expected: "no underscore form for a complex type",
                    }));
                }
                let value = value.ok_or_else(|| {
                    path.error(super::super::codec::DecodeErrorKind::MissingProperty)
                })?;
                let inner = super::super::codec::Json::from_json(
                    super::super::codec::expect_object(
                        super::super::codec::expect_single(value, path)?,
                        path,
                    )?,
                    path,
                )?;
                Ok(Self::TriggerDefinition(Box::new(inner)))
            }
            "UsageContext" => {
                if element.is_some() {
                    return Err(path.error(super::super::codec::DecodeErrorKind::WrongType {
                        expected: "no underscore form for a complex type",
                    }));
                }
                let value = value.ok_or_else(|| {
                    path.error(super::super::codec::DecodeErrorKind::MissingProperty)
                })?;
                let inner = super::super::codec::Json::from_json(
                    super::super::codec::expect_object(
                        super::super::codec::expect_single(value, path)?,
                        path,
                    )?,
                    path,
                )?;
                Ok(Self::UsageContext(Box::new(inner)))
            }
            "Dosage" => {
                if element.is_some() {
                    return Err(path.error(super::super::codec::DecodeErrorKind::WrongType {
                        expected: "no underscore form for a complex type",
                    }));
                }
                let value = value.ok_or_else(|| {
                    path.error(super::super::codec::DecodeErrorKind::MissingProperty)
                })?;
                let inner = super::super::codec::Json::from_json(
                    super::super::codec::expect_object(
                        super::super::codec::expect_single(value, path)?,
                        path,
                    )?,
                    path,
                )?;
                Ok(Self::Dosage(Box::new(inner)))
            }
            "Meta" => {
                if element.is_some() {
                    return Err(path.error(super::super::codec::DecodeErrorKind::WrongType {
                        expected: "no underscore form for a complex type",
                    }));
                }
                let value = value.ok_or_else(|| {
                    path.error(super::super::codec::DecodeErrorKind::MissingProperty)
                })?;
                let inner = super::super::codec::Json::from_json(
                    super::super::codec::expect_object(
                        super::super::codec::expect_single(value, path)?,
                        path,
                    )?,
                    path,
                )?;
                Ok(Self::Meta(Box::new(inner)))
            }
            _ => Err(path.error(super::super::codec::DecodeErrorKind::UnknownProperty)),
        }
    }
}
