// @generated by notio-fhir-codegen from hl7.fhir.r5.core 5.0.0. DO NOT EDIT.
// Change the emitter (tools/notio-fhir-codegen) and regenerate.
//! Contact information

/// Contact information
///
/// Specifies contact information for a specific purpose over a period of time,
/// might be handled/monitored by a specific named person or organization.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ExtendedContactDetail {
    /// Unique id for inter-element referencing
    ///
    /// Unique id for the element within a resource (for internal references). This
    /// may be any string value that does not contain spaces.
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the element. To make the use of extensions safe and
    /// managable, there is a strict set of governance applied to the definition and
    /// use of extensions. Though any implementer can define an extension, there is
    /// a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// The type of contact
    ///
    /// The purpose/type of contact.
    pub purpose: Option<super::codeable_concept::CodeableConcept>,
    /// Name of an individual to contact
    ///
    /// The name of an individual to contact, some types of contact detail are
    /// usually blank.
    pub name: Vec<super::human_name::HumanName>,
    /// Contact details (e.g.phone/fax/url)
    ///
    /// The contact details application for the purpose defined.
    pub telecom: Vec<super::contact_point::ContactPoint>,
    /// Address for the contact.
    pub address: Option<super::address::Address>,
    /// This contact detail is handled/monitored by a specific organization
    ///
    /// This contact detail is handled/monitored by a specific organization. If the
    /// name is provided in the contact, then it is referring to the named
    /// individual within this organization.
    pub organization: Option<super::reference::Reference>,
    /// Period that this contact was valid for usage.
    pub period: Option<super::period::Period>,
}
