// @generated by notio-fhir-codegen from hl7.fhir.r5.core 5.0.0. DO NOT EDIT.
// Change the emitter (tools/notio-fhir-codegen) and regenerate.
//! Metadata about a resource

/// Metadata about a resource
///
/// The metadata about a resource. This is content in the resource that is
/// maintained by the infrastructure. Changes to the content might not always be
/// associated with version changes to the resource.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Meta {
    /// Unique id for inter-element referencing
    ///
    /// Unique id for the element within a resource (for internal references). This
    /// may be any string value that does not contain spaces.
    pub id: Option<std::string::String>,
    /// Additional content defined by implementations
    ///
    /// May be used to represent additional information that is not part of the
    /// basic definition of the element. To make the use of extensions safe and
    /// managable, there is a strict set of governance applied to the definition and
    /// use of extensions. Though any implementer can define an extension, there is
    /// a set of requirements that SHALL be met as part of the definition of the
    /// extension.
    pub extension: Vec<super::extension::Extension>,
    /// Version specific identifier
    ///
    /// The version specific identifier, as it appears in the version portion of the
    /// URL. This value changes when the resource is created, updated, or deleted.
    pub version_id: Option<super::primitives::Id>,
    /// When the resource version last changed
    ///
    /// When the resource last changed - e.g. when the version changed.
    pub last_updated: Option<super::primitives::Instant>,
    /// Identifies where the resource comes from
    ///
    /// A uri that identifies the source system of the resource. This provides a
    /// minimal amount of \[Provenance\](provenance.html\#) information that can be
    /// used to track or differentiate the source of information in the resource.
    /// The source may identify another FHIR server, document, message, database,
    /// etc.
    pub source: Option<super::primitives::Uri>,
    /// Profiles this resource claims to conform to
    ///
    /// A list of profiles (references to
    /// \[StructureDefinition\](structuredefinition.html\#) resources) that this
    /// resource claims to conform to. The URL is a reference to
    /// \[StructureDefinition.url\](structuredefinition-definitions.html\#StructureDefinition.url).
    pub profile: Vec<super::primitives::Canonical>,
    /// Security Labels applied to this resource
    ///
    /// Security labels applied to this resource. These tags connect specific
    /// resources to the overall security policy and infrastructure.
    pub security: Vec<super::coding::Coding>,
    /// Tags applied to this resource
    ///
    /// Tags applied to this resource. Tags are intended to be used to identify and
    /// relate resources to process and workflow, and applications are not required
    /// to consider the tags when interpreting the meaning of a resource.
    pub tag: Vec<super::coding::Coding>,
}
