// @generated by notio-fhir-codegen from hl7.fhir.r5.core 5.0.0. DO NOT EDIT.
// Change the emitter (tools/notio-fhir-codegen) and regenerate.
//! FHIR R5 types: the terminology root set and the complete closure of the
//! datatypes and primitives it references, from `hl7.fhir.r5.core` 5.0.0.

pub mod address;
pub mod age;
pub mod annotation;
pub mod attachment;
pub mod availability;
pub mod bundle;
pub mod capability_statement;
pub mod code_system;
pub mod codeable_concept;
pub mod codeable_reference;
pub mod coding;
pub mod concept_map;
pub mod contact_detail;
pub mod contact_point;
pub mod count;
pub mod data_requirement;
pub mod distance;
pub mod dosage;
pub mod duration;
pub mod expression;
pub mod extended_contact_detail;
pub mod extension;
pub mod human_name;
pub mod identifier;
pub mod meta;
pub mod money;
pub mod narrative;
pub mod operation_outcome;
pub mod operations;
pub mod parameter_definition;
pub mod parameters;
pub mod period;
pub mod primitives;
pub mod quantity;
pub mod range;
pub mod ratio;
pub mod ratio_range;
pub mod reference;
pub mod related_artifact;
pub mod resource;
pub mod sampled_data;
pub mod signature;
pub mod terminology_capabilities;
pub mod timing;
pub mod trigger_definition;
pub mod usage_context;
pub mod value_set;
