// @generated by fhir-codegen from hl7.fhir.r4b.core 4.3.0. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
//! `ConceptMap/$closure`.
//!
//! This operation provides support for ongoing maintenance of a client-side
//! \[transitive closure
//! table\](<https://en.wikipedia.org/wiki/Transitive_closure#In_graph_theory>)
//! based on server-side terminological logic. For details of how this is
//! used, see \[Maintaining a Closure
//! Table\](terminology-service.html\#closure)

/// The `in` parameters of `ConceptMap/$closure`.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ConceptMapClosureRequest {
    /// The name that defines the particular context for the subsumption based
    /// closure table
    pub name: super::super::primitives::String,
    /// Concepts to add to the closure table
    pub concept: Vec<super::super::coding::Coding>,
    /// A request to resynchronise - request to send all new entries since the
    /// nominated version was sent by the server
    pub version: Option<super::super::primitives::String>,
}

/// The `out` parameters of `ConceptMap/$closure`.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ConceptMapClosureResponse {
    /// A list of new entries (code / system --\> code/system) that the client
    /// should add to its closure table. The only kind of entry mapping
    /// equivalences that can be returned are equal, specializes, subsumes and
    /// unmatched
    pub r#return: super::super::concept_map::ConceptMap,
}

impl ConceptMapClosureRequest {
    /// Reads the parameters from a `Parameters` resource.
    ///
    /// # Errors
    ///
    /// Returns the error for an undeclared, repeated, missing, or wrongly typed parameter.
    pub fn from_parameters(
        parameters: &super::super::parameters::Parameters,
    ) -> Result<Self, super::super::super::operation::ParametersError> {
        Self::from_parameter_list(&parameters.parameter)
    }
    /// Writes the parameters as a `Parameters` resource.
    #[must_use]
    pub fn to_parameters(&self) -> super::super::parameters::Parameters {
        super::super::parameters::Parameters {
            parameter: self.to_parameter_list(),
            ..Default::default()
        }
    }
    /// Reads the fields from a parameter list.
    ///
    /// # Errors
    ///
    /// Returns the error for an undeclared, repeated, missing, or wrongly typed parameter.
    pub fn from_parameter_list(
        list: &[super::super::parameters::ParametersParameter],
    ) -> Result<Self, super::super::super::operation::ParametersError> {
        const OPERATION: &str = "ConceptMap/$closure";
        const PREFIX: &str = "";
        let mut field_name: Option<super::super::primitives::String> = None;
        let mut field_concept: Vec<super::super::coding::Coding> = Vec::new();
        let mut field_version: Option<super::super::primitives::String> = None;
        for parameter in list {
            let parameter_name = parameter.name.value.as_deref().ok_or(
                super::super::super::operation::ParametersError::Unnamed {
                    operation: OPERATION,
                },
            )?;
            match parameter_name {
                "name" => {
                    if field_name.is_some() {
                        return Err(super::super::super::operation::ParametersError::Repeated {
                            operation: OPERATION,
                            name: "name",
                        });
                    }
                    field_name = Some(match &parameter.value {
                        Some(super::super::parameters::ParametersParameterValue::String(value)) => {
                            value.clone()
                        }
                        Some(super::super::parameters::ParametersParameterValue::Code(value)) => {
                            super::super::primitives::String {
                                id: value.id.clone(),
                                extension: value.extension.clone(),
                                value: value.value.clone(),
                            }
                        }
                        Some(super::super::parameters::ParametersParameterValue::Id(value)) => {
                            super::super::primitives::String {
                                id: value.id.clone(),
                                extension: value.extension.clone(),
                                value: value.value.clone(),
                            }
                        }
                        Some(super::super::parameters::ParametersParameterValue::Markdown(
                            value,
                        )) => super::super::primitives::String {
                            id: value.id.clone(),
                            extension: value.extension.clone(),
                            value: value.value.clone(),
                        },
                        Some(_) => {
                            return Err(
                                super::super::super::operation::ParametersError::WrongType {
                                    operation: OPERATION,
                                    name: "name",
                                    expected: "String",
                                },
                            );
                        }
                        None => {
                            return Err(
                                super::super::super::operation::ParametersError::MissingValue {
                                    operation: OPERATION,
                                    name: "name",
                                },
                            );
                        }
                    });
                }
                "concept" => {
                    field_concept.push(match &parameter.value {
                        Some(super::super::parameters::ParametersParameterValue::Coding(value)) => {
                            value.clone()
                        }
                        Some(_) => {
                            return Err(
                                super::super::super::operation::ParametersError::WrongType {
                                    operation: OPERATION,
                                    name: "concept",
                                    expected: "Coding",
                                },
                            );
                        }
                        None => {
                            return Err(
                                super::super::super::operation::ParametersError::MissingValue {
                                    operation: OPERATION,
                                    name: "concept",
                                },
                            );
                        }
                    });
                }
                "version" => {
                    if field_version.is_some() {
                        return Err(super::super::super::operation::ParametersError::Repeated {
                            operation: OPERATION,
                            name: "version",
                        });
                    }
                    field_version = Some(match &parameter.value {
                        Some(super::super::parameters::ParametersParameterValue::String(value)) => {
                            value.clone()
                        }
                        Some(super::super::parameters::ParametersParameterValue::Code(value)) => {
                            super::super::primitives::String {
                                id: value.id.clone(),
                                extension: value.extension.clone(),
                                value: value.value.clone(),
                            }
                        }
                        Some(super::super::parameters::ParametersParameterValue::Id(value)) => {
                            super::super::primitives::String {
                                id: value.id.clone(),
                                extension: value.extension.clone(),
                                value: value.value.clone(),
                            }
                        }
                        Some(super::super::parameters::ParametersParameterValue::Markdown(
                            value,
                        )) => super::super::primitives::String {
                            id: value.id.clone(),
                            extension: value.extension.clone(),
                            value: value.value.clone(),
                        },
                        Some(_) => {
                            return Err(
                                super::super::super::operation::ParametersError::WrongType {
                                    operation: OPERATION,
                                    name: "version",
                                    expected: "String",
                                },
                            );
                        }
                        None => {
                            return Err(
                                super::super::super::operation::ParametersError::MissingValue {
                                    operation: OPERATION,
                                    name: "version",
                                },
                            );
                        }
                    });
                }
                other => {
                    return Err(
                        super::super::super::operation::ParametersError::Undeclared {
                            operation: OPERATION,
                            name: [PREFIX, other].concat(),
                        },
                    );
                }
            }
        }
        Ok(Self {
            name: field_name.ok_or(super::super::super::operation::ParametersError::Missing {
                operation: OPERATION,
                name: "name",
            })?,
            concept: field_concept,
            version: field_version,
        })
    }
    /// Writes the fields as a parameter list.
    #[must_use]
    pub fn to_parameter_list(&self) -> Vec<super::super::parameters::ParametersParameter> {
        let mut out = Vec::new();
        {
            let value = &self.name;
            out.push(super::super::parameters::ParametersParameter {
                name: "name".into(),
                value: Some(super::super::parameters::ParametersParameterValue::String(
                    value.clone(),
                )),
                ..Default::default()
            });
        }
        for value in &self.concept {
            out.push(super::super::parameters::ParametersParameter {
                name: "concept".into(),
                value: Some(super::super::parameters::ParametersParameterValue::Coding(
                    value.clone(),
                )),
                ..Default::default()
            });
        }
        if let Some(value) = &self.version {
            out.push(super::super::parameters::ParametersParameter {
                name: "version".into(),
                value: Some(super::super::parameters::ParametersParameterValue::String(
                    value.clone(),
                )),
                ..Default::default()
            });
        }
        out
    }
}

impl ConceptMapClosureResponse {
    /// Reads the parameters from a `Parameters` resource.
    ///
    /// # Errors
    ///
    /// Returns the error for an undeclared, repeated, missing, or wrongly typed parameter.
    pub fn from_parameters(
        parameters: &super::super::parameters::Parameters,
    ) -> Result<Self, super::super::super::operation::ParametersError> {
        Self::from_parameter_list(&parameters.parameter)
    }
    /// Writes the parameters as a `Parameters` resource.
    #[must_use]
    pub fn to_parameters(&self) -> super::super::parameters::Parameters {
        super::super::parameters::Parameters {
            parameter: self.to_parameter_list(),
            ..Default::default()
        }
    }
    /// Reads the fields from a parameter list.
    ///
    /// # Errors
    ///
    /// Returns the error for an undeclared, repeated, missing, or wrongly typed parameter.
    pub fn from_parameter_list(
        list: &[super::super::parameters::ParametersParameter],
    ) -> Result<Self, super::super::super::operation::ParametersError> {
        const OPERATION: &str = "ConceptMap/$closure";
        const PREFIX: &str = "";
        let mut field_return: Option<super::super::concept_map::ConceptMap> = None;
        for parameter in list {
            let parameter_name = parameter.name.value.as_deref().ok_or(
                super::super::super::operation::ParametersError::Unnamed {
                    operation: OPERATION,
                },
            )?;
            match parameter_name {
                "return" => {
                    if field_return.is_some() {
                        return Err(super::super::super::operation::ParametersError::Repeated {
                            operation: OPERATION,
                            name: "return",
                        });
                    }
                    field_return = Some(match &parameter.resource {
                        Some(super::super::resource::Resource::ConceptMap(value)) => {
                            (**value).clone()
                        }
                        Some(_) => {
                            return Err(
                                super::super::super::operation::ParametersError::WrongType {
                                    operation: OPERATION,
                                    name: "return",
                                    expected: "ConceptMap",
                                },
                            );
                        }
                        None => {
                            return Err(
                                super::super::super::operation::ParametersError::MissingValue {
                                    operation: OPERATION,
                                    name: "return",
                                },
                            );
                        }
                    });
                }
                other => {
                    return Err(
                        super::super::super::operation::ParametersError::Undeclared {
                            operation: OPERATION,
                            name: [PREFIX, other].concat(),
                        },
                    );
                }
            }
        }
        Ok(Self {
            r#return: field_return.ok_or(
                super::super::super::operation::ParametersError::Missing {
                    operation: OPERATION,
                    name: "return",
                },
            )?,
        })
    }
    /// Writes the fields as a parameter list.
    #[must_use]
    pub fn to_parameter_list(&self) -> Vec<super::super::parameters::ParametersParameter> {
        let mut out = Vec::new();
        {
            let value = &self.r#return;
            out.push(super::super::parameters::ParametersParameter {
                name: "return".into(),
                resource: Some(super::super::resource::Resource::ConceptMap(Box::new(
                    value.clone(),
                ))),
                ..Default::default()
            });
        }
        out
    }
}

/// The declared parameter set of `ConceptMap/$closure`.
pub const CONCEPT_MAP_CLOSURE: super::super::super::operation::Operation =
    super::super::super::operation::Operation {
        url: "http://hl7.org/fhir/OperationDefinition/ConceptMap-closure",
        resource: "ConceptMap",
        code: "closure",
        system: true,
        type_level: false,
        instance: false,
        parameters: &[
            super::super::super::operation::Parameter {
                name: "name",
                usage: super::super::super::operation::ParameterUse::In,
                cardinality: super::super::super::operation::Cardinality {
                    min: 1,
                    max: Some(1),
                },
                type_code: Some("string"),
                scope: &[],
                source: super::super::super::operation::ParameterSource::Version,
                parts: &[],
            },
            super::super::super::operation::Parameter {
                name: "concept",
                usage: super::super::super::operation::ParameterUse::In,
                cardinality: super::super::super::operation::Cardinality { min: 0, max: None },
                type_code: Some("Coding"),
                scope: &[],
                source: super::super::super::operation::ParameterSource::Version,
                parts: &[],
            },
            super::super::super::operation::Parameter {
                name: "version",
                usage: super::super::super::operation::ParameterUse::In,
                cardinality: super::super::super::operation::Cardinality {
                    min: 0,
                    max: Some(1),
                },
                type_code: Some("string"),
                scope: &[],
                source: super::super::super::operation::ParameterSource::Version,
                parts: &[],
            },
            super::super::super::operation::Parameter {
                name: "return",
                usage: super::super::super::operation::ParameterUse::Out,
                cardinality: super::super::super::operation::Cardinality {
                    min: 1,
                    max: Some(1),
                },
                type_code: Some("ConceptMap"),
                scope: &[],
                source: super::super::super::operation::ParameterSource::Version,
                parts: &[],
            },
        ],
    };
