// @generated by fhir-codegen from hl7.fhir.r4.core 4.0.1. DO NOT EDIT.
// Change the emitter (tools/fhir-codegen) and regenerate.
//! `CodeSystem/$find-matches`.
//!
//! Given a set of properties (and text), return one or more possible
//! matching codes This operation takes a set of properties, and examines
//! the code system looking for codes in the code system that match a set of
//! known properties. When looking for matches, there are 3 possible types
//! of match: \* a complete match - a code that represents all the provided
//! properties correctly \* a partial match - a code that represents some of
//! the provided properties correctly, and not others \* a possible match -
//! a code that may represent the provided properties closely, but may
//! capture less or more precise information for some of the properties The
//! $find-matches operation can be called in one of 2 modes: \* By a human,
//! looking for the best match for a set of properties. In this mode, the
//! server returns a list of complete, possible or partial matches (possibly
//! with comments), so that the user can choose (or not) the most
//! appropriate code \* By a machine (typically in a system interface
//! performing a transformation). In this mode, the server returns only a
//! list of complete and partial matches, but no possible matches. The
//! machine can choose a code from the list (or not) based on what
//! properties are not coded These modes are differentiated by the 'exact'
//! parameter, so the client can indicate whether it only wants exact
//! matches (including partial matches) or whether potential matches based
//! on text matching are desired The find-matches operation is still
//! preliminary. The interface can be expected to change as more experience
//! is gained from implementations.

/// The `in` parameters of `CodeSystem/$find-matches`.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct CodeSystemFindMatchesRequest {
    /// The system in which composition is to be performed. This must be
    /// provided unless the operation is invoked on a code system instance
    pub system: Option<super::super::primitives::Uri>,
    /// The version of the system for the inferencing to be performed
    pub version: Option<super::super::primitives::String>,
    /// One or more properties that contain information to be composed into the
    /// code
    pub property: Vec<CodeSystemFindMatchesRequestProperty>,
    /// Whether the operation is being used by a human ('false'), or a machine
    /// ('true'). If the operation is being used by a human, the terminology
    /// server can return a list of possible matches, with commentary. For a
    /// machine, the server returns complete or partial matches, not possible
    /// matches. The default value is 'false'
    pub exact: super::super::primitives::Boolean,
    /// Post-coordinated expressions are allowed to be returned in the matching
    /// codes (mainly for SNOMED CT). Default = false
    pub compositional: Option<super::super::primitives::Boolean>,
}

/// The parts of the `property` parameter.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct CodeSystemFindMatchesRequestProperty {
    /// Identifies the property provided
    pub code: super::super::primitives::Code,
    /// The value of the property provided
    pub value: Option<super::super::parameters::ParametersParameterValue>,
    /// Nested Properties (mainly used for SNOMED CT composition, for
    /// relationship Groups)
    pub subproperty: Vec<CodeSystemFindMatchesRequestPropertySubproperty>,
}

/// The parts of the `subproperty` parameter.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CodeSystemFindMatchesRequestPropertySubproperty {
    /// Identifies the sub-property provided
    pub code: super::super::primitives::Code,
    /// The value of the sub-property provided
    pub value: super::super::parameters::ParametersParameterValue,
}

/// The `out` parameters of `CodeSystem/$find-matches`.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct CodeSystemFindMatchesResponse {
    /// Concepts returned by the server as a result of the inferencing operation
    pub r#match: Vec<CodeSystemFindMatchesResponseMatch>,
}

/// The parts of the `match` parameter.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct CodeSystemFindMatchesResponseMatch {
    /// A code that matches the properties provided
    pub code: super::super::coding::Coding,
    /// One or more properties that contain properties that could not be matched
    /// into the code
    pub unmatched: Vec<CodeSystemFindMatchesResponseMatchUnmatched>,
    /// Information about the quality of the match, if operation is for a human
    pub comment: Option<super::super::primitives::String>,
}

/// The parts of the `unmatched` parameter.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CodeSystemFindMatchesResponseMatchUnmatched {
    /// Identifies the property provided
    pub code: super::super::primitives::Code,
    /// The value of the property provided
    pub value: super::super::parameters::ParametersParameterValue,
    /// Nested Properties (mainly used for SNOMED CT composition, for
    /// relationship Groups)
    pub property: Vec<CodeSystemFindMatchesResponseMatchUnmatchedProperty>,
}

/// The parts of the `property` parameter.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CodeSystemFindMatchesResponseMatchUnmatchedProperty {
    /// Identifies the sub-property provided
    pub code: super::super::primitives::Code,
    /// The value of the sub-property provided
    pub value: super::super::parameters::ParametersParameterValue,
}

impl CodeSystemFindMatchesRequest {
    /// Reads the parameters from a `Parameters` resource.
    ///
    /// # Errors
    ///
    /// Returns the error for an undeclared, repeated, missing, or wrongly typed parameter.
    pub fn from_parameters(
        parameters: &super::super::parameters::Parameters,
    ) -> Result<Self, super::super::super::operation::ParametersError> {
        Self::from_parameter_list(&parameters.parameter)
    }
    /// Writes the parameters as a `Parameters` resource, by move.
    #[must_use]
    pub fn into_parameters(self) -> super::super::parameters::Parameters {
        super::super::parameters::Parameters {
            parameter: self.into_parameter_list(),
            ..Default::default()
        }
    }
    /// Writes the parameters as a `Parameters` resource, from a reference.
    #[must_use]
    pub fn to_parameters(&self) -> super::super::parameters::Parameters {
        self.clone().into_parameters()
    }
    /// Reads the fields from a parameter list.
    ///
    /// # Errors
    ///
    /// Returns the error for an undeclared, repeated, missing, or wrongly typed parameter.
    pub fn from_parameter_list(
        list: &[super::super::parameters::ParametersParameter],
    ) -> Result<Self, super::super::super::operation::ParametersError> {
        const OPERATION: &str = "CodeSystem/$find-matches";
        const PREFIX: &str = "";
        let mut field_system: Option<super::super::primitives::Uri> = None;
        let mut field_version: Option<super::super::primitives::String> = None;
        let mut field_property: Vec<CodeSystemFindMatchesRequestProperty> = Vec::new();
        let mut field_exact: Option<super::super::primitives::Boolean> = None;
        let mut field_compositional: Option<super::super::primitives::Boolean> = None;
        for parameter in list {
            let parameter_name = parameter.name.value.as_deref().ok_or(
                super::super::super::operation::ParametersError::Unnamed {
                    operation: OPERATION,
                },
            )?;
            match parameter_name {
                "system" => {
                    if field_system.is_some() {
                        return Err(super::super::super::operation::ParametersError::Repeated {
                            operation: OPERATION,
                            name: "system",
                        });
                    }
                    field_system = Some(match &parameter.value {
                        Some(super::super::parameters::ParametersParameterValue::Uri(value)) => {
                            value.clone()
                        }
                        Some(super::super::parameters::ParametersParameterValue::Canonical(
                            value,
                        )) => super::super::primitives::Uri {
                            id: value.id.clone(),
                            extension: value.extension.clone(),
                            value: value.value.clone(),
                        },
                        Some(super::super::parameters::ParametersParameterValue::Oid(value)) => {
                            super::super::primitives::Uri {
                                id: value.id.clone(),
                                extension: value.extension.clone(),
                                value: value.value.clone(),
                            }
                        }
                        Some(super::super::parameters::ParametersParameterValue::Url(value)) => {
                            super::super::primitives::Uri {
                                id: value.id.clone(),
                                extension: value.extension.clone(),
                                value: value.value.clone(),
                            }
                        }
                        Some(super::super::parameters::ParametersParameterValue::Uuid(value)) => {
                            super::super::primitives::Uri {
                                id: value.id.clone(),
                                extension: value.extension.clone(),
                                value: value.value.clone(),
                            }
                        }
                        Some(_) => {
                            return Err(
                                super::super::super::operation::ParametersError::WrongType {
                                    operation: OPERATION,
                                    name: "system",
                                    expected: "Uri",
                                },
                            );
                        }
                        None => {
                            return Err(
                                super::super::super::operation::ParametersError::MissingValue {
                                    operation: OPERATION,
                                    name: "system",
                                },
                            );
                        }
                    });
                }
                "version" => {
                    if field_version.is_some() {
                        return Err(super::super::super::operation::ParametersError::Repeated {
                            operation: OPERATION,
                            name: "version",
                        });
                    }
                    field_version = Some(match &parameter.value {
                        Some(super::super::parameters::ParametersParameterValue::String(value)) => {
                            value.clone()
                        }
                        Some(super::super::parameters::ParametersParameterValue::Code(value)) => {
                            super::super::primitives::String {
                                id: value.id.clone(),
                                extension: value.extension.clone(),
                                value: value.value.clone(),
                            }
                        }
                        Some(super::super::parameters::ParametersParameterValue::Id(value)) => {
                            super::super::primitives::String {
                                id: value.id.clone(),
                                extension: value.extension.clone(),
                                value: value.value.clone(),
                            }
                        }
                        Some(super::super::parameters::ParametersParameterValue::Markdown(
                            value,
                        )) => super::super::primitives::String {
                            id: value.id.clone(),
                            extension: value.extension.clone(),
                            value: value.value.clone(),
                        },
                        Some(_) => {
                            return Err(
                                super::super::super::operation::ParametersError::WrongType {
                                    operation: OPERATION,
                                    name: "version",
                                    expected: "String",
                                },
                            );
                        }
                        None => {
                            return Err(
                                super::super::super::operation::ParametersError::MissingValue {
                                    operation: OPERATION,
                                    name: "version",
                                },
                            );
                        }
                    });
                }
                "property" => {
                    field_property.push(CodeSystemFindMatchesRequestProperty::from_parameter_list(
                        &parameter.part,
                    )?);
                }
                "exact" => {
                    if field_exact.is_some() {
                        return Err(super::super::super::operation::ParametersError::Repeated {
                            operation: OPERATION,
                            name: "exact",
                        });
                    }
                    field_exact = Some(match &parameter.value {
                        Some(super::super::parameters::ParametersParameterValue::Boolean(
                            value,
                        )) => value.clone(),
                        Some(_) => {
                            return Err(
                                super::super::super::operation::ParametersError::WrongType {
                                    operation: OPERATION,
                                    name: "exact",
                                    expected: "Boolean",
                                },
                            );
                        }
                        None => {
                            return Err(
                                super::super::super::operation::ParametersError::MissingValue {
                                    operation: OPERATION,
                                    name: "exact",
                                },
                            );
                        }
                    });
                }
                "compositional" => {
                    if field_compositional.is_some() {
                        return Err(super::super::super::operation::ParametersError::Repeated {
                            operation: OPERATION,
                            name: "compositional",
                        });
                    }
                    field_compositional = Some(match &parameter.value {
                        Some(super::super::parameters::ParametersParameterValue::Boolean(
                            value,
                        )) => value.clone(),
                        Some(_) => {
                            return Err(
                                super::super::super::operation::ParametersError::WrongType {
                                    operation: OPERATION,
                                    name: "compositional",
                                    expected: "Boolean",
                                },
                            );
                        }
                        None => {
                            return Err(
                                super::super::super::operation::ParametersError::MissingValue {
                                    operation: OPERATION,
                                    name: "compositional",
                                },
                            );
                        }
                    });
                }
                other => {
                    return Err(
                        super::super::super::operation::ParametersError::Undeclared {
                            operation: OPERATION,
                            name: [PREFIX, other].concat(),
                        },
                    );
                }
            }
        }
        Ok(Self {
            system: field_system,
            version: field_version,
            property: field_property,
            exact: field_exact.ok_or(super::super::super::operation::ParametersError::Missing {
                operation: OPERATION,
                name: "exact",
            })?,
            compositional: field_compositional,
        })
    }
    /// Writes the fields as a parameter list, by move.
    #[must_use]
    pub fn into_parameter_list(self) -> Vec<super::super::parameters::ParametersParameter> {
        let mut out = Vec::with_capacity(5);
        if let Some(value) = self.system {
            out.push(super::super::parameters::ParametersParameter {
                name: "system".into(),
                value: Some(super::super::parameters::ParametersParameterValue::Uri(
                    value,
                )),
                ..Default::default()
            });
        }
        if let Some(value) = self.version {
            out.push(super::super::parameters::ParametersParameter {
                name: "version".into(),
                value: Some(super::super::parameters::ParametersParameterValue::String(
                    value,
                )),
                ..Default::default()
            });
        }
        for value in self.property {
            out.push(super::super::parameters::ParametersParameter {
                name: "property".into(),
                part: value.into_parameter_list(),
                ..Default::default()
            });
        }
        {
            let value = self.exact;
            out.push(super::super::parameters::ParametersParameter {
                name: "exact".into(),
                value: Some(super::super::parameters::ParametersParameterValue::Boolean(
                    value,
                )),
                ..Default::default()
            });
        }
        if let Some(value) = self.compositional {
            out.push(super::super::parameters::ParametersParameter {
                name: "compositional".into(),
                value: Some(super::super::parameters::ParametersParameterValue::Boolean(
                    value,
                )),
                ..Default::default()
            });
        }
        out
    }
    /// Writes the fields as a parameter list, from a reference.
    #[must_use]
    pub fn to_parameter_list(&self) -> Vec<super::super::parameters::ParametersParameter> {
        self.clone().into_parameter_list()
    }
}

impl CodeSystemFindMatchesRequestProperty {
    /// Reads the fields from a parameter list.
    ///
    /// # Errors
    ///
    /// Returns the error for an undeclared, repeated, missing, or wrongly typed parameter.
    pub fn from_parameter_list(
        list: &[super::super::parameters::ParametersParameter],
    ) -> Result<Self, super::super::super::operation::ParametersError> {
        const OPERATION: &str = "CodeSystem/$find-matches";
        const PREFIX: &str = "property.";
        let mut field_code: Option<super::super::primitives::Code> = None;
        let mut field_value: Option<super::super::parameters::ParametersParameterValue> = None;
        let mut field_subproperty: Vec<CodeSystemFindMatchesRequestPropertySubproperty> =
            Vec::new();
        for parameter in list {
            let parameter_name = parameter.name.value.as_deref().ok_or(
                super::super::super::operation::ParametersError::Unnamed {
                    operation: OPERATION,
                },
            )?;
            match parameter_name {
                "code" => {
                    if field_code.is_some() {
                        return Err(super::super::super::operation::ParametersError::Repeated {
                            operation: OPERATION,
                            name: "property.code",
                        });
                    }
                    field_code = Some(match &parameter.value {
                        Some(super::super::parameters::ParametersParameterValue::Code(value)) => {
                            value.clone()
                        }
                        Some(super::super::parameters::ParametersParameterValue::String(value)) => {
                            super::super::primitives::Code {
                                id: value.id.clone(),
                                extension: value.extension.clone(),
                                value: value.value.clone(),
                            }
                        }
                        Some(_) => {
                            return Err(
                                super::super::super::operation::ParametersError::WrongType {
                                    operation: OPERATION,
                                    name: "property.code",
                                    expected: "Code",
                                },
                            );
                        }
                        None => {
                            return Err(
                                super::super::super::operation::ParametersError::MissingValue {
                                    operation: OPERATION,
                                    name: "property.code",
                                },
                            );
                        }
                    });
                }
                "value" => {
                    if field_value.is_some() {
                        return Err(super::super::super::operation::ParametersError::Repeated {
                            operation: OPERATION,
                            name: "property.value",
                        });
                    }
                    field_value = Some(parameter.value.clone().ok_or(
                        super::super::super::operation::ParametersError::MissingValue {
                            operation: OPERATION,
                            name: "property.value",
                        },
                    )?);
                }
                "subproperty" => {
                    field_subproperty.push(
                        CodeSystemFindMatchesRequestPropertySubproperty::from_parameter_list(
                            &parameter.part,
                        )?,
                    );
                }
                other => {
                    return Err(
                        super::super::super::operation::ParametersError::Undeclared {
                            operation: OPERATION,
                            name: [PREFIX, other].concat(),
                        },
                    );
                }
            }
        }
        Ok(Self {
            code: field_code.ok_or(super::super::super::operation::ParametersError::Missing {
                operation: OPERATION,
                name: "property.code",
            })?,
            value: field_value,
            subproperty: field_subproperty,
        })
    }
    /// Writes the fields as a parameter list, by move.
    #[must_use]
    pub fn into_parameter_list(self) -> Vec<super::super::parameters::ParametersParameter> {
        let mut out = Vec::with_capacity(3);
        {
            let value = self.code;
            out.push(super::super::parameters::ParametersParameter {
                name: "code".into(),
                value: Some(super::super::parameters::ParametersParameterValue::Code(
                    value,
                )),
                ..Default::default()
            });
        }
        if let Some(value) = self.value {
            out.push(super::super::parameters::ParametersParameter {
                name: "value".into(),
                value: Some(value),
                ..Default::default()
            });
        }
        for value in self.subproperty {
            out.push(super::super::parameters::ParametersParameter {
                name: "subproperty".into(),
                part: value.into_parameter_list(),
                ..Default::default()
            });
        }
        out
    }
    /// Writes the fields as a parameter list, from a reference.
    #[must_use]
    pub fn to_parameter_list(&self) -> Vec<super::super::parameters::ParametersParameter> {
        self.clone().into_parameter_list()
    }
}

impl CodeSystemFindMatchesRequestPropertySubproperty {
    /// Reads the fields from a parameter list.
    ///
    /// # Errors
    ///
    /// Returns the error for an undeclared, repeated, missing, or wrongly typed parameter.
    pub fn from_parameter_list(
        list: &[super::super::parameters::ParametersParameter],
    ) -> Result<Self, super::super::super::operation::ParametersError> {
        const OPERATION: &str = "CodeSystem/$find-matches";
        const PREFIX: &str = "property.subproperty.";
        let mut field_code: Option<super::super::primitives::Code> = None;
        let mut field_value: Option<super::super::parameters::ParametersParameterValue> = None;
        for parameter in list {
            let parameter_name = parameter.name.value.as_deref().ok_or(
                super::super::super::operation::ParametersError::Unnamed {
                    operation: OPERATION,
                },
            )?;
            match parameter_name {
                "code" => {
                    if field_code.is_some() {
                        return Err(super::super::super::operation::ParametersError::Repeated {
                            operation: OPERATION,
                            name: "property.subproperty.code",
                        });
                    }
                    field_code = Some(match &parameter.value {
                        Some(super::super::parameters::ParametersParameterValue::Code(value)) => {
                            value.clone()
                        }
                        Some(super::super::parameters::ParametersParameterValue::String(value)) => {
                            super::super::primitives::Code {
                                id: value.id.clone(),
                                extension: value.extension.clone(),
                                value: value.value.clone(),
                            }
                        }
                        Some(_) => {
                            return Err(
                                super::super::super::operation::ParametersError::WrongType {
                                    operation: OPERATION,
                                    name: "property.subproperty.code",
                                    expected: "Code",
                                },
                            );
                        }
                        None => {
                            return Err(
                                super::super::super::operation::ParametersError::MissingValue {
                                    operation: OPERATION,
                                    name: "property.subproperty.code",
                                },
                            );
                        }
                    });
                }
                "value" => {
                    if field_value.is_some() {
                        return Err(super::super::super::operation::ParametersError::Repeated {
                            operation: OPERATION,
                            name: "property.subproperty.value",
                        });
                    }
                    field_value = Some(parameter.value.clone().ok_or(
                        super::super::super::operation::ParametersError::MissingValue {
                            operation: OPERATION,
                            name: "property.subproperty.value",
                        },
                    )?);
                }
                other => {
                    return Err(
                        super::super::super::operation::ParametersError::Undeclared {
                            operation: OPERATION,
                            name: [PREFIX, other].concat(),
                        },
                    );
                }
            }
        }
        Ok(Self {
            code: field_code.ok_or(super::super::super::operation::ParametersError::Missing {
                operation: OPERATION,
                name: "property.subproperty.code",
            })?,
            value: field_value.ok_or(super::super::super::operation::ParametersError::Missing {
                operation: OPERATION,
                name: "property.subproperty.value",
            })?,
        })
    }
    /// Writes the fields as a parameter list, by move.
    #[must_use]
    pub fn into_parameter_list(self) -> Vec<super::super::parameters::ParametersParameter> {
        let mut out = Vec::with_capacity(2);
        {
            let value = self.code;
            out.push(super::super::parameters::ParametersParameter {
                name: "code".into(),
                value: Some(super::super::parameters::ParametersParameterValue::Code(
                    value,
                )),
                ..Default::default()
            });
        }
        {
            let value = self.value;
            out.push(super::super::parameters::ParametersParameter {
                name: "value".into(),
                value: Some(value),
                ..Default::default()
            });
        }
        out
    }
    /// Writes the fields as a parameter list, from a reference.
    #[must_use]
    pub fn to_parameter_list(&self) -> Vec<super::super::parameters::ParametersParameter> {
        self.clone().into_parameter_list()
    }
}

impl CodeSystemFindMatchesResponse {
    /// Reads the parameters from a `Parameters` resource.
    ///
    /// # Errors
    ///
    /// Returns the error for an undeclared, repeated, missing, or wrongly typed parameter.
    pub fn from_parameters(
        parameters: &super::super::parameters::Parameters,
    ) -> Result<Self, super::super::super::operation::ParametersError> {
        Self::from_parameter_list(&parameters.parameter)
    }
    /// Writes the parameters as a `Parameters` resource, by move.
    #[must_use]
    pub fn into_parameters(self) -> super::super::parameters::Parameters {
        super::super::parameters::Parameters {
            parameter: self.into_parameter_list(),
            ..Default::default()
        }
    }
    /// Writes the parameters as a `Parameters` resource, from a reference.
    #[must_use]
    pub fn to_parameters(&self) -> super::super::parameters::Parameters {
        self.clone().into_parameters()
    }
    /// Reads the fields from a parameter list.
    ///
    /// # Errors
    ///
    /// Returns the error for an undeclared, repeated, missing, or wrongly typed parameter.
    pub fn from_parameter_list(
        list: &[super::super::parameters::ParametersParameter],
    ) -> Result<Self, super::super::super::operation::ParametersError> {
        const OPERATION: &str = "CodeSystem/$find-matches";
        const PREFIX: &str = "";
        let mut field_match: Vec<CodeSystemFindMatchesResponseMatch> = Vec::new();
        for parameter in list {
            let parameter_name = parameter.name.value.as_deref().ok_or(
                super::super::super::operation::ParametersError::Unnamed {
                    operation: OPERATION,
                },
            )?;
            match parameter_name {
                "match" => {
                    field_match.push(CodeSystemFindMatchesResponseMatch::from_parameter_list(
                        &parameter.part,
                    )?);
                }
                other => {
                    return Err(
                        super::super::super::operation::ParametersError::Undeclared {
                            operation: OPERATION,
                            name: [PREFIX, other].concat(),
                        },
                    );
                }
            }
        }
        Ok(Self {
            r#match: field_match,
        })
    }
    /// Writes the fields as a parameter list, by move.
    #[must_use]
    pub fn into_parameter_list(self) -> Vec<super::super::parameters::ParametersParameter> {
        let mut out = Vec::with_capacity(1);
        for value in self.r#match {
            out.push(super::super::parameters::ParametersParameter {
                name: "match".into(),
                part: value.into_parameter_list(),
                ..Default::default()
            });
        }
        out
    }
    /// Writes the fields as a parameter list, from a reference.
    #[must_use]
    pub fn to_parameter_list(&self) -> Vec<super::super::parameters::ParametersParameter> {
        self.clone().into_parameter_list()
    }
}

impl CodeSystemFindMatchesResponseMatch {
    /// Reads the fields from a parameter list.
    ///
    /// # Errors
    ///
    /// Returns the error for an undeclared, repeated, missing, or wrongly typed parameter.
    pub fn from_parameter_list(
        list: &[super::super::parameters::ParametersParameter],
    ) -> Result<Self, super::super::super::operation::ParametersError> {
        const OPERATION: &str = "CodeSystem/$find-matches";
        const PREFIX: &str = "match.";
        let mut field_code: Option<super::super::coding::Coding> = None;
        let mut field_unmatched: Vec<CodeSystemFindMatchesResponseMatchUnmatched> = Vec::new();
        let mut field_comment: Option<super::super::primitives::String> = None;
        for parameter in list {
            let parameter_name = parameter.name.value.as_deref().ok_or(
                super::super::super::operation::ParametersError::Unnamed {
                    operation: OPERATION,
                },
            )?;
            match parameter_name {
                "code" => {
                    if field_code.is_some() {
                        return Err(super::super::super::operation::ParametersError::Repeated {
                            operation: OPERATION,
                            name: "match.code",
                        });
                    }
                    field_code = Some(match &parameter.value {
                        Some(super::super::parameters::ParametersParameterValue::Coding(value)) => {
                            (**value).clone()
                        }
                        Some(_) => {
                            return Err(
                                super::super::super::operation::ParametersError::WrongType {
                                    operation: OPERATION,
                                    name: "match.code",
                                    expected: "Coding",
                                },
                            );
                        }
                        None => {
                            return Err(
                                super::super::super::operation::ParametersError::MissingValue {
                                    operation: OPERATION,
                                    name: "match.code",
                                },
                            );
                        }
                    });
                }
                "unmatched" => {
                    field_unmatched.push(
                        CodeSystemFindMatchesResponseMatchUnmatched::from_parameter_list(
                            &parameter.part,
                        )?,
                    );
                }
                "comment" => {
                    if field_comment.is_some() {
                        return Err(super::super::super::operation::ParametersError::Repeated {
                            operation: OPERATION,
                            name: "match.comment",
                        });
                    }
                    field_comment = Some(match &parameter.value {
                        Some(super::super::parameters::ParametersParameterValue::String(value)) => {
                            value.clone()
                        }
                        Some(super::super::parameters::ParametersParameterValue::Code(value)) => {
                            super::super::primitives::String {
                                id: value.id.clone(),
                                extension: value.extension.clone(),
                                value: value.value.clone(),
                            }
                        }
                        Some(super::super::parameters::ParametersParameterValue::Id(value)) => {
                            super::super::primitives::String {
                                id: value.id.clone(),
                                extension: value.extension.clone(),
                                value: value.value.clone(),
                            }
                        }
                        Some(super::super::parameters::ParametersParameterValue::Markdown(
                            value,
                        )) => super::super::primitives::String {
                            id: value.id.clone(),
                            extension: value.extension.clone(),
                            value: value.value.clone(),
                        },
                        Some(_) => {
                            return Err(
                                super::super::super::operation::ParametersError::WrongType {
                                    operation: OPERATION,
                                    name: "match.comment",
                                    expected: "String",
                                },
                            );
                        }
                        None => {
                            return Err(
                                super::super::super::operation::ParametersError::MissingValue {
                                    operation: OPERATION,
                                    name: "match.comment",
                                },
                            );
                        }
                    });
                }
                other => {
                    return Err(
                        super::super::super::operation::ParametersError::Undeclared {
                            operation: OPERATION,
                            name: [PREFIX, other].concat(),
                        },
                    );
                }
            }
        }
        Ok(Self {
            code: field_code.ok_or(super::super::super::operation::ParametersError::Missing {
                operation: OPERATION,
                name: "match.code",
            })?,
            unmatched: field_unmatched,
            comment: field_comment,
        })
    }
    /// Writes the fields as a parameter list, by move.
    #[must_use]
    pub fn into_parameter_list(self) -> Vec<super::super::parameters::ParametersParameter> {
        let mut out = Vec::with_capacity(3);
        {
            let value = self.code;
            out.push(super::super::parameters::ParametersParameter {
                name: "code".into(),
                value: Some(super::super::parameters::ParametersParameterValue::Coding(
                    Box::new(value),
                )),
                ..Default::default()
            });
        }
        for value in self.unmatched {
            out.push(super::super::parameters::ParametersParameter {
                name: "unmatched".into(),
                part: value.into_parameter_list(),
                ..Default::default()
            });
        }
        if let Some(value) = self.comment {
            out.push(super::super::parameters::ParametersParameter {
                name: "comment".into(),
                value: Some(super::super::parameters::ParametersParameterValue::String(
                    value,
                )),
                ..Default::default()
            });
        }
        out
    }
    /// Writes the fields as a parameter list, from a reference.
    #[must_use]
    pub fn to_parameter_list(&self) -> Vec<super::super::parameters::ParametersParameter> {
        self.clone().into_parameter_list()
    }
}

impl CodeSystemFindMatchesResponseMatchUnmatched {
    /// Reads the fields from a parameter list.
    ///
    /// # Errors
    ///
    /// Returns the error for an undeclared, repeated, missing, or wrongly typed parameter.
    pub fn from_parameter_list(
        list: &[super::super::parameters::ParametersParameter],
    ) -> Result<Self, super::super::super::operation::ParametersError> {
        const OPERATION: &str = "CodeSystem/$find-matches";
        const PREFIX: &str = "match.unmatched.";
        let mut field_code: Option<super::super::primitives::Code> = None;
        let mut field_value: Option<super::super::parameters::ParametersParameterValue> = None;
        let mut field_property: Vec<CodeSystemFindMatchesResponseMatchUnmatchedProperty> =
            Vec::new();
        for parameter in list {
            let parameter_name = parameter.name.value.as_deref().ok_or(
                super::super::super::operation::ParametersError::Unnamed {
                    operation: OPERATION,
                },
            )?;
            match parameter_name {
                "code" => {
                    if field_code.is_some() {
                        return Err(super::super::super::operation::ParametersError::Repeated {
                            operation: OPERATION,
                            name: "match.unmatched.code",
                        });
                    }
                    field_code = Some(match &parameter.value {
                        Some(super::super::parameters::ParametersParameterValue::Code(value)) => {
                            value.clone()
                        }
                        Some(super::super::parameters::ParametersParameterValue::String(value)) => {
                            super::super::primitives::Code {
                                id: value.id.clone(),
                                extension: value.extension.clone(),
                                value: value.value.clone(),
                            }
                        }
                        Some(_) => {
                            return Err(
                                super::super::super::operation::ParametersError::WrongType {
                                    operation: OPERATION,
                                    name: "match.unmatched.code",
                                    expected: "Code",
                                },
                            );
                        }
                        None => {
                            return Err(
                                super::super::super::operation::ParametersError::MissingValue {
                                    operation: OPERATION,
                                    name: "match.unmatched.code",
                                },
                            );
                        }
                    });
                }
                "value" => {
                    if field_value.is_some() {
                        return Err(super::super::super::operation::ParametersError::Repeated {
                            operation: OPERATION,
                            name: "match.unmatched.value",
                        });
                    }
                    field_value = Some(parameter.value.clone().ok_or(
                        super::super::super::operation::ParametersError::MissingValue {
                            operation: OPERATION,
                            name: "match.unmatched.value",
                        },
                    )?);
                }
                "property" => {
                    field_property.push(
                        CodeSystemFindMatchesResponseMatchUnmatchedProperty::from_parameter_list(
                            &parameter.part,
                        )?,
                    );
                }
                other => {
                    return Err(
                        super::super::super::operation::ParametersError::Undeclared {
                            operation: OPERATION,
                            name: [PREFIX, other].concat(),
                        },
                    );
                }
            }
        }
        Ok(Self {
            code: field_code.ok_or(super::super::super::operation::ParametersError::Missing {
                operation: OPERATION,
                name: "match.unmatched.code",
            })?,
            value: field_value.ok_or(super::super::super::operation::ParametersError::Missing {
                operation: OPERATION,
                name: "match.unmatched.value",
            })?,
            property: field_property,
        })
    }
    /// Writes the fields as a parameter list, by move.
    #[must_use]
    pub fn into_parameter_list(self) -> Vec<super::super::parameters::ParametersParameter> {
        let mut out = Vec::with_capacity(3);
        {
            let value = self.code;
            out.push(super::super::parameters::ParametersParameter {
                name: "code".into(),
                value: Some(super::super::parameters::ParametersParameterValue::Code(
                    value,
                )),
                ..Default::default()
            });
        }
        {
            let value = self.value;
            out.push(super::super::parameters::ParametersParameter {
                name: "value".into(),
                value: Some(value),
                ..Default::default()
            });
        }
        for value in self.property {
            out.push(super::super::parameters::ParametersParameter {
                name: "property".into(),
                part: value.into_parameter_list(),
                ..Default::default()
            });
        }
        out
    }
    /// Writes the fields as a parameter list, from a reference.
    #[must_use]
    pub fn to_parameter_list(&self) -> Vec<super::super::parameters::ParametersParameter> {
        self.clone().into_parameter_list()
    }
}

impl CodeSystemFindMatchesResponseMatchUnmatchedProperty {
    /// Reads the fields from a parameter list.
    ///
    /// # Errors
    ///
    /// Returns the error for an undeclared, repeated, missing, or wrongly typed parameter.
    pub fn from_parameter_list(
        list: &[super::super::parameters::ParametersParameter],
    ) -> Result<Self, super::super::super::operation::ParametersError> {
        const OPERATION: &str = "CodeSystem/$find-matches";
        const PREFIX: &str = "match.unmatched.property.";
        let mut field_code: Option<super::super::primitives::Code> = None;
        let mut field_value: Option<super::super::parameters::ParametersParameterValue> = None;
        for parameter in list {
            let parameter_name = parameter.name.value.as_deref().ok_or(
                super::super::super::operation::ParametersError::Unnamed {
                    operation: OPERATION,
                },
            )?;
            match parameter_name {
                "code" => {
                    if field_code.is_some() {
                        return Err(super::super::super::operation::ParametersError::Repeated {
                            operation: OPERATION,
                            name: "match.unmatched.property.code",
                        });
                    }
                    field_code = Some(match &parameter.value {
                        Some(super::super::parameters::ParametersParameterValue::Code(value)) => {
                            value.clone()
                        }
                        Some(super::super::parameters::ParametersParameterValue::String(value)) => {
                            super::super::primitives::Code {
                                id: value.id.clone(),
                                extension: value.extension.clone(),
                                value: value.value.clone(),
                            }
                        }
                        Some(_) => {
                            return Err(
                                super::super::super::operation::ParametersError::WrongType {
                                    operation: OPERATION,
                                    name: "match.unmatched.property.code",
                                    expected: "Code",
                                },
                            );
                        }
                        None => {
                            return Err(
                                super::super::super::operation::ParametersError::MissingValue {
                                    operation: OPERATION,
                                    name: "match.unmatched.property.code",
                                },
                            );
                        }
                    });
                }
                "value" => {
                    if field_value.is_some() {
                        return Err(super::super::super::operation::ParametersError::Repeated {
                            operation: OPERATION,
                            name: "match.unmatched.property.value",
                        });
                    }
                    field_value = Some(parameter.value.clone().ok_or(
                        super::super::super::operation::ParametersError::MissingValue {
                            operation: OPERATION,
                            name: "match.unmatched.property.value",
                        },
                    )?);
                }
                other => {
                    return Err(
                        super::super::super::operation::ParametersError::Undeclared {
                            operation: OPERATION,
                            name: [PREFIX, other].concat(),
                        },
                    );
                }
            }
        }
        Ok(Self {
            code: field_code.ok_or(super::super::super::operation::ParametersError::Missing {
                operation: OPERATION,
                name: "match.unmatched.property.code",
            })?,
            value: field_value.ok_or(super::super::super::operation::ParametersError::Missing {
                operation: OPERATION,
                name: "match.unmatched.property.value",
            })?,
        })
    }
    /// Writes the fields as a parameter list, by move.
    #[must_use]
    pub fn into_parameter_list(self) -> Vec<super::super::parameters::ParametersParameter> {
        let mut out = Vec::with_capacity(2);
        {
            let value = self.code;
            out.push(super::super::parameters::ParametersParameter {
                name: "code".into(),
                value: Some(super::super::parameters::ParametersParameterValue::Code(
                    value,
                )),
                ..Default::default()
            });
        }
        {
            let value = self.value;
            out.push(super::super::parameters::ParametersParameter {
                name: "value".into(),
                value: Some(value),
                ..Default::default()
            });
        }
        out
    }
    /// Writes the fields as a parameter list, from a reference.
    #[must_use]
    pub fn to_parameter_list(&self) -> Vec<super::super::parameters::ParametersParameter> {
        self.clone().into_parameter_list()
    }
}

/// The declared parameter set of `CodeSystem/$find-matches`.
pub const CODE_SYSTEM_FIND_MATCHES: super::super::super::operation::Operation =
    super::super::super::operation::Operation {
        url: "http://hl7.org/fhir/OperationDefinition/CodeSystem-find-matches",
        resource: "CodeSystem",
        code: "find-matches",
        system: false,
        type_level: true,
        instance: true,
        parameters: &[
            super::super::super::operation::Parameter {
                name: "system",
                usage: super::super::super::operation::ParameterUse::In,
                cardinality: super::super::super::operation::Cardinality {
                    min: 0,
                    max: Some(1),
                },
                type_code: Some("uri"),
                scope: &[],
                source: super::super::super::operation::ParameterSource::Version,
                parts: &[],
            },
            super::super::super::operation::Parameter {
                name: "version",
                usage: super::super::super::operation::ParameterUse::In,
                cardinality: super::super::super::operation::Cardinality {
                    min: 0,
                    max: Some(1),
                },
                type_code: Some("string"),
                scope: &[],
                source: super::super::super::operation::ParameterSource::Version,
                parts: &[],
            },
            super::super::super::operation::Parameter {
                name: "property",
                usage: super::super::super::operation::ParameterUse::In,
                cardinality: super::super::super::operation::Cardinality { min: 0, max: None },
                type_code: None,
                scope: &[],
                source: super::super::super::operation::ParameterSource::Version,
                parts: &[
                    super::super::super::operation::Parameter {
                        name: "code",
                        usage: super::super::super::operation::ParameterUse::In,
                        cardinality: super::super::super::operation::Cardinality {
                            min: 1,
                            max: Some(1),
                        },
                        type_code: Some("code"),
                        scope: &[],
                        source: super::super::super::operation::ParameterSource::Version,
                        parts: &[],
                    },
                    super::super::super::operation::Parameter {
                        name: "value",
                        usage: super::super::super::operation::ParameterUse::In,
                        cardinality: super::super::super::operation::Cardinality {
                            min: 0,
                            max: Some(1),
                        },
                        type_code: Some("Element"),
                        scope: &[],
                        source: super::super::super::operation::ParameterSource::Version,
                        parts: &[],
                    },
                    super::super::super::operation::Parameter {
                        name: "subproperty",
                        usage: super::super::super::operation::ParameterUse::In,
                        cardinality: super::super::super::operation::Cardinality {
                            min: 0,
                            max: None,
                        },
                        type_code: None,
                        scope: &[],
                        source: super::super::super::operation::ParameterSource::Version,
                        parts: &[
                            super::super::super::operation::Parameter {
                                name: "code",
                                usage: super::super::super::operation::ParameterUse::In,
                                cardinality: super::super::super::operation::Cardinality {
                                    min: 1,
                                    max: Some(1),
                                },
                                type_code: Some("code"),
                                scope: &[],
                                source: super::super::super::operation::ParameterSource::Version,
                                parts: &[],
                            },
                            super::super::super::operation::Parameter {
                                name: "value",
                                usage: super::super::super::operation::ParameterUse::In,
                                cardinality: super::super::super::operation::Cardinality {
                                    min: 1,
                                    max: Some(1),
                                },
                                type_code: Some("Element"),
                                scope: &[],
                                source: super::super::super::operation::ParameterSource::Version,
                                parts: &[],
                            },
                        ],
                    },
                ],
            },
            super::super::super::operation::Parameter {
                name: "exact",
                usage: super::super::super::operation::ParameterUse::In,
                cardinality: super::super::super::operation::Cardinality {
                    min: 1,
                    max: Some(1),
                },
                type_code: Some("boolean"),
                scope: &[],
                source: super::super::super::operation::ParameterSource::Version,
                parts: &[],
            },
            super::super::super::operation::Parameter {
                name: "compositional",
                usage: super::super::super::operation::ParameterUse::In,
                cardinality: super::super::super::operation::Cardinality {
                    min: 0,
                    max: Some(1),
                },
                type_code: Some("boolean"),
                scope: &[],
                source: super::super::super::operation::ParameterSource::Version,
                parts: &[],
            },
            super::super::super::operation::Parameter {
                name: "match",
                usage: super::super::super::operation::ParameterUse::Out,
                cardinality: super::super::super::operation::Cardinality { min: 0, max: None },
                type_code: None,
                scope: &[],
                source: super::super::super::operation::ParameterSource::Version,
                parts: &[
                    super::super::super::operation::Parameter {
                        name: "code",
                        usage: super::super::super::operation::ParameterUse::Out,
                        cardinality: super::super::super::operation::Cardinality {
                            min: 1,
                            max: Some(1),
                        },
                        type_code: Some("Coding"),
                        scope: &[],
                        source: super::super::super::operation::ParameterSource::Version,
                        parts: &[],
                    },
                    super::super::super::operation::Parameter {
                        name: "unmatched",
                        usage: super::super::super::operation::ParameterUse::Out,
                        cardinality: super::super::super::operation::Cardinality {
                            min: 0,
                            max: None,
                        },
                        type_code: None,
                        scope: &[],
                        source: super::super::super::operation::ParameterSource::Version,
                        parts: &[
                            super::super::super::operation::Parameter {
                                name: "code",
                                usage: super::super::super::operation::ParameterUse::Out,
                                cardinality: super::super::super::operation::Cardinality {
                                    min: 1,
                                    max: Some(1),
                                },
                                type_code: Some("code"),
                                scope: &[],
                                source: super::super::super::operation::ParameterSource::Version,
                                parts: &[],
                            },
                            super::super::super::operation::Parameter {
                                name: "value",
                                usage: super::super::super::operation::ParameterUse::Out,
                                cardinality: super::super::super::operation::Cardinality {
                                    min: 1,
                                    max: Some(1),
                                },
                                type_code: Some("Element"),
                                scope: &[],
                                source: super::super::super::operation::ParameterSource::Version,
                                parts: &[],
                            },
                            super::super::super::operation::Parameter {
                                name: "property",
                                usage: super::super::super::operation::ParameterUse::Out,
                                cardinality: super::super::super::operation::Cardinality {
                                    min: 0,
                                    max: None,
                                },
                                type_code: None,
                                scope: &[],
                                source: super::super::super::operation::ParameterSource::Version,
                                parts: &[
                                    super::super::super::operation::Parameter {
                                        name: "code",
                                        usage: super::super::super::operation::ParameterUse::Out,
                                        cardinality: super::super::super::operation::Cardinality {
                                            min: 1,
                                            max: Some(1),
                                        },
                                        type_code: Some("code"),
                                        scope: &[],
                                        source:
                                            super::super::super::operation::ParameterSource::Version,
                                        parts: &[],
                                    },
                                    super::super::super::operation::Parameter {
                                        name: "value",
                                        usage: super::super::super::operation::ParameterUse::Out,
                                        cardinality: super::super::super::operation::Cardinality {
                                            min: 1,
                                            max: Some(1),
                                        },
                                        type_code: Some("Element"),
                                        scope: &[],
                                        source:
                                            super::super::super::operation::ParameterSource::Version,
                                        parts: &[],
                                    },
                                ],
                            },
                        ],
                    },
                    super::super::super::operation::Parameter {
                        name: "comment",
                        usage: super::super::super::operation::ParameterUse::Out,
                        cardinality: super::super::super::operation::Cardinality {
                            min: 0,
                            max: Some(1),
                        },
                        type_code: Some("string"),
                        scope: &[],
                        source: super::super::super::operation::ParameterSource::Version,
                        parts: &[],
                    },
                ],
            },
        ],
    };
